import { scene } from "./build.js";

/** A1 home, daily routine, food, and the body. */
export const dailyScenes = [
  scene({
    id: "a1-home",
    title: "Your home",
    deTitle: "Meine Wohnung",
    place: "Someone asks about your flat.",
    goal: "Say what kind of home you have.",
    canDo: "describe your home in one sentence",
    register: "„Wohnung“ is a flat. „Haus“ is a house.",
    lines: [
      ["Person", "hear", "Wohnen Sie in einer Wohnung?", "Do you live in a flat?", "A yes/no question."],
      ["You", "say", "Ja, in einer kleinen Wohnung.", "Yes, in a small flat.", "„Einer“ after „in“."],
      ["Person", "hear", "Wie viele Zimmer?", "How many rooms?", "„Zimmer“ is a room."],
      ["You", "say", "Zwei Zimmer und eine Küche.", "Two rooms and a kitchen.", "Name the rooms you have."],
      ["Person", "hear", "Das ist praktisch.", "That is practical.", "You can stop."],
    ],
    checks: [
      [2, "Your flat is small.", "In einer kleinen Wohnung.", "In einem großen Haus nur.", "Wohnung ist dreißig Jahre.", "„Klein“ is small."],
      [4, "Two rooms and a kitchen.", "Zwei Zimmer und eine Küche.", "Zwei Uhren und eine Küche Zeit.", "Zimmer wohne ich.", "„Zimmer“ and „Küche“ are parts of the home."],
      [3, "„Wie viele Zimmer?“", "How many rooms?", "How many children?", "What time is the kitchen?", "They ask the number of rooms."],
    ],
  }),
  scene({
    id: "a1-rooms",
    title: "Rooms",
    deTitle: "Die Zimmer",
    place: "A guest asks where the bathroom is.",
    goal: "Name the rooms and point someone there.",
    canDo: "name the rooms in a home",
    register: "„Das Bad“, „die Küche“, „das Schlafzimmer“.",
    lines: [
      ["Guest", "hear", "Wo ist das Bad?", "Where is the bathroom?", "„Bad“ is the bathroom."],
      ["You", "say", "Das Bad ist hier links.", "The bathroom is here on the left.", "„Links“ is left."],
      ["Guest", "hear", "Und die Küche?", "And the kitchen?", "A second room."],
      ["You", "say", "Die Küche ist neben dem Wohnzimmer.", "The kitchen is next to the living room.", "„Neben“ means next to."],
      ["Guest", "hear", "Danke, ich finde es.", "Thanks, I'll find it.", "They are fine."],
    ],
    checks: [
      [1, "They want the bathroom.", "Wo ist das Bad?", "Wo ist der Bahnhof?", "Wie spät ist das Bad?", "„Bad“ is the bathroom."],
      [2, "It is on the left.", "Hier links.", "Hier rechts um zehn.", "Links ist ein Monat.", "„Links“ is left."],
      [4, "The kitchen is next to the living room.", "Neben dem Wohnzimmer.", "Unter der Uhr.", "Im Juli.", "„Neben“ is next to. „Wohnzimmer“ is the living room."],
    ],
  }),
  scene({
    id: "a1-furniture",
    title: "In the room",
    deTitle: "Möbel",
    place: "You tell a guest where to sit.",
    goal: "Name a table, a chair, and a bed.",
    canDo: "name basic furniture",
    register: "„Der Stuhl“, „der Tisch“, „das Bett“.",
    lines: [
      ["You", "say", "Bitte, der Stuhl am Tisch.", "Please, the chair at the table.", "Offer a seat."],
      ["Guest", "hear", "Danke. Ist das Ihr Platz?", "Thanks. Is that your seat?", "They check."],
      ["You", "say", "Nein, bitte setzen Sie sich.", "No, please sit down.", "„Sich setzen“ is to sit down."],
      ["Guest", "hear", "Wo schlafen die Kinder?", "Where do the children sleep?", "A simple follow-up."],
      ["You", "say", "Im Schlafzimmer, in dem Bett dort.", "In the bedroom, in that bed.", "„Bett“ is the bed."],
    ],
    checks: [
      [1, "You point to the chair.", "Der Stuhl am Tisch.", "Die Uhr am Tisch.", "Der Stuhl ist dreißig Euro nur.", "„Stuhl“ is the chair. „Tisch“ is the table."],
      [3, "You want them to sit.", "Bitte setzen Sie sich.", "Bitte buchstabieren Sie.", "Bitte um halb drei.", "„Setzen Sie sich“ is sit down."],
      [5, "The bed is in the bedroom.", "Im Schlafzimmer.", "In der Küche am Herd nur.", "Auf der Straße.", "„Schlafzimmer“ is where the bed is."],
    ],
  }),
  scene({
    id: "a1-routine",
    title: "A normal day",
    deTitle: "Mein Tag",
    place: "A classmate asks what you do all day.",
    goal: "Say a short daily routine.",
    canDo: "describe a simple daily routine",
    register: "Present tense. „Zuerst …, dann …“.",
    lines: [
      ["Classmate", "hear", "Was machst du morgens?", "What do you do in the morning?", "„Du“ with a classmate."],
      ["You", "say", "Ich stehe um sieben Uhr auf.", "I get up at seven.", "„Aufstehen“ splits: ich stehe … auf."],
      ["Classmate", "hear", "So früh?", "That early?", "They react."],
      ["You", "say", "Ja. Dann frühstücke ich und gehe zur Arbeit.", "Yes. Then I have breakfast and go to work.", "„Dann“ orders the day."],
      ["Classmate", "hear", "Und abends?", "And in the evening?", "The other end of the day."],
    ],
    checks: [
      [2, "You get up at 7.", "Ich stehe um sieben Uhr auf.", "Ich wohne um sieben.", "Sieben ist mein Beruf.", "„Aufstehen“ is to get up."],
      [4, "Then breakfast and work.", "Dann frühstücke ich und gehe zur Arbeit.", "Dann schlafe ich im Büro.", "Arbeit ist ein Monat.", "„Frühstücken“ and „Arbeit“ are the next steps."],
      [1, "„Was machst du morgens?“", "What do you do in the morning?", "What is your name in the morning?", "How much is the morning?", "„Morgens“ is in the mornings."],
    ],
  }),
  scene({
    id: "a1-evening",
    title: "The evening",
    deTitle: "Am Abend",
    place: "The same classmate asks about the evening.",
    goal: "Say what you do after work.",
    canDo: "talk about the evening",
    register: "„Am Abend“ is in the evening. „Um … ins Bett“.",
    lines: [
      ["You", "say", "Am Abend koche ich.", "In the evening I cook.", "„Kochen“ is to cook."],
      ["Classmate", "hear", "Jeden Abend?", "Every evening?", "„Jeden“ is every."],
      ["You", "say", "Oft. Manchmal esse ich Brot.", "Often. Sometimes I eat bread.", "„Oft“ and „manchmal“ are A1 frequency words."],
      ["Classmate", "hear", "Wann gehst du ins Bett?", "When do you go to bed?", "„Ins Bett gehen“."],
      ["You", "say", "Um elf Uhr.", "At eleven.", "A time is enough."],
    ],
    checks: [
      [1, "In the evening you cook.", "Am Abend koche ich.", "Am Abend heiße ich.", "Kochen ist um halb Name.", "„Kochen“ is cooking."],
      [3, "Not every evening.", "Oft. Manchmal Brot.", "Immer um drei Uhr nur schlafen.", "Nie, ich wohne Brot.", "„Oft“ is often. „Manchmal“ is sometimes."],
      [5, "Bedtime.", "Um elf Uhr.", "Um elf Euro.", "Elf Zimmer.", "Eleven o'clock."],
    ],
  }),
  scene({
    id: "a1-breakfast",
    title: "Breakfast",
    deTitle: "Frühstück",
    place: "You are in a café in the morning.",
    goal: "Order a simple breakfast.",
    canDo: "order breakfast",
    register: "„Ich hätte gern …“ is the polite order.",
    lines: [
      ["You", "say", "Ich hätte gern ein Frühstück.", "I would like a breakfast.", "„Hätte gern“ is more polite than „will“."],
      ["Staff", "hear", "Mit Brot, Käse und Kaffee?", "With bread, cheese, and coffee?", "They list the parts."],
      ["You", "say", "Ja. Und ein Ei, bitte.", "Yes. And an egg, please.", "Add one thing."],
      ["Staff", "hear", "Kaffee oder Tee?", "Coffee or tea?", "A choice."],
      ["You", "say", "Kaffee, bitte.", "Coffee, please.", "Choose one."],
    ],
    checks: [
      [1, "Order breakfast politely.", "Ich hätte gern ein Frühstück.", "Ich bin ein Frühstück.", "Frühstück wohnt hier.", "„Hätte gern“ places an order."],
      [2, "Bread, cheese, and coffee.", "Brot, Käse und Kaffee.", "Brot, Bus und Bahnhof.", "Käse ist ein Wochentag.", "Those are breakfast foods."],
      [4, "They offer two drinks.", "Kaffee oder Tee.", "Kaffee oder Tisch.", "Tee um halb drei nur.", "Coffee or tea."],
    ],
  }),
  scene({
    id: "a1-hungry",
    title: "Hungry and thirsty",
    deTitle: "Hunger und Durst",
    place: "A friend asks if you want to eat.",
    goal: "Say you are hungry or thirsty.",
    canDo: "say you are hungry or thirsty",
    register: "„Ich habe Hunger.“ Not „ich bin Hunger“.",
    lines: [
      ["Friend", "hear", "Hast du Hunger?", "Are you hungry?", "„Hunger“ with „haben“."],
      ["You", "say", "Ja, ich habe Hunger.", "Yes, I am hungry.", "„Haben“, not „sein“."],
      ["Friend", "hear", "Und Durst?", "And thirsty?", "„Durst“ is thirst."],
      ["You", "say", "Auch Durst. Ich nehme Wasser.", "Thirsty too. I'll have water.", "„Nehmen“ is to take, here to choose."],
      ["Friend", "hear", "Gut, wir essen etwas.", "Good, we'll eat something.", "The plan is to eat."],
    ],
    checks: [
      [2, "You are hungry.", "Ich habe Hunger.", "Ich bin Hunger.", "Hunger ist drei Uhr.", "German uses „haben“ with Hunger."],
      [4, "You want water.", "Ich nehme Wasser.", "Ich wohne Wasser.", "Wasser heiße ich.", "„Nehmen“ chooses the drink."],
      [3, "„Durst“.", "Thirst.", "A room.", "A weekday.", "„Durst“ means you want a drink."],
    ],
  }),
  scene({
    id: "a1-menu",
    title: "At a restaurant",
    deTitle: "Die Speisekarte",
    place: "You sit down and the menu is in German.",
    goal: "Ask for the menu and order a meal.",
    canDo: "order a meal in a restaurant",
    register: "„Die Speisekarte“ is the menu. „Als Vorspeise / Hauptgericht“ can wait. Keep it to one dish.",
    lines: [
      ["You", "say", "Die Speisekarte, bitte.", "The menu, please.", "Ask before you order."],
      ["Staff", "hear", "Hier, bitte. Möchten Sie etwas trinken?", "Here you are. Would you like a drink?", "„Möchten“ is would you like."],
      ["You", "say", "Ein Wasser, und dann die Suppe.", "A water, and then the soup.", "Drink plus one dish."],
      ["Staff", "hear", "Die Tagessuppe?", "The soup of the day?", "They check which soup."],
      ["You", "say", "Ja, die Tagessuppe.", "Yes, the soup of the day.", "Confirm."],
    ],
    checks: [
      [1, "You need the menu.", "Die Speisekarte, bitte.", "Die Telefonnummer, bitte.", "Wie spät ist die Karte?", "„Speisekarte“ is the menu."],
      [3, "Water and soup.", "Ein Wasser, und dann die Suppe.", "Ein Tisch, und dann die Uhr.", "Suppe ist mein Name.", "Those are the drink and the dish."],
      [2, "„Möchten Sie etwas trinken?“", "Would you like a drink?", "What is your job?", "Where is the soup from?", "„Trinken“ is to drink. „Möchten“ is the polite want."],
    ],
  }),
  scene({
    id: "a1-like",
    title: "What you like to eat",
    deTitle: "Das schmeckt",
    place: "Someone asks what you like.",
    goal: "Say you like or do not like a food.",
    canDo: "say what food you like",
    register: "„Ich mag …“ is I like. „Ich mag … nicht“ is I don't like.",
    lines: [
      ["Person", "hear", "Was isst du gern?", "What do you like to eat?", "„Gern“ means gladly, with pleasure."],
      ["You", "say", "Ich mag Nudeln.", "I like pasta.", "„Mag“ is the present of „mögen“."],
      ["Person", "hear", "Und Fisch?", "And fish?", "They offer another food."],
      ["You", "say", "Fisch mag ich nicht.", "I don't like fish.", "„Nicht“ at the end of this short sentence."],
      ["Person", "hear", "Dann nehmen wir Nudeln.", "Then we'll have pasta.", "They choose what you like."],
    ],
    checks: [
      [2, "You like pasta.", "Ich mag Nudeln.", "Ich bin Nudeln.", "Nudeln wohnen hier.", "„Mögen“ is to like."],
      [4, "You do not like fish.", "Fisch mag ich nicht.", "Fisch mag ich sehr.", "Ich habe Fisch als Beruf.", "„Nicht“ negates the liking."],
      [1, "„Was isst du gern?“", "What do you like eating?", "What time do you eat?", "Where is the pasta?", "„Gern“ asks for a preference."],
    ],
  }),
  scene({
    id: "a1-diet",
    title: "No meat",
    deTitle: "Vegetarisch",
    place: "You tell the restaurant what you do not eat.",
    goal: "Say a simple food limit.",
    canDo: "say you do not eat meat",
    register: "„Kein Fleisch“ uses „kein“, not „nicht ein“.",
    lines: [
      ["Staff", "hear", "Möchten Sie Fleisch oder Fisch?", "Would you like meat or fish?", "Two options you may refuse."],
      ["You", "say", "Kein Fleisch, bitte. Ich esse vegetarisch.", "No meat, please. I eat vegetarian.", "„Kein“ plus the noun."],
      ["Staff", "hear", "Gemüse und Reis?", "Vegetables and rice?", "A fitting dish."],
      ["You", "say", "Ja, Gemüse ist gut.", "Yes, vegetables are good.", "Accept."],
      ["Staff", "hear", "Kommt sofort.", "Coming right away.", "The kitchen has the order."],
    ],
    checks: [
      [2, "You eat no meat.", "Kein Fleisch. Ich esse vegetarisch.", "Nicht ein Fleisch Uhr.", "Fleisch ist ein Zimmer.", "„Kein“ negates the noun „Fleisch“."],
      [3, "They offer vegetables and rice.", "Gemüse und Reis.", "Gemüse und Bahnhof.", "Reis ist ein Wochentag.", "Those are foods."],
      [1, "They ask meat or fish.", "You can refuse both.", "You must choose a time.", "You must spell your name.", "The question is about food, and you can say no."],
    ],
  }),
  scene({
    id: "a1-market",
    title: "At the market",
    deTitle: "Auf dem Markt",
    place: "A stall sells fruit. You want apples.",
    goal: "Buy food by the kilo.",
    canDo: "buy fruit at a market",
    register: "„Ein Kilo“ is one kilogram. „Hundert Gramm“ is 100 grams.",
    lines: [
      ["Seller", "hear", "Was darf es sein?", "What would you like?", "A market greeting."],
      ["You", "say", "Ein Kilo Äpfel, bitte.", "One kilo of apples, please.", "Amount plus food."],
      ["Seller", "hear", "Die Äpfel sind süß.", "The apples are sweet.", "They describe them."],
      ["You", "say", "Gut. Und zweihundert Gramm Käse.", "Good. And 200 grams of cheese.", "A second item, in grams."],
      ["Seller", "hear", "Äpfel und Käse. Sonst noch?", "Apples and cheese. Anything else?", "They repeat the order."],
    ],
    checks: [
      [2, "One kilogram of apples.", "Ein Kilo Äpfel.", "Ein Kilo Uhr.", "Äpfel sind mein Beruf.", "„Kilo“ is the amount. „Äpfel“ is apples."],
      [4, "200 grams of cheese.", "Zweihundert Gramm Käse.", "Zweihundert Euro Käse Zeit.", "Gramm ist ein Monat.", "„Gramm“ is the weight."],
      [3, "„Süß.“", "Sweet.", "Expensive.", "Closed.", "„Süß“ describes the taste."],
    ],
  }),
  scene({
    id: "a1-bakery",
    title: "At the bakery",
    deTitle: "Beim Bäcker",
    place: "You want bread and a bread roll.",
    goal: "Buy bread with the right words.",
    canDo: "buy bread at a bakery",
    register: "„Ein Brot“, „ein Brötchen“. „Noch ein“ is one more.",
    lines: [
      ["You", "say", "Ein Brot und zwei Brötchen, bitte.", "One loaf and two rolls, please.", "„Brötchen“ is a bread roll."],
      ["Baker", "hear", "Das Brot ist von heute.", "The bread is from today.", "Fresh today."],
      ["You", "say", "Gut. Noch ein Brötchen, bitte.", "Good. One more roll, please.", "„Noch ein“ adds one."],
      ["Baker", "hear", "Drei Brötchen und ein Brot.", "Three rolls and one loaf.", "They correct the count."],
      ["You", "say", "Ja, genau.", "Yes, exactly.", "Confirm the new count."],
    ],
    checks: [
      [1, "A loaf and two rolls.", "Ein Brot und zwei Brötchen.", "Ein Brot und zwei Bahnhöfe.", "Brötchen ist die Uhrzeit.", "„Brot“ is the loaf. „Brötchen“ is the roll."],
      [3, "You add one roll.", "Noch ein Brötchen.", "Kein Brötchen mehr.", "Brötchen um drei Uhr.", "„Noch ein“ means one more."],
      [4, "The new total.", "Three rolls and one loaf.", "Two rolls and one loaf.", "Three loaves.", "They said drei Brötchen."],
    ],
  }),
  scene({
    id: "a1-drink",
    title: "Something to drink",
    deTitle: "Etwas trinken",
    place: "You are thirsty in a café.",
    goal: "Order water, coffee, or tea.",
    canDo: "order a drink",
    register: "„Mit Milch“, „ohne Zucker“.",
    lines: [
      ["You", "say", "Einen Kaffee, bitte.", "A coffee, please.", "„Einen“ because „Kaffee“ is masculine, and you order it."],
      ["Staff", "hear", "Mit Milch und Zucker?", "With milk and sugar?", "The usual question."],
      ["You", "say", "Mit Milch, ohne Zucker.", "With milk, without sugar.", "„Ohne“ means without."],
      ["Staff", "hear", "Zum Hiertrinken oder zum Mitnehmen?", "To drink here or to take away?", "Two options."],
      ["You", "say", "Zum Mitnehmen.", "To take away.", "Choose one."],
    ],
    checks: [
      [3, "Milk, no sugar.", "Mit Milch, ohne Zucker.", "Ohne Milch, mit Zucker immer.", "Zucker ist ein Zimmer.", "„Ohne“ removes the sugar."],
      [5, "You will leave with the coffee.", "Zum Mitnehmen.", "Zum Hiertrinken.", "Zum Bahnhof um drei.", "„Mitnehmen“ is take away."],
      [1, "Order a coffee.", "Einen Kaffee, bitte.", "Eine Kaffee Uhr.", "Kaffee wohne ich.", "The drink is coffee, accusative „einen“."],
    ],
  }),
  scene({
    id: "a1-pay",
    title: "The bill",
    deTitle: "Zahlen, bitte",
    place: "You have finished the coffee.",
    goal: "Ask to pay and hear the price.",
    canDo: "ask for the bill and pay",
    register: "„Zahlen, bitte“ is enough. „Zusammen oder getrennt?“ is together or separate.",
    lines: [
      ["You", "say", "Zahlen, bitte.", "The bill, please.", "This is the normal phrase."],
      ["Staff", "hear", "Zusammen oder getrennt?", "Together or separate?", "If you are more than one."],
      ["You", "say", "Zusammen.", "Together.", "One person pays."],
      ["Staff", "hear", "Das macht acht Euro fünfzig.", "That comes to 8.50.", "Euro, then cents."],
      ["You", "say", "Mit Karte, bitte.", "By card, please.", "„Karte“ is the card. „Bar“ is cash."],
    ],
    checks: [
      [1, "You want to pay.", "Zahlen, bitte.", "Buchstabieren, bitte.", "Wo ist das Bad?", "„Zahlen“ here is to pay."],
      [4, "The price.", "8 euros 50.", "8 euros 15.", "50 euros.", "„Acht Euro fünfzig“ is 8.50."],
      [5, "You pay by card.", "Mit Karte.", "Mit Kaffee.", "Bar, und kein Karte-Wort.", "„Karte“ is the bank card here."],
    ],
  }),
  scene({
    id: "a1-body",
    title: "Parts of the body",
    deTitle: "Der Körper",
    place: "A doctor asks what hurts. You name the place.",
    goal: "Name head, stomach, and arm.",
    canDo: "name basic body parts",
    register: "„Der Kopf“, „der Bauch“, „der Arm“, „das Bein“.",
    lines: [
      ["Doctor", "hear", "Wo tut es weh?", "Where does it hurt?", "„Weh tun“ is to hurt."],
      ["You", "say", "Der Kopf tut weh.", "My head hurts.", "Body part plus „tut weh“."],
      ["Doctor", "hear", "Und der Bauch?", "And your stomach?", "They check another place."],
      ["You", "say", "Der Bauch ist okay. Der linke Arm auch ein bisschen.", "The stomach is okay. The left arm a bit too.", "„Der linke Arm“ is the left arm."],
      ["Doctor", "hear", "Kopf und linker Arm. Verstehe.", "Head and left arm. I understand.", "They repeat it."],
    ],
    checks: [
      [2, "Your head hurts.", "Der Kopf tut weh.", "Der Kopf ist geöffnet.", "Kopf kostet acht Euro.", "„Tut weh“ means it hurts."],
      [4, "The left arm, a little.", "Der linke Arm.", "Das linke Bein nur.", "Der Arm ist ein Monat.", "„Arm“ is the arm. „Links“ is left."],
      [1, "„Wo tut es weh?“", "Where does it hurt?", "Where do you live?", "What time is it?", "„Weh“ is pain."],
    ],
  }),
  scene({
    id: "a1-sick",
    title: "You are ill",
    deTitle: "Ich bin krank",
    place: "You call work because you cannot come.",
    goal: "Say you are ill.",
    canDo: "say you are ill",
    register: "„Ich bin krank.“ „Ich habe Fieber.“",
    lines: [
      ["You", "say", "Guten Morgen. Ich bin krank.", "Good morning. I am ill.", "Say it early in the call."],
      ["Colleague", "hear", "Was haben Sie?", "What do you have?", "They mean the symptoms."],
      ["You", "say", "Ich habe Fieber und Husten.", "I have a fever and a cough.", "„Fieber“ and „Husten“."],
      ["Colleague", "hear", "Bleiben Sie heute zu Hause.", "Stay home today.", "„Zu Hause“ is at home."],
      ["You", "say", "Ja. Morgen bin ich hoffentlich wieder da.", "Yes. Tomorrow I will hopefully be back.", "„Hoffentlich“ is hopefully."],
    ],
    checks: [
      [1, "Tell them you are ill.", "Ich bin krank.", "Ich bin Hunger.", "Krank ist die Adresse.", "„Krank“ uses „sein“."],
      [3, "Fever and a cough.", "Fieber und Husten.", "Fieber und Brötchen.", "Husten ist ein Zimmer.", "Those are symptoms."],
      [4, "They want you at home.", "Bleiben Sie zu Hause.", "Kommen Sie sofort ins Büro.", "Gehen Sie auf den Markt.", "„Zu Hause bleiben“ is to stay home."],
    ],
  }),
  scene({
    id: "a1-pharmacy",
    title: "At the pharmacy",
    deTitle: "In der Apotheke",
    place: "You need something for a headache.",
    goal: "Ask for a simple medicine.",
    canDo: "ask for help in a pharmacy",
    register: "„Die Apotheke“ is the pharmacy. „Gegen“ means against, for a symptom.",
    lines: [
      ["You", "say", "Ich brauche etwas gegen Kopfschmerzen.", "I need something for a headache.", "„Gegen“ plus the problem."],
      ["Pharmacist", "hear", "Haben Sie Allergien?", "Do you have allergies?", "A safety question."],
      ["You", "say", "Nein, keine Allergien.", "No, no allergies.", "„Keine“ with the plural noun."],
      ["Pharmacist", "hear", "Dann diese Tabletten. Dreimal am Tag.", "Then these tablets. Three times a day.", "„Dreimal“ is three times."],
      ["You", "say", "Dreimal. Danke.", "Three times. Thanks.", "Repeat the instruction."],
    ],
    checks: [
      [1, "You need help for a headache.", "Etwas gegen Kopfschmerzen.", "Etwas gegen den Bahnhof.", "Kopfschmerzen ist mein Beruf.", "„Gegen Kopfschmerzen“ is for a headache."],
      [3, "You have no allergies.", "Keine Allergien.", "Viele Allergien, ja.", "Allergie um drei Uhr.", "„Keine“ is the negative."],
      [4, "How often.", "Three times a day.", "Three tablets for a year.", "Once on Sunday.", "„Dreimal am Tag“ is three times a day."],
    ],
  }),
  scene({
    id: "a1-doctor",
    title: "At the doctor",
    deTitle: "Beim Arzt",
    place: "You have an appointment.",
    goal: "Say why you came.",
    canDo: "say why you are at the doctor",
    register: "„Ich habe einen Termin.“ „Seit zwei Tagen.“",
    lines: [
      ["Doctor", "hear", "Was fehlt Ihnen?", "What is wrong?", "The standard doctor question."],
      ["You", "say", "Ich habe seit zwei Tagen Halsschmerzen.", "I have had a sore throat for two days.", "„Seit“ plus how long."],
      ["Doctor", "hear", "Fieber auch?", "Fever too?", "One more symptom."],
      ["You", "say", "Nein, nur der Hals.", "No, only the throat.", "„Nur“ means only."],
      ["Doctor", "hear", "Ich schaue mir das an.", "I'll take a look.", "The exam starts."],
    ],
    checks: [
      [1, "„Was fehlt Ihnen?“", "What is wrong?", "What is your address?", "How much is the visit?", "This question asks about the illness."],
      [2, "A sore throat for two days.", "Seit zwei Tagen Halsschmerzen.", "Seit zwei Uhren.", "Hals ist ein Kilo.", "„Hals“ is the throat. „Seit zwei Tagen“ is the length."],
      [4, "Only the throat.", "Nur der Hals.", "Auch Fieber und Husten.", "Der Hals ist geöffnet.", "„Nur“ limits it to the throat."],
    ],
  }),
  scene({
    id: "a1-weather",
    title: "The weather",
    deTitle: "Das Wetter",
    place: "Someone at the door talks about the day.",
    goal: "Describe today's weather.",
    canDo: "describe the weather",
    register: "„Es regnet“, „die Sonne scheint“, „es ist kalt“.",
    lines: [
      ["Neighbor", "hear", "Wie ist das Wetter heute?", "How is the weather today?", "A common small-talk question."],
      ["You", "say", "Es regnet.", "It is raining.", "„Regnen“ for rain. Subject is „es“."],
      ["Neighbor", "hear", "Gestern hat die Sonne geschienen.", "Yesterday the sun shone.", "You only need to understand this. Your answer stays in the present."],
      ["You", "say", "Ja. Heute ist es kalt.", "Yes. Today it is cold.", "„Kalt“ is cold. „Warm“ is warm."],
      ["Neighbor", "hear", "Nehmen Sie eine Jacke.", "Take a jacket.", "A practical result."],
    ],
    checks: [
      [2, "It is raining.", "Es regnet.", "Es ist ein Brot.", "Regen wohnt in Hamburg.", "„Es regnet“ is the weather sentence."],
      [4, "Today is cold.", "Heute ist es kalt.", "Heute ist es dreißig Euro.", "Kalt ist ein Wochentag.", "„Kalt“ describes the temperature."],
      [5, "They mention a jacket.", "Because it is cold and wet.", "Because you need a ticket.", "Because the shop is closed.", "A jacket matches rain and cold."],
    ],
  }),
  scene({
    id: "a1-clothes",
    title: "What you wear",
    deTitle: "Kleidung",
    place: "You get dressed and name the clothes.",
    goal: "Name jacket, trousers, and shoes.",
    canDo: "name basic clothes",
    register: "„Die Jacke“, „die Hose“, „die Schuhe“.",
    lines: [
      ["Friend", "hear", "Was ziehst du an?", "What are you putting on?", "„Anziehen“ is to put on."],
      ["You", "say", "Eine Jacke, eine Hose und Schuhe.", "A jacket, trousers, and shoes.", "Three clothing words."],
      ["Friend", "hear", "Die blaue Jacke?", "The blue jacket?", "„Blau“ is blue."],
      ["You", "say", "Nein, die schwarze.", "No, the black one.", "„Schwarz“ is black."],
      ["Friend", "hear", "Die steht dir gut.", "That suits you.", "A friendly comment. „Dir“ is you, informal."],
    ],
    checks: [
      [2, "Jacket, trousers, shoes.", "Jacke, Hose und Schuhe.", "Jacke, Suppe und Schuhe Zeit.", "Hose ist ein Getränk.", "Those are clothes."],
      [4, "The black jacket.", "Die schwarze.", "Die blaue.", "Die Jacke um zehn Uhr.", "„Schwarz“ is black. You said no to blue."],
      [3, "„Blau.“", "Blue.", "Black.", "Small.", "„Blau“ is the color blue."],
    ],
  }),
  scene({
    id: "a1-size",
    title: "A size in a shop",
    deTitle: "Die Größe",
    place: "You try a jacket.",
    goal: "Ask for another size.",
    canDo: "ask for a size",
    register: "„Größe M“, „zu klein“, „zu groß“.",
    lines: [
      ["You", "say", "Haben Sie das in Größe M?", "Do you have this in size M?", "„Größe“ is the size."],
      ["Staff", "hear", "M ist da. Passt es?", "M is here. Does it fit?", "„Passen“ is to fit."],
      ["You", "say", "Es ist zu klein.", "It is too small.", "„Zu“ before the adjective means too."],
      ["Staff", "hear", "Dann Größe L.", "Then size L.", "One size up."],
      ["You", "say", "Ja, L ist besser.", "Yes, L is better.", "„Besser“ is better."],
    ],
    checks: [
      [1, "You want size M.", "Haben Sie das in Größe M?", "Haben Sie das um drei Uhr?", "Größe ist mein Name.", "„Größe“ is the clothing size."],
      [3, "It does not fit. It is small.", "Es ist zu klein.", "Es ist zu warm.", "Klein kostet fünfzig.", "„Zu klein“ is too small."],
      [5, "L is the better size.", "L ist besser.", "M ist besser.", "Besser ist ein Kilo.", "You accepted L."],
    ],
  }),
  scene({
    id: "a1-colors",
    title: "Colors",
    deTitle: "Farben",
    place: "You choose a shirt.",
    goal: "Name four colors.",
    canDo: "name basic colors",
    register: "„Rot, blau, grün, schwarz, weiß“.",
    lines: [
      ["Staff", "hear", "Welche Farbe?", "Which color?", "„Farbe“ is color."],
      ["You", "say", "Blau oder grün.", "Blue or green.", "Two colors."],
      ["Staff", "hear", "Grün haben wir nicht. Rot?", "We don't have green. Red?", "They offer another."],
      ["You", "say", "Nein. Dann das weiße Hemd.", "No. Then the white shirt.", "„Weiß“ is white. „Hemd“ is shirt."],
      ["Staff", "hear", "Das weiße Hemd in M.", "The white shirt in M.", "Color plus size."],
    ],
    checks: [
      [2, "Blue or green.", "Blau oder grün.", "Blau oder Brot.", "Grün ist acht Euro.", "Those are colors."],
      [4, "The white shirt.", "Das weiße Hemd.", "Das schwarze Brot.", "Hemd ist eine Uhrzeit.", "„Weiß“ is white. „Hemd“ is the shirt."],
      [3, "They do not have green.", "Grün haben wir nicht.", "Grün ist zu groß.", "Grün kostet extra.", "„Nicht“ says it is not available."],
    ],
  }),
  scene({
    id: "a1-seasons",
    title: "The seasons",
    deTitle: "Die Jahreszeiten",
    place: "You say which season you like.",
    goal: "Name summer and winter.",
    canDo: "name the seasons",
    register: "„Der Sommer“, „der Winter“, „der Frühling“, „der Herbst“.",
    lines: [
      ["Friend", "hear", "Welche Jahreszeit magst du?", "Which season do you like?", "„Jahreszeit“ is a season."],
      ["You", "say", "Ich mag den Sommer.", "I like summer.", "„Den“ because „Sommer“ is masculine, after „mögen“."],
      ["Friend", "hear", "Nicht den Winter?", "Not winter?", "„Winter“ is winter."],
      ["You", "say", "Nein, im Winter ist es zu kalt.", "No, in winter it is too cold.", "„Im Winter“."],
      ["Friend", "hear", "Ich mag den Herbst.", "I like autumn.", "„Herbst“ is autumn. You only need to recognize it."],
    ],
    checks: [
      [2, "You like summer.", "Ich mag den Sommer.", "Ich mag den Montag Sommer.", "Sommer ist eine Größe.", "„Sommer“ is summer."],
      [4, "Winter is too cold.", "Im Winter ist es zu kalt.", "Im Winter ist es zu süß.", "Winter kostet fünfzig.", "Cold belongs to winter here."],
      [5, "„Herbst“.", "Autumn.", "Spring only.", "Monday.", "„Herbst“ is autumn. „Frühling“ would be spring."],
    ],
  }),
  scene({
    id: "a1-post",
    title: "At the post office",
    deTitle: "Bei der Post",
    place: "You want to send a letter.",
    goal: "Buy a stamp and send a letter.",
    canDo: "send a letter at the post office",
    register: "„Ein Brief“, „eine Briefmarke“, „nach China“.",
    lines: [
      ["You", "say", "Ich möchte diesen Brief nach China schicken.", "I would like to send this letter to China.", "„Schicken“ is to send."],
      ["Staff", "hear", "Ein Brief, wohin?", "One letter, where to?", "They confirm the destination."],
      ["You", "say", "Nach China. Was kostet die Briefmarke?", "To China. What does the stamp cost?", "„Briefmarke“ is the stamp."],
      ["Staff", "hear", "Eins achtzig.", "One euro eighty.", "The price of the stamp."],
      ["You", "say", "Eine Briefmarke, bitte.", "One stamp, please.", "You buy it."],
    ],
    checks: [
      [1, "You want to send a letter to China.", "Diesen Brief nach China schicken.", "Einen Kaffee nach China.", "China ist die Briefmarke.", "„Brief“ is the letter. „Nach“ is the destination."],
      [3, "Ask the price of the stamp.", "Was kostet die Briefmarke?", "Wo ist die Post um drei?", "Briefmarke ist ein Wochentag.", "„Briefmarke“ is the stamp."],
      [4, "The stamp costs.", "1.80 euros.", "180 euros.", "Eight stamps.", "„Eins achtzig“ is 1.80."],
    ],
  }),
  scene({
    id: "a1-status",
    title: "Family status",
    deTitle: "Familienstand",
    place: "A form asks if you are married.",
    goal: "Say your family status.",
    canDo: "say whether you are married",
    register: "„Ledig“ is single. „Verheiratet“ is married.",
    lines: [
      ["Staff", "hear", "Wie ist Ihr Familienstand?", "What is your marital status?", "A standard form question."],
      ["You", "say", "Ich bin ledig.", "I am single.", "Use „verheiratet“ if you are married."],
      ["Staff", "hear", "Haben Sie Kinder?", "Do you have children?", "The next box."],
      ["You", "say", "Nein, ich habe keine Kinder.", "No, I have no children.", "„Keine“ with the plural."],
      ["Staff", "hear", "Danke. Das war alles.", "Thanks. That was all.", "The form is done."],
    ],
    checks: [
      [1, "„Familienstand“.", "Married or single.", "Your address.", "Your shoe size.", "It asks about marriage, not the street."],
      [2, "You are single.", "Ich bin ledig.", "Ich bin verheiratet.", "Ledig ist eine Stadt.", "„Ledig“ means single."],
      [4, "No children.", "Ich habe keine Kinder.", "Ich habe zwei Kinder.", "Kinder ist der Familienstand selbst.", "„Keine Kinder“ is none."],
    ],
  }),
];
