import { scene } from "./build.js";

/**
 * Start Deutsch 1 tasks and the inventory those tasks still needed:
 * listening for a fact, reading a short text, the form and the 30-word message,
 * speaking (introduce, spell, ask, request), plus the grammar the exam may use.
 */
export const examScenes = [
  scene({
    id: "a1-x-phone",
    title: "A phone message",
    deTitle: "Eine Nachricht",
    place: "A practice calls and leaves a message. In the exam you hear this once or twice.",
    goal: "Catch the day, the time, and the room.",
    canDo: "understand a short phone message",
    register: "Listening. Note the day, the time, and the place.",
    lines: [
      ["Message", "hear", "Guten Tag. Hier ist die Praxis Berg.", "Hello. This is the Berg practice.", "The caller says who they are first."],
      ["Message", "hear", "Ihr Termin ist am Donnerstag.", "Your appointment is on Thursday.", "The day is the first fact."],
      ["Message", "hear", "Kommen Sie um zehn Uhr.", "Come at ten.", "„Um“ plus the time."],
      ["Message", "hear", "Zimmer drei, im ersten Stock.", "Room 3, one floor up.", "In Germany the ground floor is the Erdgeschoss. The first floor is one up."],
      ["Message", "hear", "Bringen Sie Ihre Karte mit. Auf Wiederhören.", "Bring your card. Goodbye.", "„Auf Wiederhören“ ends a phone call."],
    ],
    checks: [
      [2, "Which day is the appointment?", "Thursday.", "Tuesday.", "Every morning.", "They said Donnerstag."],
      [3, "What time?", "10:00.", "3:00.", "10 euros.", "„Um zehn Uhr“ is the time."],
      [4, "Where do you go?", "Room 3, one floor up.", "Platform 3.", "The bank.", "„Zimmer drei“ and „im ersten Stock“."],
    ],
  }),
  scene({
    id: "a1-x-announce",
    title: "An announcement",
    deTitle: "Eine Durchsage",
    place: "You are in the station. A loudspeaker speaks.",
    goal: "Catch the platform, the time, and the delay.",
    canDo: "understand a station announcement",
    register: "Listening. One announcement, three facts.",
    lines: [
      ["Speaker", "hear", "Achtung, eine Durchsage.", "Attention, an announcement.", "This word starts many exam audios."],
      ["Speaker", "hear", "Der Zug nach Berlin fährt von Gleis sieben.", "The train to Berlin leaves from platform 7.", "Platform."],
      ["Speaker", "hear", "Abfahrt um vierzehn Uhr zwanzig.", "Departure at 14:20.", "The clock time."],
      ["Speaker", "hear", "Der Zug kommt zehn Minuten später.", "The train is ten minutes late.", "„Später“ is later."],
      ["Speaker", "hear", "Wir bitten um Entschuldigung.", "We apologize.", "A set phrase. You do not answer it."],
    ],
    checks: [
      [2, "Which platform?", "7", "2", "14", "„Gleis sieben“ is platform 7."],
      [3, "Departure on the clock.", "14:20", "14:10", "7:20", "„Vierzehn Uhr zwanzig“ is 14:20."],
      [4, "The train is.", "10 minutes late.", "Cancelled.", "10 euros.", "„Zehn Minuten später“ is a delay, not a new price."],
    ],
  }),
  scene({
    id: "a1-x-speaker",
    title: "In the supermarket",
    deTitle: "Im Supermarkt",
    place: "A loudspeaker in the shop.",
    goal: "Catch a price and a closing time.",
    canDo: "understand a short shop announcement",
    register: "Listening. Price and closing time.",
    lines: [
      ["Speaker", "hear", "Heute: ein Kilo Äpfel für einen Euro.", "Today: one kilo of apples for one euro.", "Amount, item, price."],
      ["Speaker", "hear", "Brot gibt es nicht mehr.", "There is no bread left.", "„Nicht mehr“ means none left."],
      ["Speaker", "hear", "Milch steht hinten links.", "Milk is at the back on the left.", "Place in the shop."],
      ["Speaker", "hear", "Die Kasse schließt um achtzehn Uhr.", "The checkout closes at 18:00.", "„Kasse“ is the checkout."],
      ["Speaker", "hear", "Vielen Dank.", "Thank you very much.", "The announcement ends."],
    ],
    checks: [
      [1, "The apples.", "1 euro a kilo.", "1 euro each, any number.", "18 euros.", "„Ein Kilo für einen Euro“."],
      [2, "Bread.", "There is none left.", "It costs 1 euro.", "It is at the back.", "„Nicht mehr“ means sold out."],
      [4, "The checkout closes at.", "18:00", "8:00", "20:00", "„Achtzehn Uhr“ is 18:00."],
    ],
  }),
  scene({
    id: "a1-x-ad",
    title: "An ad for a room",
    deTitle: "Zimmer zu vermieten",
    place: "You read a short ad. In the exam, ads look like this.",
    goal: "Find the size, the rent, and the date.",
    canDo: "read a short rental ad",
    register: "Reading. „Warm“ means heating is included. „Kalt“ means it is not.",
    lines: [
      ["Ad", "hear", "Zimmer zu vermieten.", "Room to rent.", "„Vermieten“ is to rent out."],
      ["Ad", "hear", "Dreiundvierzig Quadratmeter, mit Küche.", "43 square meters, with a kitchen.", "„Quadratmeter“ is the size."],
      ["Ad", "hear", "Miete: vierhundert Euro warm.", "Rent: 400 euros, heating included.", "„Warm“ includes heating."],
      ["Ad", "hear", "Ab dem ersten Mai.", "From the first of May.", "„Ab“ is the start date."],
      ["Ad", "hear", "Telefon: null vier null, drei zwei eins.", "Phone: 040, 321.", "Say a phone number digit by digit. 040 is null, vier, null."],
    ],
    checks: [
      [2, "How big is the room?", "43 square meters.", "400 square meters.", "43 euros.", "„Quadratmeter“ is the size, not the price."],
      [3, "The rent.", "400 euros, heating included.", "400 euros, plus heating.", "43 euros.", "„Warm“ means heating is in the 400."],
      [4, "You can move in.", "From 1 May.", "Only in April.", "From 8:00.", "„Ab dem ersten Mai“."],
    ],
  }),
  scene({
    id: "a1-x-sign",
    title: "Signs",
    deTitle: "Schilder",
    place: "You read signs at a museum door.",
    goal: "Understand what is forbidden and when it is open.",
    canDo: "read simple signs",
    register: "Reading. Signs use few words.",
    lines: [
      ["Sign", "hear", "Rauchen verboten.", "No smoking.", "„Verboten“ means you must not."],
      ["Sign", "hear", "Eingang links. Ausgang rechts.", "Entrance on the left. Exit on the right.", "„Eingang“ in, „Ausgang“ out."],
      ["Sign", "hear", "Heute geöffnet von neun bis achtzehn Uhr.", "Open today from 9 to 18.", "„Von … bis …“ is the span."],
      ["Sign", "hear", "Sonntag geschlossen.", "Closed on Sunday.", "„Geschlossen“ is closed."],
      ["Sign", "hear", "Karten nur an der Kasse.", "Tickets only at the checkout.", "You cannot buy them at the door."],
    ],
    checks: [
      [1, "Smoking.", "You must not smoke.", "You may smoke inside.", "Smoking is only on Sunday.", "„Verboten“ forbids it."],
      [2, "You go in.", "On the left.", "On the right.", "At the checkout only.", "„Eingang links“."],
      [4, "Sunday.", "The museum is closed.", "It opens at 18:00.", "Tickets are free.", "„Geschlossen“."],
    ],
  }),
  scene({
    id: "a1-x-note",
    title: "A note at home",
    deTitle: "Eine Notiz",
    place: "A note is on the table.",
    goal: "See where the person is and when they return.",
    canDo: "read a short personal note",
    register: "Reading. A note has a name at the end.",
    lines: [
      ["Note", "hear", "Hallo Anna.", "Hello Anna.", "The note names you."],
      ["Note", "hear", "Ich bin im Kurs.", "I am at the course.", "Where Paul is now."],
      ["Note", "hear", "Essen steht im Kühlschrank.", "Food is in the fridge.", "„Kühlschrank“ is the fridge."],
      ["Note", "hear", "Ich komme um sieben nach Hause.", "I get home at seven.", "„Nach Hause“ is homeward."],
      ["Note", "hear", "Bis später. Paul.", "See you later. Paul.", "The name at the end is the writer."],
    ],
    checks: [
      [2, "Where is Paul now?", "At the course.", "At home.", "In the fridge.", "„Im Kurs“."],
      [3, "The food is.", "In the fridge.", "At the course.", "At seven.", "„Im Kühlschrank“."],
      [4, "Paul comes home at.", "7:00", "17:00 only if you add ten.", "9:00", "„Um sieben“ is 7:00."],
    ],
  }),
  scene({
    id: "a1-x-mail",
    title: "A short email",
    deTitle: "Eine E-Mail",
    place: "You read Lena’s email.",
    goal: "Find the day, the time, and the place.",
    canDo: "read a short email",
    register: "Reading. Same facts as a listening task: when and where.",
    lines: [
      ["Email", "hear", "Liebe Anna.", "Dear Anna.", "A friendly greeting."],
      ["Email", "hear", "Hast du am Samstag Zeit?", "Do you have time on Saturday?", "The day."],
      ["Email", "hear", "Wir treffen uns um vier im Café.", "We meet at four in the café.", "Time and place in one line."],
      ["Email", "hear", "Kannst du kommen?", "Can you come?", "She wants an answer."],
      ["Email", "hear", "Liebe Grüße, Lena.", "Love, Lena.", "„Liebe Grüße“ closes a friendly email."],
    ],
    checks: [
      [2, "Which day?", "Saturday.", "Sunday.", "At four, every day.", "„Am Samstag“."],
      [3, "When and where?", "At 4:00, in the café.", "At 4:00, at the station.", "On Saturday, no place.", "„Um vier im Café“."],
      [5, "Who wrote it?", "Lena.", "Anna.", "The café.", "The name after the closing is the writer."],
    ],
  }),
  scene({
    id: "a1-x-form",
    title: "Fill in a form",
    deTitle: "Das Formular",
    place: "The exam gives you a short text. You copy five facts into a form.",
    goal: "Find the name, the street, and the date.",
    canDo: "take facts from a text for a form",
    register: "Writing, part 1. Copy what the text says. Do not invent a fact.",
    lines: [
      ["Text", "hear", "Anna Keller möchte einen Deutschkurs.", "Anna Keller wants a German course.", "This line has the name."],
      ["Text", "hear", "Sie wohnt in der Hauptstraße zwölf.", "She lives at 12 Hauptstraße.", "Street and number."],
      ["Text", "hear", "Der Kurs beginnt am dritten Mai.", "The course starts on 3 May.", "The date."],
      ["Text", "hear", "Sie zahlt bar.", "She pays cash.", "„Bar“ is cash. „Mit Karte“ would be by card."],
      ["Text", "hear", "Bitte Name, Adresse und Datum schreiben.", "Please write name, address, and date.", "Those are the form fields."],
    ],
    checks: [
      [1, "The name field.", "Anna Keller.", "Deutschkurs.", "Hauptstraße.", "The person who wants the course."],
      [2, "The address field.", "Hauptstraße 12.", "3 May.", "Cash.", "Street then house number."],
      [3, "The date field.", "3 May.", "12 May.", "May, no day.", "„Am dritten Mai“."],
    ],
  }),
  scene({
    id: "a1-x-letter",
    title: "A short message",
    deTitle: "Eine Mitteilung",
    place: "You write to a tourist office. The exam wants about 30 words: a greeting, three points, and a closing.",
    goal: "Say why you write, ask for one thing, and ask one question.",
    canDo: "write a short formal message",
    register: "Writing, part 2. Greeting and closing are part of the score.",
    lines: [
      ["You", "say", "Sehr geehrte Damen und Herren,", "Dear Sir or Madam,", "Use this for an office you do not know."],
      ["You", "say", "ich möchte im August nach Dresden fahren.", "I would like to travel to Dresden in August.", "Point 1: why you write."],
      ["You", "say", "Bitte schicken Sie mir Informationen zum Kulturprogramm.", "Please send me information about the culture program.", "Point 2: a request. „Mir“ means to me."],
      ["You", "say", "Haben Sie auch Hoteladressen?", "Do you also have hotel addresses?", "Point 3: a question."],
      ["You", "say", "Mit freundlichen Grüßen, Anna Keller.", "Kind regards, Anna Keller.", "The formal closing, then your name."],
    ],
    checks: [
      [1, "The greeting for an office.", "Sehr geehrte Damen und Herren.", "Hallo Leute.", "Tschüs.", "A formal message starts this way."],
      [3, "You ask them to send.", "Information about the culture program.", "A train ticket.", "Your name.", "„Informationen zum Kulturprogramm“."],
      [5, "The closing.", "Mit freundlichen Grüßen, then your name.", "A second question.", "The date of the course only.", "The exam gives a point for a real closing."],
    ],
  }),
  scene({
    id: "a1-x-sorry-note",
    title: "I cannot come",
    deTitle: "Eine Entschuldigung",
    place: "You write a short note to a friend. Three points, then a greeting.",
    goal: "Say you cannot come, give the reason, and offer another day.",
    canDo: "write a short apology",
    register: "Writing. „Liebe Lena“ fits a friend. An office gets „Sehr geehrte Damen und Herren“.",
    lines: [
      ["You", "say", "Liebe Lena,", "Dear Lena,", "Friend, so „Liebe“, not the office greeting."],
      ["You", "say", "leider kann ich am Freitag nicht kommen.", "Unfortunately I cannot come on Friday.", "Point 1."],
      ["You", "say", "Ich muss am Freitag arbeiten.", "I have to work on Friday.", "Point 2: the reason."],
      ["You", "say", "Können wir uns am Samstag um vier treffen?", "Can we meet on Saturday at four?", "Point 3: a new plan."],
      ["You", "say", "Viele Grüße, Anna.", "Best wishes, Anna.", "A friendly closing."],
    ],
    checks: [
      [2, "Friday.", "You cannot come.", "You can come at four.", "You are on holiday.", "„Nicht kommen“."],
      [3, "The reason.", "You have to work.", "You are in Dresden.", "The café is closed.", "„Ich muss arbeiten“."],
      [4, "The new plan.", "Saturday at 4:00.", "Friday at 4:00.", "No new day.", "„Am Samstag um vier“."],
    ],
  }),
  scene({
    id: "a1-x-intro",
    title: "Introduce yourself",
    deTitle: "Sich vorstellen",
    place: "Speaking, part 1. You have about a minute. The card shows name, age, country, languages, hobby.",
    goal: "Say who you are in five short sentences.",
    canDo: "introduce yourself in the exam",
    register: "Speaking, part 1. Then say the same facts about yourself, not only about Anna.",
    lines: [
      ["You", "say", "Guten Tag. Ich heiße Anna Keller.", "Hello. My name is Anna Keller.", "Name first."],
      ["You", "say", "Ich komme aus China und wohne in Hamburg.", "I come from China and live in Hamburg.", "Origin, then the city you live in."],
      ["You", "say", "Ich bin dreißig Jahre alt und ich bin Ingenieurin.", "I am thirty and I am an engineer.", "Age and job."],
      ["You", "say", "Ich spreche Chinesisch und Deutsch.", "I speak Chinese and German.", "Languages."],
      ["You", "say", "Mein Hobby ist Lesen.", "My hobby is reading.", "One hobby is enough."],
    ],
    checks: [
      [2, "Origin and home.", "From China, lives in Hamburg.", "From Hamburg, lives in China.", "The hobby is China.", "„Aus“ is origin. „Wohnen in“ is where you live now."],
      [3, "Age and work.", "30, engineer.", "30, a hobby.", "Engineer, no age.", "Both facts are in the line."],
      [5, "The hobby.", "Reading.", "German.", "Hamburg.", "„Lesen“ is reading."],
    ],
  }),
  scene({
    id: "a1-x-exam-spell",
    title: "Spell it in the exam",
    deTitle: "Buchstabieren",
    place: "After the introduction, the examiner asks you to spell a word and say a number.",
    goal: "Spell a city and say a phone number.",
    canDo: "spell a word and say a number",
    register: "Speaking, part 1. Spell your own city the same way.",
    lines: [
      ["Examiner", "hear", "Können Sie Hamburg bitte buchstabieren?", "Can you please spell Hamburg?", "They name the word."],
      ["You", "say", "H, A, M, B, U, R, G.", "H, A, M, B, U, R, G.", "One letter at a time."],
      ["Examiner", "hear", "Wie ist Ihre Telefonnummer?", "What is your phone number?", "A number of at least two digits."],
      ["You", "say", "Null eins sieben, vier fünf sechs.", "017, 456.", "In groups, „null“ first."],
      ["Examiner", "hear", "Danke. Das war Teil eins.", "Thank you. That was part one.", "Part 1 ends."],
    ],
    checks: [
      [2, "Hamburg.", "H, A, M, B, U, R, G.", "H, A, M, double B.", "The phone number.", "Seven letters, no double letter."],
      [4, "The number starts with.", "017", "456", "040", "Read from the left."],
      [1, "They ask you to.", "Spell Hamburg.", "Pay 17 euros.", "Open the window.", "„Buchstabieren“ is spelling."],
    ],
  }),
  scene({
    id: "a1-x-ask",
    title: "Ask your partner",
    deTitle: "Eine Frage",
    place: "Speaking, part 2. Your card says Essen. You ask, then you answer.",
    goal: "Ask what someone likes and answer the same kind of question.",
    canDo: "ask and answer an everyday question",
    register: "Speaking, part 2. One question, then a full answer.",
    lines: [
      ["You", "say", "Was isst du gern?", "What do you like to eat?", "The card topic is food."],
      ["Partner", "hear", "Ich esse gern Reis. Und du?", "I like rice. And you?", "They answer and ask back."],
      ["You", "say", "Ich esse gern Nudeln.", "I like pasta.", "A full sentence, not one word."],
      ["Partner", "hear", "Möchtest du Wasser oder Tee?", "Would you like water or tea?", "A choice."],
      ["You", "say", "Wasser, bitte.", "Water, please.", "Choose one."],
    ],
    checks: [
      [1, "Your question.", "What do you like to eat?", "Where is the rice?", "How much is the pasta?", "„Was isst du gern?“"],
      [3, "Your answer needs.", "A full sentence.", "Only the word Nudeln, with no verb.", "A platform number.", "Part 2 wants a sentence."],
      [5, "You choose.", "Water.", "Both, and also coffee.", "Pasta again.", "You said Wasser."],
    ],
  }),
  scene({
    id: "a1-x-request",
    title: "Make a request",
    deTitle: "Eine Bitte",
    place: "Speaking, part 3. The card says: Fenster auf.",
    goal: "Turn the card into a polite request.",
    canDo: "ask someone to do something",
    register: "Speaking, part 3. The card is not the sentence. You make the sentence.",
    lines: [
      ["Card", "hear", "Fenster auf.", "Window open.", "Two words on the card."],
      ["You", "say", "Kannst du bitte das Fenster aufmachen?", "Can you please open the window?", "A question, with „bitte“."],
      ["Partner", "hear", "Ja, klar.", "Yes, sure.", "They agree."],
      ["You", "say", "Danke. Es ist sehr warm hier.", "Thanks. It is very warm here.", "A short reason helps."],
      ["Partner", "hear", "Kein Problem.", "No problem.", "Done."],
    ],
    checks: [
      [2, "You turn the card into.", "Can you open the window?", "The window is a noun I point at.", "Fenster auf, with no verb.", "Part 3 needs a request."],
      [2, "„Aufmachen“ here means.", "Open.", "Buy.", "Spell.", "The card said „auf“."],
      [4, "The reason.", "It is warm.", "You want a ticket.", "The window is forbidden.", "„Warm“."],
    ],
  }),
  scene({
    id: "a1-x-sheet",
    title: "The answer sheet",
    deTitle: "Der Antwortbogen",
    place: "Before the written exam, you hear the instructions.",
    goal: "Understand what to mark and where to write.",
    canDo: "follow exam instructions",
    register: "These words are on the paper: Aufgabe, ankreuzen, Beispiel, Antwortbogen.",
    lines: [
      ["Examiner", "hear", "Lesen Sie die Aufgabe.", "Read the task.", "„Aufgabe“ is the task."],
      ["Examiner", "hear", "Kreuzen Sie die richtige Antwort an.", "Mark the right answer.", "„Ankreuzen“ means put a cross."],
      ["Examiner", "hear", "Schreiben Sie auf den Antwortbogen.", "Write on the answer sheet.", "Only the answer sheet is marked."],
      ["Examiner", "hear", "Zuerst kommt ein Beispiel.", "First there is an example.", "„Beispiel“ is the example. You do not score it."],
      ["Examiner", "hear", "Sie haben zwanzig Minuten.", "You have twenty minutes.", "The time for that part."],
    ],
    checks: [
      [2, "„Ankreuzen“.", "Put a cross by the answer.", "Write a long letter.", "Spell your name.", "A cross, not a sentence."],
      [3, "Where do your answers count?", "On the answer sheet.", "In the question booklet only.", "On the card.", "„Antwortbogen“."],
      [4, "The example.", "You look at it first. It is not scored.", "It is worth 20 points.", "It is the speaking test.", "„Beispiel“ shows the task. It is not a scored item."],
    ],
  }),
  scene({
    id: "a1-x-rent",
    title: "The rent",
    deTitle: "Die Miete",
    place: "You ask about a flat.",
    goal: "Understand kalt, warm, and extra costs.",
    canDo: "ask about rent",
    register: "„Kalt“ is rent without heating. „Nebenkosten“ are the extra costs.",
    lines: [
      ["Landlord", "hear", "Die Miete ist fünfhundert Euro kalt.", "The rent is 500 euros, without heating.", "„Kalt“ excludes heating."],
      ["You", "say", "Und die Nebenkosten?", "And the extra costs?", "Heating, water, and similar."],
      ["Landlord", "hear", "Hundert Euro im Monat.", "100 euros a month.", "A second number."],
      ["You", "say", "Also sechshundert Euro warm?", "So 600 euros with heating?", "You add the two numbers."],
      ["Landlord", "hear", "Ja, warm.", "Yes, with heating.", "They confirm the word „warm“."],
    ],
    checks: [
      [1, "500 euros kalt.", "Rent without heating.", "The size of the flat.", "A phone number.", "„Kalt“ leaves heating out."],
      [2, "„Nebenkosten“.", "Extra costs, such as heating.", "The deposit only.", "The house number.", "They are added on top of the cold rent."],
      [4, "600 euros warm.", "Rent plus the extra costs.", "The extra costs alone.", "A cheaper room.", "500 plus 100."],
    ],
  }),
  scene({
    id: "a1-x-move",
    title: "Moving house",
    deTitle: "Umziehen",
    place: "You tell a friend you are moving.",
    goal: "Say when you move and ask for help.",
    canDo: "say you are moving",
    register: "„Umziehen“ splits: ich ziehe um.",
    lines: [
      ["Friend", "hear", "Wann ziehen Sie um?", "When are you moving?", "The prefix „um“ is at the end."],
      ["You", "say", "Am Samstag ziehe ich um.", "I am moving on Saturday.", "Day first is fine. The prefix still ends the sentence."],
      ["Friend", "hear", "In welche Wohnung?", "Into which flat?", "„Welche“ asks which one."],
      ["You", "say", "In eine Wohnung in der Hauptstraße.", "Into a flat on Hauptstraße.", "„In“ plus the street."],
      ["Friend", "hear", "Brauchen Sie Hilfe? Ich komme um zehn.", "Do you need help? I'll come at ten.", "An offer."],
    ],
    checks: [
      [2, "When?", "Saturday.", "At 10:00 only.", "Next year, no day.", "„Am Samstag“."],
      [1, "„Wann ziehen Sie um?“", "When are you moving?", "When do you pay?", "Where is the station?", "„Umziehen“ is moving house."],
      [4, "The new flat is.", "On Hauptstraße.", "At platform 10.", "In China.", "They named the street."],
    ],
  }),
  scene({
    id: "a1-x-pet",
    title: "A pet",
    deTitle: "Tiere",
    place: "The building allows some animals.",
    goal: "Say which animal you have.",
    canDo: "say whether you have a pet",
    register: "„Kein“ for an animal you do not have.",
    lines: [
      ["Neighbor", "hear", "Gibt es Tiere in der Wohnung?", "Are there animals in the flat?", "A house rule question."],
      ["You", "say", "Ja, ich habe eine Katze.", "Yes, I have a cat.", "„Katze“ is feminine: eine."],
      ["Neighbor", "hear", "Hunde sind hier nicht erlaubt.", "Dogs are not allowed here.", "„Erlaubt“ is allowed."],
      ["You", "say", "Ich habe keinen Hund.", "I do not have a dog.", "„Keinen“ because „Hund“ is masculine."],
      ["Neighbor", "hear", "Gut. Die Katze ist kein Problem.", "Good. The cat is no problem.", "The cat may stay."],
    ],
    checks: [
      [2, "You have.", "A cat.", "A dog.", "No animals.", "„Eine Katze“."],
      [3, "Dogs.", "Not allowed here.", "Welcome.", "Only on Sunday.", "„Nicht erlaubt“."],
      [4, "A dog would be.", "Keinen Hund.", "Eine Hund.", "Kein Katze.", "Masculine negative: keinen."],
    ],
  }),
  scene({
    id: "a1-x-luggage",
    title: "Your luggage",
    deTitle: "Das Gepäck",
    place: "You cannot find your suitcase at the station.",
    goal: "Describe the suitcase and where you left it.",
    canDo: "ask about lost luggage",
    register: "„Gepäck“ is luggage. „Koffer“ is a suitcase.",
    lines: [
      ["You", "say", "Wo ist mein Koffer?", "Where is my suitcase?", "One question."],
      ["Staff", "hear", "Ihr Gepäck steht bei der Information.", "Your luggage is at the information desk.", "„Information“ here is the desk."],
      ["You", "say", "Es ist ein schwarzer Koffer.", "It is a black suitcase.", "Color plus object."],
      ["Staff", "hear", "Dieser Koffer hier?", "This suitcase here?", "„Dieser“ points to one nearby."],
      ["You", "say", "Ja, das ist mein Koffer. Danke.", "Yes, that is my suitcase. Thanks.", "You confirm."],
    ],
    checks: [
      [1, "You are looking for.", "Your suitcase.", "A ticket.", "The rent.", "„Koffer“."],
      [2, "It is.", "At the information desk.", "On platform 7.", "In the flat.", "„Bei der Information“."],
      [3, "Which suitcase?", "A black one.", "A white shirt.", "Any bag.", "„Schwarz“."],
    ],
  }),
  scene({
    id: "a1-x-bank",
    title: "At the bank",
    deTitle: "Bei der Bank",
    place: "You want cash from your account.",
    goal: "Say how much you want to withdraw.",
    canDo: "withdraw money",
    register: "„Abheben“ stays together after „möchte“.",
    lines: [
      ["You", "say", "Ich möchte hundert Euro abheben.", "I would like to withdraw 100 euros.", "Amount plus „abheben“."],
      ["Clerk", "hear", "Mit Ihrer Karte, bitte.", "With your card, please.", "The bank card."],
      ["You", "say", "Hier ist die Karte.", "Here is the card.", "You hand it over."],
      ["Clerk", "hear", "Ihr Konto ist in Ordnung.", "Your account is fine.", "„Konto“ is the account."],
      ["You", "say", "Danke. Hundert Euro, bitte.", "Thank you. 100 euros, please.", "You repeat the amount."],
    ],
    checks: [
      [1, "You want to.", "Withdraw 100 euros.", "Open a new flat.", "Send a letter.", "„Abheben“ is taking cash out."],
      [4, "„Konto“.", "Your account.", "The suitcase.", "The platform.", "The account they checked."],
      [2, "They need.", "Your card.", "Your hobby.", "A stamp.", "„Karte“."],
    ],
  }),
  scene({
    id: "a1-x-police",
    title: "At the police",
    deTitle: "Bei der Polizei",
    place: "Your passport is gone. You report it.",
    goal: "Say what you lost and where.",
    canDo: "report a lost passport",
    register: "„Weg“ means it is missing. Say where it was.",
    lines: [
      ["You", "say", "Guten Tag. Mein Pass ist weg.", "Hello. My passport is gone.", "Say the problem in the first line."],
      ["Officer", "hear", "Wo war der Pass?", "Where was the passport?", "„War“ is the past of „sein“."],
      ["You", "say", "Im Bus, Linie fünf.", "On the bus, line 5.", "Place plus line."],
      ["Officer", "hear", "Wie heißen Sie? Wo wohnen Sie?", "What is your name? Where do you live?", "Two facts for the report."],
      ["You", "say", "Anna Keller, Hauptstraße zwölf.", "Anna Keller, 12 Hauptstraße.", "Name and address."],
    ],
    checks: [
      [1, "The problem.", "Your passport is missing.", "You want to rent a room.", "The bus is late.", "„Weg“ means gone."],
      [3, "Where it was.", "Bus line 5.", "At the bank.", "In the fridge.", "„Linie fünf“."],
      [5, "They need your.", "Name and address.", "Hobby and age only.", "Ticket price.", "Both are in your answer."],
    ],
  }),
  scene({
    id: "a1-x-school",
    title: "School",
    deTitle: "Die Schule",
    place: "You ask about a child’s school day.",
    goal: "Understand the start and the break.",
    canDo: "talk about school",
    register: "„Der Unterricht fängt an.“ The prefix is at the end.",
    lines: [
      ["You", "say", "Geht sie zur Schule?", "Does she go to school?", "„Zur Schule gehen“ means she is a pupil."],
      ["Teacher", "hear", "Ja. Der Unterricht fängt um acht an.", "Yes. Lessons start at eight.", "„Anfangen“ splits."],
      ["You", "say", "Wann ist die Pause?", "When is the break?", "„Pause“ is the break."],
      ["Teacher", "hear", "Um zehn Uhr, zwanzig Minuten.", "At ten, for twenty minutes.", "Time and length."],
      ["You", "say", "Lernt sie auch Deutsch?", "Does she learn German too?", "One more subject."],
    ],
    checks: [
      [2, "Lessons start at.", "8:00", "10:00", "20:00", "„Um acht“."],
      [4, "The break.", "10:00, for 20 minutes.", "8:00, all morning.", "A German test only.", "Time plus „zwanzig Minuten“."],
      [1, "„Zur Schule gehen“.", "She is a pupil.", "She teaches the class.", "She is on holiday.", "It means she attends school."],
    ],
  }),
  scene({
    id: "a1-x-holiday",
    title: "Holiday",
    deTitle: "Urlaub",
    place: "A colleague asks about your holiday.",
    goal: "Say when you go and where.",
    canDo: "talk about a holiday",
    register: "„Wohin“ asks the destination. Countries use „nach“.",
    lines: [
      ["Colleague", "hear", "Wann haben Sie Urlaub?", "When are you on holiday?", "„Urlaub“ is holiday from work."],
      ["You", "say", "Im Juli, zwei Wochen.", "In July, two weeks.", "Month and length."],
      ["Colleague", "hear", "Wohin fahren Sie?", "Where are you going?", "„Wohin“ is the destination."],
      ["You", "say", "Ich fahre nach Italien, ans Meer.", "I am going to Italy, to the sea.", "„Nach“ for the country. „Ans Meer“ is to the sea."],
      ["Colleague", "hear", "Schönen Urlaub.", "Have a good holiday.", "A set wish."],
    ],
    checks: [
      [2, "When and how long?", "July, two weeks.", "Two days in June.", "Every weekend.", "„Im Juli, zwei Wochen“."],
      [4, "The trip.", "To Italy, to the sea.", "To Hamburg, to work.", "No trip.", "„Nach Italien, ans Meer“."],
      [3, "„Wohin?“", "Where to?", "When?", "How much?", "Destination, not time."],
    ],
  }),
  scene({
    id: "a1-x-tv",
    title: "Television and radio",
    deTitle: "Fernsehen",
    place: "A friend asks what you watched.",
    goal: "Say you watch television or listen to the radio.",
    canDo: "talk about television and radio",
    register: "„Fernsehen“ splits: ich sehe fern.",
    lines: [
      ["Friend", "hear", "Siehst du gern fern?", "Do you like watching television?", "„Fern“ is the prefix, at the end."],
      ["You", "say", "Manchmal. Ich höre lieber Radio.", "Sometimes. I prefer the radio.", "„Lieber“ is a preference."],
      ["Friend", "hear", "Und gestern?", "And yesterday?", "A follow-up."],
      ["You", "say", "Gestern habe ich einen Film gesehen.", "Yesterday I watched a film.", "Perfect: „habe … gesehen“."],
      ["Friend", "hear", "Im Fernsehen?", "On television?", "They check where."],
    ],
    checks: [
      [2, "You prefer.", "The radio.", "Television, every day.", "A film at the cinema only.", "„Lieber Radio“."],
      [4, "Yesterday.", "You watched a film.", "You listened to the radio only.", "You moved house.", "„Einen Film gesehen“."],
      [1, "„Siehst du fern?“", "Do you watch television?", "Do you see the sea?", "Are you far away?", "„Fernsehen“ is television."],
    ],
  }),
  scene({
    id: "a1-x-internet",
    title: "Internet",
    deTitle: "Internet",
    place: "You need the internet in a café.",
    goal: "Ask for it and say what you will do.",
    canDo: "ask for the internet",
    register: "„Internet“ is the same word. „Eine E-Mail schreiben“ is to write an email.",
    lines: [
      ["You", "say", "Gibt es hier Internet?", "Is there internet here?", "„Gibt es“ asks if it exists."],
      ["Staff", "hear", "Ja. Das Passwort liegt auf dem Tisch.", "Yes. The password is on the table.", "„Passwort“ is the password."],
      ["You", "say", "Danke. Ich schreibe eine E-Mail.", "Thanks. I'll write an email.", "What you will do."],
      ["Staff", "hear", "Der Computer dort ist frei.", "The computer there is free.", "„Frei“ means available."],
      ["You", "say", "Gut, den nehme ich.", "Good, I'll take that one.", "„Den“ because „Computer“ is masculine."],
    ],
    checks: [
      [1, "You ask if.", "There is internet.", "The computer is yours to keep.", "The café closes.", "„Gibt es“."],
      [2, "The password is.", "On the table.", "On the platform.", "In the email already.", "„Auf dem Tisch“."],
      [4, "„Frei“ here means.", "Nobody is using it.", "It costs nothing.", "It is forbidden.", "You may use that computer."],
    ],
  }),
  scene({
    id: "a1-x-plant",
    title: "A plant",
    deTitle: "Eine Pflanze",
    place: "A plant in the flat needs water.",
    goal: "Say what the plant needs.",
    canDo: "talk about a plant",
    register: "„Brauchen“ is to need.",
    lines: [
      ["Neighbor", "hear", "Die Pflanze ist sehr trocken.", "The plant is very dry.", "„Trocken“ is dry."],
      ["You", "say", "Sie braucht Wasser.", "It needs water.", "„Brauchen“ plus the thing."],
      ["Neighbor", "hear", "Steht sie am Fenster?", "Is it by the window?", "Light."],
      ["You", "say", "Ja, aber heute scheint die Sonne nicht.", "Yes, but the sun is not shining today.", "„Scheinen“ for the sun."],
      ["Neighbor", "hear", "Dann nur Wasser, kein Problem.", "Then just water, no problem.", "A small close."],
    ],
    checks: [
      [2, "The plant needs.", "Water.", "A new flat.", "A ticket.", "„Wasser“."],
      [1, "„Trocken“.", "Dry.", "Closed.", "Expensive.", "It has not had water."],
      [4, "Today.", "The sun is not shining.", "It is raining words only.", "The plant is at the station.", "„Die Sonne scheint nicht“."],
    ],
  }),
  scene({
    id: "a1-x-perfekt",
    title: "What you did",
    deTitle: "Was hast du gemacht?",
    place: "A friend asks about yesterday. You answer in the perfect.",
    goal: "Use haben plus the participle at the end.",
    canDo: "say what you did, with haben",
    register: "Ich habe Deutsch gelernt. Ich habe einen Film gesehen. The participle is last.",
    lines: [
      ["Friend", "hear", "Was hast du gestern gemacht?", "What did you do yesterday?", "„Gemacht“ is the participle of „machen“."],
      ["You", "say", "Ich habe Deutsch gelernt.", "I studied German.", "„Habe“ early, „gelernt“ at the end."],
      ["Friend", "hear", "Und den Film?", "And the film?", "A second action."],
      ["You", "say", "Ich habe den Film auch gesehen.", "I also saw the film.", "„Gesehen“ is the participle of „sehen“."],
      ["Friend", "hear", "Ich habe nur geschlafen.", "I only slept.", "„Geschlafen“ from „schlafen“."],
    ],
    checks: [
      [2, "You studied German. The participle is.", "Gelernt, at the end.", "Lernen, in the middle.", "Gelernt, before habe.", "With „haben“, the participle closes the sentence."],
      [4, "The film.", "You saw it.", "You will see it tomorrow.", "You bought the cinema.", "„Gesehen“ is the past of „sehen“."],
      [5, "The friend.", "Only slept.", "Studied German.", "Saw the film too.", "„Geschlafen“."],
    ],
  }),
  scene({
    id: "a1-x-gefahren",
    title: "Where you went",
    deTitle: "Ich bin gefahren",
    place: "Some verbs use sein, not haben, in the perfect.",
    goal: "Use bin plus geblieben or gefahren.",
    canDo: "say where you went, with sein",
    register: "Ich bin geblieben. Ich bin gefahren. Movement and „bleiben“ use „sein“.",
    lines: [
      ["Friend", "hear", "Warst du in der Stadt?", "Were you in town?", "A yes/no question about yesterday."],
      ["You", "say", "Nein. Ich bin zu Hause geblieben.", "No. I stayed home.", "„Bin … geblieben“."],
      ["Friend", "hear", "Nicht mit dem Bus?", "Not by bus?", "They expected a trip."],
      ["You", "say", "Ich bin nicht gefahren.", "I did not go.", "„Nicht“ before the participle."],
      ["Friend", "hear", "Ich bin in die Stadt gefahren.", "I went into town.", "„In die Stadt“ is the direction."],
    ],
    checks: [
      [2, "You stayed home. The verb is.", "Ich bin geblieben.", "Ich habe geblieben.", "Ich bin bleiben.", "„Bleiben“ uses „sein“, and the participle is „geblieben“."],
      [4, "You did not travel.", "Ich bin nicht gefahren.", "Ich habe nicht gefahren.", "Ich fahre gestern.", "„Fahren“ also uses „sein“."],
      [5, "The friend went.", "Into town.", "Home, and stayed.", "To the doctor.", "„In die Stadt gefahren“."],
    ],
  }),
  scene({
    id: "a1-x-war",
    title: "Yesterday",
    deTitle: "Ich war",
    place: "You were ill yesterday. „War“ and „hatte“ are the two past forms the exam expects.",
    goal: "Use ich war and ich hatte.",
    canDo: "say where you were and what you had",
    register: "Ich war beim Arzt. Ich hatte Fieber. Not the perfect this time.",
    lines: [
      ["Colleague", "hear", "Wo waren Sie gestern?", "Where were you yesterday?", "„Waren“ with „Sie“."],
      ["You", "say", "Ich war beim Arzt.", "I was at the doctor's.", "„War“ is the past of „sein“."],
      ["Colleague", "hear", "Waren Sie krank?", "Were you ill?", "A yes/no question."],
      ["You", "say", "Ja. Ich hatte Fieber.", "Yes. I had a fever.", "„Hatte“ is the past of „haben“."],
      ["Colleague", "hear", "Gute Besserung.", "Get well soon.", "A set wish."],
    ],
    checks: [
      [2, "Where you were.", "At the doctor's.", "At the bank.", "On holiday.", "„Beim Arzt“."],
      [4, "„Ich hatte Fieber“ means.", "I had a fever.", "I have a fever next week.", "I was the doctor.", "„Hatte“ is past."],
      [5, "„Gute Besserung“.", "Get well soon.", "See you at eight.", "The rent is warm.", "A wish for someone who is ill."],
    ],
  }),
  scene({
    id: "a1-x-wollen",
    title: "I want",
    deTitle: "Wollen",
    place: "A friend asks what you want. „Wollen“ is direct. In a shop, „möchte“ is more polite.",
    goal: "Use will and wollen.",
    canDo: "say what you want",
    register: "Ich will. Willst du? With strangers, prefer „ich möchte“.",
    lines: [
      ["Friend", "hear", "Willst du einen Kaffee?", "Do you want a coffee?", "„Willst“ is „du“."],
      ["You", "say", "Nein, ich will einen Tee.", "No, I want a tea.", "„Will“ with „ich“."],
      ["Friend", "hear", "Hier oder zum Mitnehmen?", "Here or to take away?", "A choice."],
      ["You", "say", "Ich will hier trinken.", "I want to drink it here.", "„Will“ plus an infinitive at the end."],
      ["Friend", "hear", "Gut.", "Good.", "Settled."],
    ],
    checks: [
      [2, "You want.", "Tea.", "Coffee.", "Nothing to drink.", "You said Tee."],
      [1, "„Willst du?“ is.", "A direct question to a friend.", "The polite shop question.", "A past tense.", "„Wollen“ with „du“. Shops more often use „möchten“."],
      [4, "Where you drink it.", "Here.", "To take away.", "At home tomorrow.", "„Hier“."],
    ],
  }),
  scene({
    id: "a1-x-duerfen",
    title: "Allowed",
    deTitle: "Dürfen",
    place: "A sign and a person tell you what is allowed.",
    goal: "Ask dürfen and understand a ban.",
    canDo: "ask if something is allowed",
    register: "Sie dürfen hier nicht rauchen. Darf ich …?",
    lines: [
      ["Staff", "hear", "Sie dürfen hier nicht rauchen.", "You may not smoke here.", "„Nicht dürfen“ is not allowed."],
      ["You", "say", "Darf ich draußen rauchen?", "May I smoke outside?", "„Darf ich“ asks permission."],
      ["Staff", "hear", "Ja, nur draußen.", "Yes, only outside.", "The limit."],
      ["You", "say", "Darf ich ein Foto machen?", "May I take a photo?", "A second permission."],
      ["Staff", "hear", "Ja, das dürfen Sie.", "Yes, you may.", "„Dürfen“ with „Sie“."],
    ],
    checks: [
      [1, "Smoking here.", "Not allowed.", "Allowed.", "Only on the answer sheet.", "„Dürfen nicht“."],
      [2, "Outside.", "You may smoke there.", "You may not smoke anywhere.", "You must smoke there.", "They said yes, only outside."],
      [5, "A photo.", "You may take one.", "It is forbidden.", "It costs 100 euros.", "„Das dürfen Sie“."],
    ],
  }),
  scene({
    id: "a1-x-sollen",
    title: "What you should do",
    deTitle: "Sollen",
    place: "You are filling in a form and ask what to write.",
    goal: "Use sollen.",
    canDo: "ask what you are supposed to do",
    register: "Was soll ich machen? Sie sollen … schreiben.",
    lines: [
      ["You", "say", "Was soll ich hier schreiben?", "What should I write here?", "„Soll ich“ asks for the instruction."],
      ["Staff", "hear", "Sie sollen Ihren Namen schreiben.", "You should write your name.", "The instruction."],
      ["You", "say", "Und die Adresse?", "And the address?", "The next field."],
      ["Staff", "hear", "Die Adresse sollen Sie auch schreiben.", "You should write the address too.", "„Sollen“ with „Sie“."],
      ["You", "say", "Gut. Name und Adresse.", "Good. Name and address.", "You repeat both."],
    ],
    checks: [
      [1, "„Was soll ich schreiben?“", "What am I supposed to write?", "What did I write yesterday?", "Where shall the office move?", "„Sollen“ asks for the required action."],
      [2, "First field.", "Your name.", "The rent.", "A photo.", "„Namen“."],
      [4, "The address.", "You should write it too.", "You must not write it.", "It is already printed and finished.", "„Auch schreiben“."],
    ],
  }),
  scene({
    id: "a1-x-wuerde",
    title: "I would like",
    deTitle: "Ich würde gern",
    place: "You book a room. „Ich würde gern“ is a polite chunk. You do not build every Konjunktiv form.",
    goal: "Use ich würde gern for a polite wish.",
    canDo: "make a polite wish",
    register: "Learn the whole chunk: ich würde gern …",
    lines: [
      ["You", "say", "Ich würde gern ein Zimmer reservieren.", "I would like to reserve a room.", "The chunk plus the infinitive at the end."],
      ["Staff", "hear", "Für wann?", "For when?", "The date."],
      ["You", "say", "Für Freitag und Samstag.", "For Friday and Saturday.", "Two nights."],
      ["Staff", "hear", "Mit Frühstück?", "With breakfast?", "An extra."],
      ["You", "say", "Ja, ich würde gern mit Frühstück.", "Yes, I would like it with breakfast.", "The same chunk again."],
    ],
    checks: [
      [1, "„Ich würde gern“ is.", "A polite wish.", "A past event.", "A ban.", "Use it to ask for something politely."],
      [3, "The nights.", "Friday and Saturday.", "Only Sunday.", "Two weeks in July.", "Those two days."],
      [5, "Breakfast.", "Yes, you want it.", "No.", "It is forbidden.", "You repeated „würde gern“."],
    ],
  }),
  scene({
    id: "a1-x-dieser",
    title: "This one",
    deTitle: "Dieser",
    place: "You point at one thing in a shop, not the thing beside it.",
    goal: "Use dieser, diese, and dieses.",
    canDo: "point to this one",
    register: "Dieser Tisch. Diese Lampe. Dieses Buch. Same endings as der, die, das.",
    lines: [
      ["You", "say", "Ich nehme diesen Tisch.", "I'll take this table.", "Masculine object: diesen."],
      ["Staff", "hear", "Dieser Tisch am Fenster?", "This table by the window?", "They check which one."],
      ["You", "say", "Ja. Diese Lampe ist zu hell.", "Yes. This lamp is too bright.", "Feminine: diese."],
      ["Staff", "hear", "Und dieses Buch?", "And this book?", "Neuter: dieses."],
      ["You", "say", "Das Buch nehme ich nicht.", "I won't take the book.", "You refuse one item."],
    ],
    checks: [
      [1, "This table, as the thing you take.", "Diesen Tisch.", "Dieser Tisch, as the object.", "Dieses Tisch.", "Masculine object: diesen."],
      [3, "This lamp.", "Diese Lampe.", "Dieser Lampe.", "Dieses Lampe.", "„Lampe“ is feminine."],
      [4, "This book.", "Dieses Buch.", "Diese Buch.", "Diesen Buch.", "„Buch“ is neuter."],
    ],
  }),
  scene({
    id: "a1-x-dich",
    title: "Me and you",
    deTitle: "Mich und dich",
    place: "You did not hear a friend. You ask them to call you.",
    goal: "Use mich and dich.",
    canDo: "use mich and dich",
    register: "After the verb, a person is often mich or dich. Ich verstehe dich. Kannst du mich anrufen?",
    lines: [
      ["You", "say", "Ich verstehe dich nicht.", "I don't understand you.", "„Dich“ is you, informal, as the object."],
      ["Friend", "hear", "Kannst du mich hören?", "Can you hear me?", "„Mich“ is me."],
      ["You", "say", "Ja. Kannst du mich morgen anrufen?", "Yes. Can you call me tomorrow?", "„Anrufen“ stays together after „kannst“."],
      ["Friend", "hear", "Ich rufe dich um acht an.", "I'll call you at eight.", "Here the prefix „an“ is at the end."],
      ["You", "say", "Danke. Bis morgen.", "Thanks. Until tomorrow.", "The plan is set."],
    ],
    checks: [
      [1, "„Dich“ in the first line.", "You, informal.", "Me.", "A formal stranger.", "„Dich“ matches „du“."],
      [3, "You want them to.", "Call you tomorrow.", "Hear the radio.", "Open the window.", "„Mich anrufen“."],
      [4, "The call is at.", "8:00", "18:00", "Tomorrow, no time.", "„Um acht“."],
    ],
  }),
  scene({
    id: "a1-x-mir",
    title: "To me",
    deTitle: "Mir und Ihnen",
    place: "Someone asks how you are and offers help.",
    goal: "Use mir and Ihnen.",
    canDo: "use mir and Ihnen",
    register: "Es geht mir gut. Können Sie mir helfen? „Mir“ and „Ihnen“ are to me and to you.",
    lines: [
      ["Person", "hear", "Wie geht es Ihnen?", "How are you?", "Polite."],
      ["You", "say", "Danke, es geht mir gut.", "Thanks, I'm well.", "„Mir”, not „mich“, with „gehen“."],
      ["Person", "hear", "Kann ich Ihnen helfen?", "Can I help you?", "„Ihnen“ is polite you."],
      ["You", "say", "Ja. Können Sie mir den Weg zeigen?", "Yes. Can you show me the way?", "„Mir“ is to me. „Den Weg“ is the way."],
      ["Person", "hear", "Gern. Geradeaus, dann links.", "Gladly. Straight ahead, then left.", "The help."],
    ],
    checks: [
      [2, "„Es geht mir gut“.", "I am well.", "I understand you.", "Show me the way.", "„Mir“ with „gehen“."],
      [4, "You ask them to.", "Show you the way.", "Call you at eight.", "Spell their name.", "„Den Weg zeigen“."],
      [3, "„Ihnen“ is.", "You, polite.", "Me.", "The way.", "It matches „Sie“."],
    ],
  }),
  scene({
    id: "a1-x-man",
    title: "One can",
    deTitle: "Man, etwas, nichts",
    place: "You ask a general question, then you order nothing.",
    goal: "Use man, etwas, and nichts.",
    canDo: "say one can, something, and nothing",
    register: "Kann man hier …? Ich möchte etwas. Ich brauche nichts.",
    lines: [
      ["You", "say", "Kann man hier Fahrkarten kaufen?", "Can one buy tickets here?", "„Man“ is people in general, not one man."],
      ["Staff", "hear", "Ja, am Automaten.", "Yes, at the machine.", "Where."],
      ["You", "say", "Ich möchte etwas trinken.", "I would like something to drink.", "„Etwas“ is something."],
      ["Staff", "hear", "Wasser oder Tee?", "Water or tea?", "A choice."],
      ["You", "say", "Danke, ich brauche nichts.", "Thanks, I don't need anything.", "„Nichts“ is nothing."],
    ],
    checks: [
      [1, "„Kann man hier …?“", "Can people do this here?", "Can that man buy a ticket?", "Where is the man?", "„Man“ means one, people in general."],
      [3, "„Etwas“.", "Something.", "Nothing.", "A ticket machine.", "You wanted a drink, not a named one yet."],
      [5, "In the end you want.", "Nothing.", "Tea.", "A ticket and water.", "„Nichts“."],
    ],
  }),
  scene({
    id: "a1-x-lieber",
    title: "Rather",
    deTitle: "Lieber",
    place: "The café offers two drinks.",
    goal: "Choose with lieber.",
    canDo: "say which you prefer",
    register: "Möchten Sie lieber Tee oder Kaffee? Lieber Tee.",
    lines: [
      ["Staff", "hear", "Möchten Sie lieber Tee oder Kaffee?", "Would you rather have tea or coffee?", "„Lieber“ asks for the preference."],
      ["You", "say", "Lieber Tee.", "Tea, rather.", "One of the two."],
      ["Staff", "hear", "Mit Milch?", "With milk?", "An extra."],
      ["You", "say", "Nein. Tee ist besser.", "No. Tea is better.", "„Besser“ is better."],
      ["Staff", "hear", "Kommt sofort.", "Coming right away.", "The order is in."],
    ],
    checks: [
      [2, "You prefer.", "Tea.", "Coffee.", "Milk.", "„Lieber Tee“."],
      [1, "„Lieber“ asks.", "Which of the two you prefer.", "The price.", "The time.", "It is a comparison of two options."],
      [4, "„Besser“.", "Better.", "More expensive.", "Later.", "You think tea is the better drink."],
    ],
  }),
  scene({
    id: "a1-x-denn",
    title: "Because, with denn",
    deTitle: "Denn",
    place: "You give a reason. „Denn“ does not send the verb to the end. „Weil“ does.",
    goal: "Give a reason with denn.",
    canDo: "give a reason with denn",
    register: "Ich bleibe hier, denn es ist zu kalt. The verb stays in second place after denn.",
    lines: [
      ["Friend", "hear", "Kommst du mit in den Park?", "Are you coming to the park?", "An invitation."],
      ["You", "say", "Nein, denn es ist zu kalt.", "No, because it is too cold.", "After „denn“, „ist“ is the second idea, not at the end."],
      ["Friend", "hear", "Nur zehn Minuten?", "Only ten minutes?", "They try again."],
      ["You", "say", "Ich bleibe hier, denn ich muss lernen.", "I'll stay here, because I have to study.", "Again: „muss“ is not at the end."],
      ["Friend", "hear", "Dann bis morgen.", "Then until tomorrow.", "They accept it."],
    ],
    checks: [
      [2, "After „denn“, the verb.", "Stays in second place: es ist.", "Goes to the end, as with weil.", "Disappears.", "„Denn es ist zu kalt“, not „denn es zu kalt ist“."],
      [2, "The reason you refuse.", "It is too cold.", "You prefer tea.", "The park is forbidden.", "„Zu kalt“."],
      [4, "The second reason.", "You have to study.", "You are moving house.", "You want breakfast.", "„Ich muss lernen“."],
    ],
  }),
  scene({
    id: "a1-x-minutes",
    title: "Minutes to the hour",
    deTitle: "Fünf Minuten vor",
    place: "A friend names a time that is not a quarter and not half.",
    goal: "Understand minutes before the hour.",
    canDo: "understand minutes before the hour",
    register: "Fünf Minuten vor drei is 2:55. Viertel vor drei is 2:45.",
    lines: [
      ["Friend", "hear", "Wir treffen uns fünf Minuten vor drei.", "We meet at five minutes to three.", "Five minutes before three."],
      ["You", "say", "Um vierzehn Uhr fünfundfünfzig?", "At 14:55?", "You check the 24-hour clock."],
      ["Friend", "hear", "Ja. Nicht Viertel vor drei.", "Yes. Not quarter to three.", "They block the nearby time."],
      ["You", "say", "Also nicht vierzehn Uhr fünfundvierzig.", "So not 14:45.", "Quarter to three is :45."],
      ["Friend", "hear", "Genau. Bis dann.", "Exactly. See you then.", "The time is agreed."],
    ],
    checks: [
      [1, "Fünf Minuten vor drei.", "2:55", "2:45", "3:05", "Five minutes before three."],
      [3, "Viertel vor drei.", "2:45", "2:55", "3:15", "A quarter of an hour before three."],
      [2, "14:55 matches.", "Five minutes to three.", "Quarter to three.", "Half past two.", "„Fünfundfünfzig“ is :55."],
    ],
  }),
  scene({
    id: "a1-x-measures",
    title: "A pound and a liter",
    deTitle: "Pfund und Liter",
    place: "At the market you buy by weight and by liter.",
    goal: "Use Pfund, Liter, and Kilo.",
    canDo: "buy by weight and volume",
    register: "Ein Pfund is 500 grams. Ein Liter is the liquid. Ein Kilo is 1000 grams.",
    lines: [
      ["Seller", "hear", "Ein Kilo oder ein Pfund?", "A kilo or a pound?", "Two weights."],
      ["You", "say", "Ein Pfund Tomaten, bitte.", "A pound of tomatoes, please.", "The smaller amount."],
      ["Seller", "hear", "Und Milch? Ein Liter?", "And milk? One liter?", "A liquid."],
      ["You", "say", "Ja, ein Liter Milch.", "Yes, one liter of milk.", "You accept."],
      ["Seller", "hear", "Tomaten und Milch. Sonst noch etwas?", "Tomatoes and milk. Anything else?", "They repeat the order."],
    ],
    checks: [
      [2, "You buy.", "A pound of tomatoes.", "A kilo of tomatoes.", "A liter of tomatoes.", "„Ein Pfund“."],
      [4, "The milk.", "One liter.", "One pound.", "One kilo.", "„Ein Liter“ is for the milk."],
      [1, "„Pfund“ is.", "About 500 grams, less than a kilo.", "1000 grams.", "A liquid.", "A pound is half a kilo."],
    ],
  }),
];
