import { scene } from "./build.js";

/** A1 grammar in real situations: articles, cases, negation, modals, questions. */
export const grammarScenes = [
  scene({
    id: "a1-articles",
    title: "Der, die, das",
    deTitle: "Der, die, das",
    place: "You name three things on the table.",
    goal: "Use the right article.",
    canDo: "use der, die, and das with common nouns",
    register: "Masculine der, feminine die, neuter das. Learn the word with its article.",
    lines: [
      ["Teacher", "hear", "Was ist das?", "What is that?", "They point at the table."],
      ["You", "say", "Das ist der Tisch.", "That is the table.", "„Tisch“ is masculine: der."],
      ["Teacher", "hear", "Und die Lampe?", "And the lamp?", "„Lampe“ is feminine."],
      ["You", "say", "Die Lampe ist an. Das Buch ist neu.", "The lamp is on. The book is new.", "„Buch“ is neuter: das."],
      ["Teacher", "hear", "Der Tisch, die Lampe, das Buch.", "The table, the lamp, the book.", "Three articles, three genders."],
    ],
    checks: [
      [2, "The table.", "Der Tisch.", "Die Tisch.", "Das Tisch.", "„Tisch“ is masculine."],
      [4, "The book.", "Das Buch.", "Der Buch.", "Die Buch.", "„Buch“ is neuter."],
      [3, "The lamp.", "Die Lampe.", "Der Lampe.", "Das Lampe.", "„Lampe“ is feminine."],
    ],
  }),
  scene({
    id: "a1-ein",
    title: "A and an",
    deTitle: "Ein und eine",
    place: "You ask for one item, not the one already on the counter.",
    goal: "Choose ein or eine.",
    canDo: "use ein and eine",
    register: "Ein for masculine and neuter. Eine for feminine.",
    lines: [
      ["You", "say", "Ich hätte gern ein Wasser.", "I would like a water.", "„Wasser“ is neuter: ein."],
      ["Staff", "hear", "Und eine Suppe?", "And a soup?", "„Suppe“ is feminine: eine."],
      ["You", "say", "Ja, eine Suppe und ein Brot.", "Yes, a soup and a loaf.", "„Brot“ is neuter: ein."],
      ["Staff", "hear", "Ein Wasser, eine Suppe, ein Brot.", "A water, a soup, a loaf.", "They repeat the articles."],
      ["You", "say", "Genau.", "Exactly.", "The order is right."],
    ],
    checks: [
      [1, "A water.", "Ein Wasser.", "Eine Wasser.", "Einen Wasser als Artikel hier.", "„Wasser“ takes „ein“."],
      [3, "A soup.", "Eine Suppe.", "Ein Suppe.", "Das Suppe.", "„Suppe“ is feminine: eine."],
      [3, "A loaf.", "Ein Brot.", "Eine Brot.", "Die Brot.", "„Brot“ is neuter: ein."],
    ],
  }),
  scene({
    id: "a1-acc",
    title: "Ordering with einen",
    deTitle: "Einen Kaffee",
    place: "You order. The article changes because the thing is the object.",
    goal: "Use the accusative for a masculine noun.",
    canDo: "use einen for a masculine object",
    register: "Der Kaffee becomes einen Kaffee after „hätte gern“ or „möchte“.",
    lines: [
      ["Staff", "hear", "Was möchten Sie?", "What would you like?", "The thing you want is the object."],
      ["You", "say", "Ich möchte einen Kaffee.", "I would like a coffee.", "Masculine object: einen."],
      ["Staff", "hear", "Einen Kaffee. Und einen Kuchen?", "A coffee. And a cake?", "„Kuchen“ is also masculine."],
      ["You", "say", "Nein, keinen Kuchen. Eine Limo.", "No, no cake. A lemonade.", "„Keinen“ is the negative for masculine."],
      ["Staff", "hear", "Einen Kaffee und eine Limo.", "A coffee and a lemonade.", "Masculine einen, feminine eine."],
    ],
    checks: [
      [2, "You want a coffee.", "Einen Kaffee.", "Ein Kaffee.", "Eine Kaffee.", "After „möchte“, masculine nouns take „einen“."],
      [4, "You do not want cake.", "Keinen Kuchen.", "Kein Kuchen bleibt der.", "Keine Kuchen.", "Negative masculine is „keinen“."],
      [4, "A lemonade.", "Eine Limo.", "Einen Limo.", "Ein Limo.", "„Limo“ is feminine: eine."],
    ],
  }),
  scene({
    id: "a1-kein",
    title: "Kein",
    deTitle: "Kein",
    place: "The shop does not have what you asked for. Then you say what you do not want.",
    goal: "Negate a noun with kein.",
    canDo: "say you do not have something, using kein",
    register: "Kein, keine, keinen. Use kein with a noun. Use nicht with a verb or adjective.",
    lines: [
      ["You", "say", "Haben Sie Milch?", "Do you have milk?", "A stock question."],
      ["Staff", "hear", "Nein, wir haben keine Milch.", "No, we have no milk.", "„Keine“ with feminine „Milch“."],
      ["You", "say", "Und Brot?", "And bread?", "Neuter."],
      ["Staff", "hear", "Brot ja. Zucker haben wir auch nicht mehr. Keinen Zucker.", "Bread yes. We also have no sugar left. No sugar.", "„Zucker“ is masculine: keinen."],
      ["You", "say", "Dann nur das Brot.", "Then just the bread.", "You buy what they have."],
    ],
    checks: [
      [2, "No milk.", "Keine Milch.", "Nicht Milch.", "Kein Milch.", "„Milch“ is feminine: keine."],
      [4, "No sugar.", "Keinen Zucker.", "Keine Zucker.", "Nicht einen Zuckerwort.", "Masculine negative: keinen."],
      [5, "You still buy bread.", "Dann nur das Brot.", "Dann keine Milch als Brot.", "Brot haben wir nicht, Sie sagen das.", "You chose the item they do have."],
    ],
  }),
  scene({
    id: "a1-nicht",
    title: "Nicht",
    deTitle: "Nicht",
    place: "You correct a small misunderstanding.",
    goal: "Negate a verb or an adjective with nicht.",
    canDo: "use nicht with a verb or an adjective",
    register: "Nicht trinken. Nicht teuer. Nicht heute.",
    lines: [
      ["Friend", "hear", "Trinkst du Kaffee?", "Do you drink coffee?", "A yes/no question."],
      ["You", "say", "Ich trinke Kaffee nicht.", "I don't drink coffee.", "„Nicht“ negates the verb here."],
      ["Friend", "hear", "Ist Tee auch teuer?", "Is tea expensive too?", "An adjective."],
      ["You", "say", "Nein, Tee ist nicht teuer.", "No, tea is not expensive.", "„Nicht“ before the adjective."],
      ["Friend", "hear", "Dann Tee.", "Then tea.", "The choice is made."],
    ],
    checks: [
      [2, "You do not drink coffee.", "Ich trinke Kaffee nicht.", "Ich trinke keinen heute Morgen nur als Artikelfehler.", "Kaffee ist nicht ein Zimmer.", "„Nicht“ negates the drinking."],
      [4, "Tea is not expensive.", "Tee ist nicht teuer.", "Tee ist kein teuer.", "Nicht Tee ist die Milch.", "„Nicht“ before an adjective."],
      [2, "Why nicht, not kein, in „trinke nicht“?", "You negate the verb.", "You negate a feminine noun.", "You need the accusative.", "„Trinken“ is a verb, so „nicht“."],
    ],
  }),
  scene({
    id: "a1-mein",
    title: "My and your",
    deTitle: "Mein und Ihr",
    place: "At a cloakroom you point to your jacket and ask about theirs.",
    goal: "Use mein and Ihr.",
    canDo: "say my and your",
    register: "Mein, meine. Polite your is Ihr, Ihre.",
    lines: [
      ["You", "say", "Das ist meine Jacke.", "That is my jacket.", "„Jacke“ is feminine: meine."],
      ["Staff", "hear", "Und der Schirm?", "And the umbrella?", "„Schirm“ is masculine."],
      ["You", "say", "Das ist nicht mein Schirm.", "That is not my umbrella.", "Masculine: mein."],
      ["Staff", "hear", "Ist das Ihr Schirm?", "Is that your umbrella?", "Polite „Ihr“."],
      ["You", "say", "Nein. Meine Tasche ist blau.", "No. My bag is blue.", "„Tasche“ feminine: meine."],
    ],
    checks: [
      [1, "My jacket.", "Meine Jacke.", "Mein Jacke.", "Ihr Jacke von mir.", "Feminine possession: meine."],
      [3, "Not my umbrella.", "Nicht mein Schirm.", "Nicht meine Schirm.", "Kein Schirm Artikel nur.", "Masculine: mein."],
      [4, "Polite „your“.", "Ihr Schirm.", "Dein Schirm, mit Sie.", "Mein Schirm von Ihnen.", "With „Sie“, your is „Ihr“."],
    ],
  }),
  scene({
    id: "a1-du-sie",
    title: "Du or Sie",
    deTitle: "Du oder Sie",
    place: "You meet a classmate and then the teacher.",
    goal: "Choose du or Sie.",
    canDo: "choose du or Sie",
    register: "Du with friends and classmates. Sie with strangers and teachers.",
    lines: [
      ["Classmate", "hear", "Wie geht's dir?", "How are you?", "„Dir“ belongs to „du“."],
      ["You", "say", "Gut, danke. Und dir?", "Fine, thanks. And you?", "You answer with „du“."],
      ["Teacher", "hear", "Guten Tag. Wie geht es Ihnen?", "Hello. How are you?", "„Ihnen“ belongs to „Sie“."],
      ["You", "say", "Danke, gut. Und Ihnen?", "Thanks, well. And you?", "You switch to „Sie“."],
      ["Teacher", "hear", "Auch gut.", "Well too.", "Both greetings worked."],
    ],
    checks: [
      [2, "Answer a classmate.", "Und dir?", "Und Ihnen, zum Klassenkameraden.", "Und Sie wohnen?", "Classmates use „du“, so „dir“."],
      [4, "Answer a teacher.", "Und Ihnen?", "Und dir, zur Lehrerin.", "Wie heißt du, Frau Berg?", "Teachers get „Sie“, so „Ihnen“."],
      [1, "„Wie geht's dir?“", "Informal.", "A shop sign.", "A police form.", "„Dir“ is the informal you."],
    ],
  }),
  scene({
    id: "a1-pronouns",
    title: "I, you, he, she",
    deTitle: "Ich, du, er, sie",
    place: "You explain who is coming.",
    goal: "Use the subject pronouns.",
    canDo: "use ich, du, er, sie, and wir",
    register: "Er for a man or masculine noun. Sie for a woman. Wir for we.",
    lines: [
      ["Friend", "hear", "Kommt Anna?", "Is Anna coming?", "A yes/no question."],
      ["You", "say", "Ja, sie kommt.", "Yes, she is coming.", "Anna is „sie“."],
      ["Friend", "hear", "Und Paul?", "And Paul?", "A man."],
      ["You", "say", "Er kommt auch. Wir kommen um acht.", "He is coming too. We are coming at eight.", "„Er“ and „wir“."],
      ["Friend", "hear", "Gut, dann sehe ich euch.", "Good, then I'll see you all.", "„Euch“ is you plural. Recognize it."],
    ],
    checks: [
      [2, "Anna is coming.", "Sie kommt.", "Er kommt, Anna.", "Wir kommt.", "A woman is „sie“."],
      [4, "Paul is coming.", "Er kommt auch.", "Sie kommt, Paul.", "Es kommt Paul als Artikel.", "A man is „er“."],
      [4, "You and the others.", "Wir kommen um acht.", "Ich kommen um acht.", "Sie kommen, aber nur ich meine uns falsch.", "„Wir“ is we."],
    ],
  }),
  scene({
    id: "a1-sein",
    title: "Sein",
    deTitle: "Ich bin",
    place: "You fill a short spoken form: name, origin, job.",
    goal: "Use bin, ist, and sind.",
    canDo: "use the verb sein",
    register: "Ich bin. Du bist. Er ist. Wir sind. Sie sind.",
    lines: [
      ["Staff", "hear", "Wer sind Sie?", "Who are you?", "„Sind“ with „Sie“."],
      ["You", "say", "Ich bin Lena Hoffmann.", "I am Lena Hoffmann.", "„Bin“ with „ich“."],
      ["Staff", "hear", "Sind Sie die neue Kollegin?", "Are you the new colleague?", "„Sind“ again."],
      ["You", "say", "Ja, ich bin neu hier.", "Yes, I am new here.", "„Bin“ plus an adjective."],
      ["Staff", "hear", "Ihr Team ist in Raum vier.", "Your team is in room 4.", "„Ist“ for „das Team“."],
    ],
    checks: [
      [2, "I am Lena.", "Ich bin Lena Hoffmann.", "Ich ist Lena.", "Ich sind Lena.", "„Ich“ takes „bin“."],
      [3, "Are you the new colleague? The verb is.", "Sind.", "Bin.", "Bist, mit Sie.", "Polite „Sie“ takes „sind“."],
      [5, "The team is in room 4.", "Ihr Team ist in Raum vier.", "Ihr Team bin in Raum vier.", "Team sind ein Kaffee.", "Singular „Team“ takes „ist“."],
    ],
  }),
  scene({
    id: "a1-haben",
    title: "Haben",
    deTitle: "Ich habe",
    place: "At a counter you say what you have with you.",
    goal: "Use habe, hat, and haben.",
    canDo: "use the verb haben",
    register: "Ich habe. Er hat. Wir haben. You have a ticket, not you are a ticket.",
    lines: [
      ["Staff", "hear", "Haben Sie ein Ticket?", "Do you have a ticket?", "„Haben“ with „Sie“."],
      ["You", "say", "Ja, ich habe ein Ticket.", "Yes, I have a ticket.", "„Habe“ with „ich“."],
      ["Staff", "hear", "Hat Ihre Freundin auch eins?", "Does your friend have one too?", "„Hat“ with „sie“."],
      ["You", "say", "Nein, sie hat keins. Wir haben nur eins.", "No, she has none. We have only one.", "„Hat“ and „haben“."],
      ["Staff", "hear", "Dann braucht sie noch ein Ticket.", "Then she still needs a ticket.", "One ticket is missing."],
    ],
    checks: [
      [2, "I have a ticket.", "Ich habe ein Ticket.", "Ich bin ein Ticket.", "Ich hat ein Ticket.", "Possession uses „haben“, and „ich“ takes „habe“."],
      [4, "She has none.", "Sie hat keins.", "Sie habe keins.", "Sie ist keins.", "„Sie“ takes „hat“."],
      [4, "We have one.", "Wir haben nur eins.", "Wir hat nur eins.", "Wir bin eins.", "„Wir“ takes „haben“."],
    ],
  }),
  scene({
    id: "a1-questions",
    title: "Yes or no",
    deTitle: "Ja oder nein",
    place: "A clerk asks closed questions. The verb comes first.",
    goal: "Answer yes/no questions.",
    canDo: "answer a yes/no question",
    register: "The verb starts the question: „Wohnen Sie hier?“",
    lines: [
      ["Staff", "hear", "Wohnen Sie in Hamburg?", "Do you live in Hamburg?", "Verb first."],
      ["You", "say", "Ja.", "Yes.", "A short answer is correct."],
      ["Staff", "hear", "Arbeiten Sie auch hier?", "Do you also work here?", "A second question."],
      ["You", "say", "Nein, ich arbeite in Berlin.", "No, I work in Berlin.", "„Nein“ plus the fact."],
      ["Staff", "hear", "Alles klar.", "All clear.", "The form moves on."],
    ],
    checks: [
      [1, "„Wohnen Sie in Hamburg?“ The verb is.", "At the start.", "At the end, like English always.", "After the city.", "Yes/no questions start with the verb."],
      [2, "You live there.", "Ja.", "Nein, in München.", "Ich heiße Hamburg.", "You answered yes."],
      [4, "You work in Berlin.", "Nein, ich arbeite in Berlin.", "Ja, ich arbeite in Hamburg.", "Berlin ist meine Uhr.", "You said no, then the city."],
    ],
  }),
  scene({
    id: "a1-wfragen",
    title: "Question words",
    deTitle: "W-Fragen",
    place: "You ask four short questions at a desk.",
    goal: "Use wer, was, wo, and wann.",
    canDo: "ask wer, was, wo, and wann",
    register: "The question word comes first, then the verb.",
    lines: [
      ["You", "say", "Wer ist die Lehrerin?", "Who is the teacher?", "„Wer“ is who."],
      ["Staff", "hear", "Frau Berg.", "Ms Berg.", "A name answers „wer“."],
      ["You", "say", "Wo ist der Raum? Und wann beginnt der Kurs?", "Where is the room? And when does the course start?", "„Wo“ and „wann“."],
      ["Staff", "hear", "Raum zwei, um neun.", "Room 2, at nine.", "Place, then time."],
      ["You", "say", "Was brauche ich?", "What do I need?", "„Was“ is what."],
    ],
    checks: [
      [1, "Ask who the teacher is.", "Wer ist die Lehrerin?", "Wo ist die Lehrerin als Name?", "Was kostet die Lehrerin?", "„Wer“ asks for a person."],
      [3, "Place and start time.", "Wo und wann.", "Wer und was kostet.", "Wie alt ist der Raum?", "„Wo“ is where. „Wann“ is when."],
      [5, "Ask what you need.", "Was brauche ich?", "Wann brauche ich als Ding?", "Wer brauche ich?", "„Was“ asks for a thing."],
    ],
  }),
  scene({
    id: "a1-moechte",
    title: "I would like",
    deTitle: "Ich möchte",
    place: "You order. „Möchten“ is politer than „wollen“.",
    goal: "Use möchte.",
    canDo: "say what you would like",
    register: "Ich möchte. Sie möchten. Not the same as „ich mag“.",
    lines: [
      ["Staff", "hear", "Was möchten Sie trinken?", "What would you like to drink?", "„Möchten“ is the polite want."],
      ["You", "say", "Ich möchte einen Tee.", "I would like a tea.", "„Möchte“ plus the object."],
      ["Staff", "hear", "Möchten Sie auch etwas essen?", "Would you also like something to eat?", "A second offer."],
      ["You", "say", "Nein, danke. Nur den Tee.", "No, thanks. Just the tea.", "You limit the order."],
      ["Staff", "hear", "Kommt sofort.", "Coming right away.", "The order is in."],
    ],
    checks: [
      [2, "You want tea.", "Ich möchte einen Tee.", "Ich mag einen Tee als Bestellung hier falsch.", "Tee möchte ist mein Name.", "Ordering uses „möchte“."],
      [2, "„Möchte“ is closer to.", "I would like.", "I like it as a hobby.", "I am a tea.", "„Möchten“ places a wish now."],
      [4, "Only tea.", "Nur den Tee.", "Auch einen Kuchen.", "Keinen Tee.", "You refused food."],
    ],
  }),
  scene({
    id: "a1-koennen",
    title: "Can",
    deTitle: "Können",
    place: "You ask if you can pay by card, and if someone can help.",
    goal: "Use können.",
    canDo: "say what you can do and ask for help",
    register: "Ich kann. Können Sie …?",
    lines: [
      ["You", "say", "Kann ich mit Karte zahlen?", "Can I pay by card?", "„Kann“ asks permission and possibility."],
      ["Staff", "hear", "Ja, das können Sie.", "Yes, you can.", "„Können“ with „Sie“."],
      ["You", "say", "Können Sie mir helfen? Die Karte geht nicht.", "Can you help me? The card does not work.", "Ask a person for help."],
      ["Staff", "hear", "Ja. Einen Moment.", "Yes. One moment.", "They will help."],
      ["You", "say", "Danke. Allein schaffe ich es nicht.", "Thanks. I can't manage it alone.", "„Nicht“ negates „schaffen“."],
    ],
    checks: [
      [1, "Ask to pay by card.", "Kann ich mit Karte zahlen?", "Mag ich Karte als Hobby?", "Karte ist um drei.", "„Kann ich“ asks if it is possible."],
      [3, "Ask them to help.", "Können Sie mir helfen?", "Können Sie mein Hobby?", "Helfen ist ein Monat.", "„Helfen“ is to help."],
      [2, "„Das können Sie.“", "You are allowed to.", "You must not.", "You are the card.", "„Können“ here means you can."],
    ],
  }),
  scene({
    id: "a1-muessen",
    title: "Must",
    deTitle: "Müssen",
    place: "You explain why you are leaving.",
    goal: "Use müssen.",
    canDo: "say what you have to do",
    register: "Ich muss. Sie müssen. „Nicht müssen“ means do not have to.",
    lines: [
      ["Friend", "hear", "Bleibst du noch?", "Are you staying longer?", "They hoped you would."],
      ["You", "say", "Nein, ich muss gehen.", "No, I have to go.", "„Müssen“ is an obligation."],
      ["Friend", "hear", "Musst du arbeiten?", "Do you have to work?", "A reason."],
      ["You", "say", "Ja. Aber du musst nicht mitkommen.", "Yes. But you don't have to come along.", "„Nicht müssen“ is not the same as „must not“."],
      ["Friend", "hear", "Okay. Bis morgen.", "Okay. Until tomorrow.", "You leave."],
    ],
    checks: [
      [2, "You have to leave.", "Ich muss gehen.", "Ich kann bleiben gern.", "Gehen ist frei.", "„Muss“ is the obligation."],
      [4, "Your friend does not have to come.", "Du musst nicht mitkommen.", "Du musst mitkommen.", "Du darfst nie bleiben als Satz hier.", "„Nicht müssen“ means it is optional."],
      [3, "„Musst du arbeiten?“", "Do you have to work?", "Do you like work?", "Where is work?", "„Müssen“ asks about the obligation."],
    ],
  }),
  scene({
    id: "a1-plural",
    title: "More than one",
    deTitle: "Plural",
    place: "You count things in the flat for a guest.",
    goal: "Use a plural noun with a number.",
    canDo: "use plural nouns with numbers",
    register: "After a number, the noun is plural: zwei Stühle, drei Bücher.",
    lines: [
      ["Guest", "hear", "Wie viele Stühle habt ihr?", "How many chairs do you have?", "„Stühle“ is the plural of „Stuhl“."],
      ["You", "say", "Vier Stühle und einen Tisch.", "Four chairs and one table.", "Plural after four. Singular table."],
      ["Guest", "hear", "Und Bücher?", "And books?", "„Bücher“ is the plural."],
      ["You", "say", "Viele Bücher. Zwei sind neu.", "Lots of books. Two are new.", "„Viele“ needs the plural."],
      ["Guest", "hear", "Schön.", "Nice.", "Enough."],
    ],
    checks: [
      [2, "Four chairs.", "Vier Stühle.", "Vier Stuhl.", "Vier der Stuhl.", "The number above one uses the plural „Stühle“."],
      [4, "Many books.", "Viele Bücher.", "Viel Buch.", "Bücher ist singular hier falsch gesagt.", "„Viele“ plus plural."],
      [2, "One table.", "Einen Tisch.", "Vier Tische, Sie sagen das.", "Tische vier.", "You said one table, accusative „einen Tisch“."],
    ],
  }),
  scene({
    id: "a1-separable",
    title: "Verbs that split",
    deTitle: "Aufstehen",
    place: "You say three things that happen at the start and end of a visit.",
    goal: "Put the prefix at the end.",
    canDo: "use a separable verb in a main clause",
    register: "Ich stehe um sieben auf. Kommen Sie bitte mit. Ich rufe später an.",
    lines: [
      ["Friend", "hear", "Wann stehst du auf?", "When do you get up?", "„Aufstehen“ splits."],
      ["You", "say", "Ich stehe um sieben auf.", "I get up at seven.", "„Auf“ goes to the end."],
      ["Friend", "hear", "Kommst du heute mit?", "Are you coming along today?", "„Mitkommen“."],
      ["You", "say", "Ja. Ich rufe dich an.", "Yes. I'll call you.", "„Anrufen“: rufe … an."],
      ["Friend", "hear", "Gut, bis später.", "Good, see you later.", "The plan is set."],
    ],
    checks: [
      [2, "Get up at seven.", "Ich stehe um sieben auf.", "Ich aufstehe um sieben.", "Auf um sieben stehe.", "The prefix „auf“ is at the end."],
      [4, "You will phone.", "Ich rufe dich an.", "Ich anrufe dich.", "Dich rufe an ich.", "„An“ closes „anrufen“."],
      [3, "„Kommst du mit?“", "Are you coming along?", "Are you standing up?", "Are you calling?", "„Mitkommen“ is to come along."],
    ],
  }),
  scene({
    id: "a1-weil",
    title: "Because",
    deTitle: "Weil",
    place: "You give a reason for being late.",
    goal: "Give a reason with weil.",
    canDo: "give a reason with weil",
    register: "In a weil-clause the verb goes to the end: weil ich arbeite.",
    lines: [
      ["Colleague", "hear", "Warum kommst du später?", "Why are you coming later?", "„Warum“ asks for a reason."],
      ["You", "say", "Weil ich noch arbeite.", "Because I am still working.", "The verb „arbeite“ is at the end."],
      ["Colleague", "hear", "Bis wann?", "Until when?", "They want the new time."],
      ["You", "say", "Bis sieben, weil der Termin lang ist.", "Until seven, because the appointment is long.", "Again the verb is last: „ist“."],
      ["Colleague", "hear", "Okay, um sieben.", "Okay, at seven.", "They accept the reason."],
    ],
    checks: [
      [2, "The reason.", "Weil ich noch arbeite.", "Weil ich arbeite noch.", "Warum ich bin Arbeit.", "With „weil“, the verb closes the clause."],
      [1, "„Warum?“", "Why?", "Where?", "How many?", "„Warum“ asks for a reason."],
      [4, "The appointment is long.", "Weil der Termin lang ist.", "Weil ist der Termin lang.", "Lang weil Termin der.", "„Ist“ stands at the end."],
    ],
  }),
  scene({
    id: "a1-imperative",
    title: "Please do this",
    deTitle: "Bitte",
    place: "You ask a stranger for a small action, politely.",
    goal: "Use a polite request.",
    canDo: "make a polite request",
    register: "„Bitte“ plus the Sie-form: Kommen Sie, Warten Sie, Sprechen Sie langsam.",
    lines: [
      ["You", "say", "Sprechen Sie bitte langsam.", "Please speak slowly.", "Infinitive stem plus „Sie“, then „bitte“."],
      ["Person", "hear", "Natürlich.", "Of course.", "They agree."],
      ["You", "say", "Wiederholen Sie das, bitte.", "Please repeat that.", "Another polite imperative."],
      ["Person", "hear", "Der Bus kommt in fünf Minuten.", "The bus comes in five minutes.", "They repeat the fact."],
      ["You", "say", "Danke. Warten Sie, ich schreibe es.", "Thanks. Wait, I'm writing it down.", "„Warten Sie“ is please wait, with „Sie“."],
    ],
    checks: [
      [1, "Ask them to speak slowly.", "Sprechen Sie bitte langsam.", "Sprichst du bitte, zur fremden Person.", "Langsam sprechen ich.", "The polite request uses „Sie“."],
      [3, "Ask for a repeat.", "Wiederholen Sie das.", "Wiederhole, ohne Sie, zur fremden Person.", "Das ist langsam genug schon.", "„Wiederholen Sie“ is the polite form."],
      [5, "Ask them to wait.", "Warten Sie.", "Warte du, fremde Person.", "Gehen Sie sofort weg als Bitte hier.", "„Warten Sie“ asks them to wait."],
    ],
  }),
  scene({
    id: "a1-esgibt",
    title: "There is",
    deTitle: "Es gibt",
    place: "You ask if a place exists nearby.",
    goal: "Use es gibt.",
    canDo: "ask and say that something exists",
    register: "„Gibt es …?“ „Es gibt …“ The noun is accusative: einen Park, eine Bank.",
    lines: [
      ["You", "say", "Gibt es hier einen Park?", "Is there a park here?", "„Einen“ because it is the object of „gibt“."],
      ["Person", "hear", "Ja, es gibt einen Park neben der Kirche.", "Yes, there is a park next to the church.", "„Es gibt“ plus place."],
      ["You", "say", "Gibt es dort einen Spielplatz?", "Is there a playground there?", "A follow-up."],
      ["Person", "hear", "Nein, einen Spielplatz gibt es nicht.", "No, there isn't a playground.", "„Nicht“ can close this sentence."],
      ["You", "say", "Danke. Dann nur der Park.", "Thanks. Then just the park.", "You have the answer."],
    ],
    checks: [
      [1, "Ask if there is a park.", "Gibt es hier einen Park?", "Ist hier der Park mein?", "Park wohnt es.", "„Gibt es“ asks whether it exists."],
      [2, "There is a park by the church.", "Es gibt einen Park neben der Kirche.", "Es ist einen Park.", "Neben gibt Park.", "„Es gibt“ states that it exists."],
      [4, "No playground.", "Einen Spielplatz gibt es nicht.", "Es gibt einen Spielplatz doch.", "Spielplatz ist offen als Ja.", "They said there is not one."],
    ],
  }),
  scene({
    id: "a1-prepositions",
    title: "In, an, auf",
    deTitle: "Wo?",
    place: "You say where things are in the room.",
    goal: "Use in, an, and auf for a place.",
    canDo: "say where something is",
    register: "In der Tasche. An der Wand. Auf dem Tisch. Place, not movement.",
    lines: [
      ["Guest", "hear", "Wo ist mein Schlüssel?", "Where is my key?", "„Schlüssel“ is the key."],
      ["You", "say", "Auf dem Tisch.", "On the table.", "„Auf“ is on a surface."],
      ["Guest", "hear", "Und die Tasche?", "And the bag?", "Second object."],
      ["You", "say", "Die Tasche ist an der Tür. Das Geld ist in der Tasche.", "The bag is at the door. The money is in the bag.", "„An“ and „in“."],
      ["Guest", "hear", "Danke, ich sehe sie.", "Thanks, I see it.", "Found."],
    ],
    checks: [
      [2, "The key is on the table.", "Auf dem Tisch.", "In dem Tisch als Oberfläche falsch.", "An der Uhr.", "„Auf“ is on top of."],
      [4, "The bag is at the door.", "An der Tür.", "Auf der Tür als Fläche hier nicht.", "In der Tür liegt die Tasche falsch.", "„An“ is at or on a vertical thing."],
      [4, "The money is in the bag.", "In der Tasche.", "Auf der Tasche, Sie sagen das nicht.", "Neben dem Geld.", "„In“ is inside."],
    ],
  }),
  scene({
    id: "a1-hotel",
    title: "At a hotel",
    deTitle: "Im Hotel",
    place: "You arrive at a hotel with a reservation.",
    goal: "Check in with a few sentences.",
    canDo: "check into a hotel",
    register: "A frequent A1 test situation.",
    lines: [
      ["You", "say", "Guten Abend. Ich habe ein Zimmer reserviert.", "Good evening. I have reserved a room.", "Say the reservation first."],
      ["Staff", "hear", "Auf welchen Namen?", "Under what name?", "They look it up."],
      ["You", "say", "Auf den Namen Keller.", "Under the name Keller.", "Family name."],
      ["Staff", "hear", "Ein Einzelzimmer für zwei Nächte.", "A single room for two nights.", "They confirm."],
      ["You", "say", "Ja, genau. Mit Frühstück.", "Yes, exactly. With breakfast.", "„Mit Frühstück“ is with breakfast."],
    ],
    checks: [
      [1, "You have a reservation.", "Ich habe ein Zimmer reserviert.", "Ich suche den Bahnhof.", "Zimmer ist zu teuer, ich gehe.", "You tell them the room is reserved."],
      [3, "The name.", "Auf den Namen Keller.", "Ich heiße Zimmer.", "Keller ist die Nächte.", "They asked which name."],
      [4, "The booking.", "A single room, two nights.", "Two rooms, one night.", "A double room for a week.", "„Einzelzimmer“ for two nights."],
    ],
  }),
  scene({
    id: "a1-appointment",
    title: "Making an appointment",
    deTitle: "Ein Termin",
    place: "You phone a doctor’s office.",
    goal: "Ask for an appointment.",
    canDo: "make a simple appointment",
    register: "„Ich möchte einen Termin.“ Then day and time.",
    lines: [
      ["You", "say", "Ich möchte einen Termin, bitte.", "I would like an appointment, please.", "The purpose of the call."],
      ["Staff", "hear", "Geht es am Donnerstag?", "Is Thursday possible?", "They offer a day."],
      ["You", "say", "Ja. Vormittags oder nachmittags?", "Yes. Morning or afternoon?", "„Vormittags“ is in the morning."],
      ["Staff", "hear", "Um elf Uhr.", "At eleven.", "A time."],
      ["You", "say", "Donnerstag um elf. Danke.", "Thursday at eleven. Thanks.", "Repeat the appointment."],
    ],
    checks: [
      [1, "You want an appointment.", "Ich möchte einen Termin.", "Ich möchte eine Fahrkarte.", "Termin ist das Wetter.", "„Termin“ is the appointment."],
      [3, "Morning or afternoon.", "Vormittags oder nachmittags.", "Montags oder im Juli.", "Halb oder Viertel.", "Those are the two parts of the day."],
      [5, "The agreed time.", "Thursday at 11:00.", "Thursday at 11 euros.", "Friday at 11.", "Day plus „um elf“."],
    ],
  }),
  scene({
    id: "a1-lost",
    title: "Something is missing",
    deTitle: "Ich suche",
    place: "You lost your bag on the bus.",
    goal: "Say what you lost and describe it.",
    canDo: "report a lost item",
    register: "„Ich suche …“ „Er ist schwarz.“",
    lines: [
      ["You", "say", "Ich suche meine Tasche.", "I am looking for my bag.", "„Suchen“ is to look for."],
      ["Staff", "hear", "Wo war sie?", "Where was it?", "„War“ is the past of „sein“, common in this question."],
      ["You", "say", "Im Bus, Linie fünf.", "On the bus, line 5.", "Place plus line."],
      ["Staff", "hear", "Welche Farbe?", "Which color?", "They need a description."],
      ["You", "say", "Sie ist schwarz und klein.", "It is black and small.", "Two adjectives."],
    ],
    checks: [
      [1, "You are looking for your bag.", "Ich suche meine Tasche.", "Ich kaufe eine Tasche neu.", "Tasche ist gefunden schon.", "„Suchen“ means it is missing."],
      [3, "Where it was.", "On bus line 5.", "In the hotel room.", "At the bakery.", "You said the bus, line 5."],
      [5, "What it looks like.", "Black and small.", "Blue and large.", "A white shirt.", "„Schwarz und klein“."],
    ],
  }),
  scene({
    id: "a1-nationality",
    title: "Nationality",
    deTitle: "Nationalität",
    place: "A form asks for nationality, not only the country.",
    goal: "Say your nationality.",
    canDo: "say your nationality",
    register: "„Ich komme aus China“ is the country. „Ich bin Chinesin“ is the nationality.",
    lines: [
      ["Staff", "hear", "Welche Nationalität haben Sie?", "What is your nationality?", "The form uses this noun."],
      ["You", "say", "Ich bin Chinesin.", "I am Chinese.", "The person, not the country. A man says „Chinese“."],
      ["Staff", "hear", "Und Ihr Geburtsort?", "And your place of birth?", "„Geburtsort“ is birthplace."],
      ["You", "say", "Shanghai.", "Shanghai.", "A city is enough."],
      ["Staff", "hear", "Danke. Bitte hier unterschreiben.", "Thanks. Please sign here.", "„Unterschreiben“ is to sign."],
    ],
    checks: [
      [2, "Nationality, as a woman from China.", "Ich bin Chinesin.", "Ich bin China.", "Ich wohne Nationalität.", "The nationality is a word for the person."],
      [3, "„Geburtsort“.", "Place of birth.", "Current job.", "Phone number.", "„Geburt“ is birth. „Ort“ is place."],
      [5, "They want a signature.", "Bitte hier unterschreiben.", "Bitte hier essen.", "Unterschreiben ist die Farbe.", "„Unterschreiben“ is to sign."],
    ],
  }),
  scene({
    id: "a1-form",
    title: "A form",
    deTitle: "Das Formular",
    place: "You do not understand a box on a form.",
    goal: "Ask what to write.",
    canDo: "ask for help with a form",
    register: "Forms are a standard A1 task. Ask one box at a time.",
    lines: [
      ["You", "say", "Was schreibe ich hier?", "What do I write here?", "Point at the box."],
      ["Staff", "hear", "Ihren Namen und Vornamen.", "Your family name and first name.", "„Name“ is the family name. „Vorname“ is the first name."],
      ["You", "say", "Zuerst der Vorname?", "First name first?", "Check the order."],
      ["Staff", "hear", "Nein, zuerst der Familienname.", "No, family name first.", "German forms often want the family name first."],
      ["You", "say", "Keller, Anna. So?", "Keller, Anna. Like this?", "Family name, then first name."],
    ],
    checks: [
      [2, "Name and first name.", "Namen und Vornamen.", "Nur die Uhrzeit.", "Die Farbe der Tasche.", "Those are the two name fields."],
      [4, "Which name comes first on this form?", "The family name.", "The first name.", "The city.", "They said „zuerst der Familienname“."],
      [5, "You wrote Keller, Anna.", "Family name, then first name.", "First name, then city.", "Only the postcode.", "Keller is the family name."],
    ],
  }),
  scene({
    id: "a1-help",
    title: "Asking for help",
    deTitle: "Können Sie mir helfen?",
    place: "You are stuck at a machine in the station.",
    goal: "Ask a stranger for help.",
    canDo: "ask a stranger for help",
    register: "Start with „Entschuldigung“.",
    lines: [
      ["You", "say", "Entschuldigung, können Sie mir helfen?", "Excuse me, can you help me?", "Polite, and specific."],
      ["Person", "hear", "Ja, was ist das Problem?", "Yes, what is the problem?", "They stop."],
      ["You", "say", "Ich verstehe den Automaten nicht.", "I don't understand the machine.", "„Automat“ is the ticket machine."],
      ["Person", "hear", "Drücken Sie hier.", "Press here.", "„Drücken“ is to press."],
      ["You", "say", "Ah, danke. Jetzt geht es.", "Ah, thanks. It works now.", "„Es geht“ means it works."],
    ],
    checks: [
      [1, "Ask for help.", "Können Sie mir helfen?", "Woher kommen Sie?", "Wie alt sind Sie?", "You need an action from them."],
      [3, "The problem is the machine.", "Ich verstehe den Automaten nicht.", "Der Automat ist mein Hobby.", "Ich kaufe den Automaten.", "You do not understand it."],
      [4, "„Drücken Sie hier.“", "Press here.", "Write your name.", "Take the bus home.", "„Drücken“ is to press."],
    ],
  }),
];
