import { scene } from "./build.js";

/** A1 people, contact, numbers, and clock. Goethe-Zertifikat A1: sich vorstellen, Kontaktdaten, Zahlen, Uhrzeit. */
export const peopleScenes = [
  scene({
    id: "a1-hello",
    title: "Saying hello",
    deTitle: "Guten Tag",
    place: "You walk into a shop in the morning.",
    goal: "Greet someone and answer a greeting.",
    canDo: "greet someone in the morning and in the afternoon",
    register: "„Sie“ with people you do not know.",
    lines: [
      ["You", "say", "Guten Morgen.", "Good morning.", "Use this until about midday."],
      ["Staff", "hear", "Guten Morgen. Wie geht es Ihnen?", "Good morning. How are you?", "„Ihnen“ is the polite you."],
      ["You", "say", "Danke, gut. Und Ihnen?", "Thanks, well. And you?", "Answer, then ask back."],
      ["Staff", "hear", "Auch gut, danke.", "Well too, thanks.", "„Auch“ means also."],
      ["You", "say", "Guten Tag.", "Hello.", "After morning, „Guten Tag“ is the normal greeting."],
    ],
    checks: [
      [1, "You enter a shop at 9:00.", "Guten Morgen.", "Gute Nacht.", "Auf Wiedersehen.", "Morning is „Guten Morgen“."],
      [2, "„Wie geht es Ihnen?“", "They ask how you are.", "They ask your name.", "They ask the price.", "„Wie geht es“ asks how someone is."],
      [5, "It is 15:00. You greet someone.", "Guten Tag.", "Guten Morgen.", "Gute Nacht.", "Afternoon uses „Guten Tag“."],
    ],
  }),
  scene({
    id: "a1-bye",
    title: "Saying goodbye",
    deTitle: "Auf Wiedersehen",
    place: "You are leaving a counter.",
    goal: "End the conversation politely.",
    canDo: "say goodbye in a formal situation",
    register: "„Auf Wiedersehen“ is the normal goodbye with „Sie“.",
    lines: [
      ["You", "say", "Danke schön.", "Thank you.", "Say this before you leave."],
      ["Staff", "hear", "Bitte schön.", "You're welcome.", "The answer to „Danke“."],
      ["You", "say", "Auf Wiedersehen.", "Goodbye.", "Use this with strangers and in shops."],
      ["Staff", "hear", "Auf Wiedersehen. Schönen Tag noch.", "Goodbye. Have a nice day.", "„Noch“ means still, for the rest of the day."],
      ["You", "say", "Tschüs.", "Bye.", "„Tschüs“ is friendly. Use it when the other person is informal."],
    ],
    checks: [
      [3, "You leave a shop. Say goodbye politely.", "Auf Wiedersehen.", "Guten Morgen.", "Wie geht es Ihnen?", "„Auf Wiedersehen“ closes a formal conversation."],
      [2, "You said „Danke“. They answer.", "Bitte schön.", "Auf Wiedersehen noch.", "Guten Tag Ihnen.", "„Bitte schön“ answers thanks."],
      [4, "„Schönen Tag noch.“", "Have a nice rest of the day.", "Come back tomorrow morning.", "The shop is closed.", "It is a friendly goodbye, not a time."],
    ],
  }),
  scene({
    id: "a1-name",
    title: "Your name",
    deTitle: "Wie heißen Sie?",
    place: "A course on the first day. The teacher asks the group.",
    goal: "Say your name and ask theirs.",
    canDo: "say your name and ask someone's name",
    register: "„Sie“ in class with a teacher. „du“ comes later.",
    lines: [
      ["Teacher", "hear", "Wie heißen Sie?", "What is your name?", "„Heißen“ is the verb for names."],
      ["You", "say", "Ich heiße Anna Keller.", "My name is Anna Keller.", "„Ich heiße“ plus your name."],
      ["Teacher", "hear", "Freut mich, Frau Keller.", "Pleased to meet you, Ms Keller.", "„Frau“ for a woman, „Herr“ for a man."],
      ["You", "say", "Wie heißen Sie?", "What is your name?", "The same question, now from you."],
      ["Teacher", "hear", "Ich heiße Thomas Berg.", "My name is Thomas Berg.", "He uses „ich heiße“ too."],
    ],
    checks: [
      [2, "Tell them your name is Anna Keller.", "Ich heiße Anna Keller.", "Ich wohne Anna Keller.", "Ich habe Anna.", "„Heißen“ is for names. „Wohnen“ is where you live."],
      [1, "„Wie heißen Sie?“", "What is your name?", "Where do you live?", "How old are you?", "This question asks the name."],
      [3, "They say „Frau Keller“.", "They use the polite form for a woman.", "They think Keller is a city.", "They are asking the price.", "„Frau“ plus the family name is polite."],
    ],
  }),
  scene({
    id: "a1-spell",
    title: "Spelling your name",
    deTitle: "Buchstabieren",
    place: "Someone at a desk writes your name and is not sure.",
    goal: "Spell your family name.",
    canDo: "spell your name letter by letter",
    register: "Say the letters slowly. German letter names are not English.",
    lines: [
      ["Staff", "hear", "Wie schreibt man das?", "How do you spell that?", "They want the letters."],
      ["You", "say", "Keller. K, E, doppel L, E, R.", "Keller. K, E, double L, E, R.", "„Doppel“ marks a double letter."],
      ["Staff", "hear", "Mit Doppel-L?", "With a double L?", "They check one point."],
      ["You", "say", "Ja, genau. K-E-L-L-E-R.", "Yes, exactly. K-E-L-L-E-R.", "„Genau“ means exactly."],
      ["Staff", "hear", "Danke. Ich habe es.", "Thanks. I've got it.", "The name is written."],
    ],
    checks: [
      [2, "The name has two L letters.", "K, E, doppel L, E, R.", "K, E, L, E, R.", "Doppel K, E, L.", "„Doppel L“ means LL."],
      [1, "„Wie schreibt man das?“", "How is it spelled?", "What does it cost?", "Where is it?", "„Schreiben“ here means spelling."],
      [4, "They almost have it. You confirm.", "Ja, genau.", "Nein, morgen.", "Auf Wiedersehen.", "„Genau“ confirms the spelling."],
    ],
  }),
  scene({
    id: "a1-origin",
    title: "Where you are from",
    deTitle: "Woher kommen Sie?",
    place: "A neighbor asks on the stairs.",
    goal: "Say your country and ask theirs.",
    canDo: "say where you come from",
    register: "„Woher“ is from where. „Aus“ plus the country.",
    lines: [
      ["Neighbor", "hear", "Woher kommen Sie?", "Where are you from?", "„Woher“ asks the origin."],
      ["You", "say", "Ich komme aus China.", "I come from China.", "„Aus“ plus the country. Use your own country."],
      ["Neighbor", "hear", "Aus China. Schön.", "From China. Nice.", "They repeat it."],
      ["You", "say", "Und Sie? Woher kommen Sie?", "And you? Where are you from?", "Ask the same question back."],
      ["Neighbor", "hear", "Ich komme aus Deutschland.", "I come from Germany.", "„Deutschland“ is Germany."],
    ],
    checks: [
      [2, "You are from China.", "Ich komme aus China.", "Ich komme nach China.", "Ich wohne China.", "Origin uses „aus“."],
      [1, "„Woher kommen Sie?“", "Where are you from?", "Where are you going?", "What is your name?", "„Woher“ is origin. „Wohin“ would be destination."],
      [5, "They come from Germany.", "Ich komme aus Deutschland.", "Ich komme in Deutschland.", "Deutschland heiße ich.", "Same pattern: „kommen aus“."],
    ],
  }),
  scene({
    id: "a1-city",
    title: "Where you live",
    deTitle: "Wo wohnen Sie?",
    place: "The same neighbor, one question later.",
    goal: "Say the city you live in.",
    canDo: "say where you live",
    register: "„Wohnen“ is to live. „In“ plus the city.",
    lines: [
      ["Neighbor", "hear", "Wo wohnen Sie?", "Where do you live?", "„Wo“ asks the place."],
      ["You", "say", "Ich wohne in Hamburg.", "I live in Hamburg.", "„In“ plus the city."],
      ["Neighbor", "hear", "In Hamburg. Seit wann?", "In Hamburg. Since when?", "„Seit wann“ asks the starting point."],
      ["You", "say", "Seit einem Jahr.", "For a year.", "„Seit“ plus a point or a length in this everyday answer."],
      ["Neighbor", "hear", "Willkommen in Hamburg.", "Welcome to Hamburg.", "A friendly close."],
    ],
    checks: [
      [2, "You live in Hamburg.", "Ich wohne in Hamburg.", "Ich komme aus Hamburg nur.", "Ich heiße Hamburg.", "„Wohnen in“ is where you live now."],
      [3, "„Seit wann?“", "Since when?", "How much is it?", "What is your name?", "„Seit wann“ asks when it started."],
      [4, "You have lived there for a year.", "Seit einem Jahr.", "Um ein Jahr.", "Nach einem Jahr bitte.", "„Seit“ marks how long it has been true."],
    ],
  }),
  scene({
    id: "a1-age",
    title: "How old you are",
    deTitle: "Wie alt sind Sie?",
    place: "A form at the German course. The secretary asks.",
    goal: "Say your age.",
    canDo: "say how old you are",
    register: "„Ich bin … Jahre alt.“ Numbers stay simple.",
    lines: [
      ["Staff", "hear", "Wie alt sind Sie?", "How old are you?", "„Alt“ is old. Here it asks age."],
      ["You", "say", "Ich bin dreißig Jahre alt.", "I am thirty years old.", "„Jahre alt“ is the normal pattern."],
      ["Staff", "hear", "Dreißig. Danke.", "Thirty. Thanks.", "They note the number."],
      ["You", "say", "Und Sie?", "And you?", "Optional, and polite."],
      ["Staff", "hear", "Ich bin zweiundvierzig.", "I am forty-two.", "The ones come before the tens: zwei-und-vierzig."],
    ],
    checks: [
      [2, "You are 30.", "Ich bin dreißig Jahre alt.", "Ich habe dreißig.", "Ich wohne dreißig.", "Age uses „bin … Jahre alt“."],
      [1, "„Wie alt sind Sie?“", "How old are you?", "How tall are you?", "Where are you from?", "„Alt“ in this question is age."],
      [5, "42 in German.", "Zweiundvierzig.", "Vierzigundzwei.", "Zwei vierzig.", "Say the ones, then „und“, then the tens."],
    ],
  }),
  scene({
    id: "a1-job",
    title: "What you do",
    deTitle: "Was sind Sie von Beruf?",
    place: "Someone at a party asks about work.",
    goal: "Name your job, or say you are a student.",
    canDo: "say your job",
    register: "„Von Beruf“ means as a profession.",
    lines: [
      ["Guest", "hear", "Was sind Sie von Beruf?", "What do you do for work?", "The standard question for a job."],
      ["You", "say", "Ich bin Ingenieurin.", "I am an engineer.", "The job name, no „ein“ in this short answer. Use your own job."],
      ["Guest", "hear", "Arbeiten Sie hier?", "Do you work here?", "„Hier“ is here, in this city."],
      ["You", "say", "Ja, bei einer Firma in Hamburg.", "Yes, at a company in Hamburg.", "„Bei“ plus the workplace."],
      ["Guest", "hear", "Interessant.", "Interesting.", "The topic can stop here."],
    ],
    checks: [
      [2, "Say you are an engineer.", "Ich bin Ingenieurin.", "Ich arbeite Ingenieurin.", "Ich heiße Beruf.", "„Ich bin“ plus the job."],
      [1, "„Was sind Sie von Beruf?“", "What is your job?", "Where do you live?", "How old are you?", "„Beruf“ is the profession."],
      [4, "You work at a company.", "Bei einer Firma.", "Aus einer Firma kommen.", "Nach einer Firma heißen.", "„Bei“ marks the employer."],
    ],
  }),
  scene({
    id: "a1-family",
    title: "Your family",
    deTitle: "Meine Familie",
    place: "A classmate asks about your family.",
    goal: "Name the people in your family.",
    canDo: "name family members",
    register: "„Du“ with a classmate.",
    lines: [
      ["Classmate", "hear", "Hast du Geschwister?", "Do you have brothers or sisters?", "„Geschwister“ is siblings."],
      ["You", "say", "Ja, einen Bruder und eine Schwester.", "Yes, one brother and one sister.", "„Einen“ and „eine“ are the accusative after „haben“."],
      ["Classmate", "hear", "Und deine Eltern?", "And your parents?", "„Deine“ because „Eltern“ is plural, and you say „du“."],
      ["You", "say", "Meine Eltern wohnen in China.", "My parents live in China.", "„Meine“ is my, with „Sie“ form it would be different. Here you speak about them."],
      ["Classmate", "hear", "Schöne Familie.", "A nice family.", "A small friendly close."],
    ],
    checks: [
      [2, "You have a brother and a sister.", "Einen Bruder und eine Schwester.", "Ein Bruder wohnt Schwester.", "Geschwister heiße ich.", "After „haben“, a masculine person is „einen“."],
      [1, "„Hast du Geschwister?“", "Do you have siblings?", "Do you have children?", "Where is your flat?", "„Geschwister“ means brothers and sisters."],
      [4, "Your parents live in China.", "Meine Eltern wohnen in China.", "Meine Eltern sind dreißig Euro.", "Eltern kommen nach Uhr.", "„Wohnen“ is where they live."],
    ],
  }),
  scene({
    id: "a1-kids",
    title: "Children",
    deTitle: "Kinder",
    place: "A neighbor asks if you have children.",
    goal: "Say whether you have children, and how many.",
    canDo: "say if you have children",
    register: "„Sie“ with the neighbor.",
    lines: [
      ["Neighbor", "hear", "Haben Sie Kinder?", "Do you have children?", "A yes/no question."],
      ["You", "say", "Ja, eine Tochter.", "Yes, one daughter.", "„Tochter“ is daughter. „Sohn“ is son."],
      ["Neighbor", "hear", "Wie alt ist sie?", "How old is she?", "„Sie“ here is the daughter, not the polite you."],
      ["You", "say", "Sie ist sechs Jahre alt.", "She is six years old.", "Same age pattern as for yourself."],
      ["Neighbor", "hear", "Sechs. Süß.", "Six. Sweet.", "You can smile and stop."],
    ],
    checks: [
      [2, "You have one daughter.", "Ja, eine Tochter.", "Ja, ein Sohn nur Tochter.", "Kinder wohnen sechs.", "„Tochter“ is the daughter."],
      [3, "„Wie alt ist sie?“ about the daughter.", "How old is she?", "Where does she work?", "What is her job?", "„Alt“ asks age."],
      [4, "She is 6.", "Sie ist sechs Jahre alt.", "Sie hat sechs.", "Sechs wohnt sie.", "Age: „ist … Jahre alt“."],
    ],
  }),
  scene({
    id: "a1-languages",
    title: "Languages you speak",
    deTitle: "Sprachen",
    place: "The German course asks what you already speak.",
    goal: "Say which languages you speak.",
    canDo: "say which languages you speak",
    register: "„Sprechen“ is to speak. „Ein bisschen“ is a little.",
    lines: [
      ["Teacher", "hear", "Welche Sprachen sprechen Sie?", "Which languages do you speak?", "„Welche“ means which."],
      ["You", "say", "Ich spreche Chinesisch und ein bisschen Englisch.", "I speak Chinese and a little English.", "Language names are capitalized in German."],
      ["Teacher", "hear", "Und Deutsch?", "And German?", "They mean the course language."],
      ["You", "say", "Ich lerne Deutsch.", "I am learning German.", "„Lernen“ is the honest A1 answer."],
      ["Teacher", "hear", "Sehr gut.", "Very good.", "„Sehr“ makes „gut“ stronger."],
    ],
    checks: [
      [2, "You speak Chinese and a little English.", "Ich spreche Chinesisch und ein bisschen Englisch.", "Ich wohne Chinesisch.", "Englisch ist dreißig.", "„Sprechen“ plus the language."],
      [4, "You are still learning German.", "Ich lerne Deutsch.", "Ich bin Deutsch von Beruf.", "Deutsch wohnt hier.", "„Lernen“ is the verb for studying a language."],
      [1, "„Welche Sprachen sprechen Sie?“", "Which languages do you speak?", "Which city do you like?", "How old is German?", "„Sprachen“ are languages."],
    ],
  }),
  scene({
    id: "a1-meet",
    title: "Nice to meet you",
    deTitle: "Freut mich",
    place: "A friend introduces you to someone.",
    goal: "React when you meet a new person.",
    canDo: "respond when you are introduced",
    register: "„Freut mich“ works with „Sie“ and with „du“.",
    lines: [
      ["Friend", "hear", "Das ist Lena.", "This is Lena.", "„Das ist“ introduces a person."],
      ["You", "say", "Hallo Lena. Freut mich.", "Hello Lena. Nice to meet you.", "Name, then „Freut mich“."],
      ["Lena", "hear", "Mich auch.", "Me too.", "She is pleased too."],
      ["You", "say", "Wohnst du auch hier?", "Do you live here too?", "„Du“ because your friend introduced you informally."],
      ["Lena", "hear", "Ja, in der Nähe.", "Yes, nearby.", "„In der Nähe“ means nearby."],
    ],
    checks: [
      [2, "You just heard her name.", "Freut mich.", "Auf Wiedersehen sofort.", "Wie viel kostet das?", "„Freut mich“ is the meeting phrase."],
      [1, "„Das ist Lena.“", "This is Lena.", "Lena is leaving.", "Lena is the price.", "„Das ist“ introduces someone."],
      [5, "„In der Nähe.“", "Nearby.", "In another country.", "At 9:00.", "„Nähe“ means near."],
    ],
  }),
  scene({
    id: "a1-phone",
    title: "Your phone number",
    deTitle: "Ihre Telefonnummer",
    place: "A desk asks for a number they can call.",
    goal: "Say a phone number in pairs.",
    canDo: "say your phone number",
    register: "Say numbers in groups. „Null“ is zero.",
    lines: [
      ["Staff", "hear", "Ihre Telefonnummer, bitte.", "Your phone number, please.", "„Ihre“ is your, polite."],
      ["You", "say", "Null eins sieben, vier fünf sechs.", "Zero one seven, four five six.", "Start with „null“. Give it in small groups."],
      ["Staff", "hear", "Noch einmal, bitte.", "Once more, please.", "They did not catch it."],
      ["You", "say", "Null, eins, sieben, vier, fünf, sechs.", "Zero, one, seven, four, five, six.", "Slower, one number at a time."],
      ["Staff", "hear", "Danke. Ich rufe Sie an.", "Thanks. I'll call you.", "„Anrufen“ is to call."],
    ],
    checks: [
      [2, "The number starts with 017.", "Null eins sieben.", "Sieben null eins.", "Null ist mein Name.", "Read it from the left, „null“ first."],
      [3, "They missed it.", "Noch einmal, bitte.", "Auf Wiedersehen.", "Wie alt sind Sie?", "„Noch einmal“ asks for a repeat."],
      [5, "„Ich rufe Sie an.“", "They will phone you.", "They will write your name.", "They live nearby.", "„Anrufen“ is a phone call."],
    ],
  }),
  scene({
    id: "a1-email",
    title: "Your email",
    deTitle: "Ihre E-Mail",
    place: "The course office wants an email address.",
    goal: "Dictate an email address.",
    canDo: "say your email address",
    register: "„at“ is „ät“ or „Klammeraffe“. The dot is „Punkt“.",
    lines: [
      ["Staff", "hear", "Wie ist Ihre E-Mail-Adresse?", "What is your email address?", "They will type it."],
      ["You", "say", "Anna Punkt Keller ät Beispiel Punkt de.", "Anna dot Keller at example dot de.", "„Punkt“ is the dot. „ät“ is the at-sign."],
      ["Staff", "hear", "Alles klein?", "All lowercase?", "Email is usually lowercase."],
      ["You", "say", "Ja, alles klein.", "Yes, all lowercase.", "Confirm it."],
      ["Staff", "hear", "Gut, ich schicke Ihnen eine Mail.", "Good, I'll send you an email.", "„Ihnen“ is to you, polite."],
    ],
    checks: [
      [2, "Say anna.keller@example.de.", "Anna Punkt Keller ät Beispiel Punkt de.", "Anna Komma Keller und de.", "Beispiel wohnt Anna.", "Dot is „Punkt“, at is „ät“."],
      [3, "„Alles klein?“", "Are the letters lowercase?", "Is the price small?", "Is the flat small?", "They mean capital letters or not."],
      [5, "They will email you.", "Ich schicke Ihnen eine Mail.", "Ich rufe die Mail an.", "Die Mail ist sechs Jahre.", "„Schicken“ is to send."],
    ],
  }),
  scene({
    id: "a1-address",
    title: "Your address",
    deTitle: "Die Adresse",
    place: "A form needs the street and the number.",
    goal: "Say your street address.",
    canDo: "say your address",
    register: "Street, number, then postcode and city.",
    lines: [
      ["Staff", "hear", "Wie ist Ihre Adresse?", "What is your address?", "Street and number."],
      ["You", "say", "Hauptstraße zwölf.", "12 Hauptstraße.", "The number comes after the street in speech."],
      ["Staff", "hear", "Und die Postleitzahl?", "And the postcode?", "Five digits in Germany."],
      ["You", "say", "Zwei null null neun fünf, Hamburg.", "20095, Hamburg.", "Say a postcode digit by digit, then the city."],
      ["Staff", "hear", "Danke, das reicht.", "Thanks, that's enough.", "The form is complete."],
    ],
    checks: [
      [2, "The street number is 12.", "Hauptstraße zwölf.", "Zwölf Hauptstraße Euro.", "Ich bin Hauptstraße.", "Street then number."],
      [3, "„Die Postleitzahl?“", "The postcode.", "The phone number.", "The age.", "„Postleitzahl“ is the postcode."],
      [4, "The postcode and city.", "20095 Hamburg.", "Twelve Hauptstraße.", "Frau Hamburg.", "The digits are the postcode, then the city."],
    ],
  }),
  scene({
    id: "a1-clock",
    title: "What time it is",
    deTitle: "Wie spät ist es?",
    place: "You ask someone on the street. Your phone is empty.",
    goal: "Ask the time and understand a full hour.",
    canDo: "ask and tell the time on the hour",
    register: "„Wie spät ist es?“ is the normal question.",
    lines: [
      ["You", "say", "Entschuldigung, wie spät ist es?", "Excuse me, what time is it?", "One question is enough."],
      ["Person", "hear", "Es ist drei Uhr.", "It is three o'clock.", "„Uhr“ marks the time."],
      ["You", "say", "Drei Uhr?", "Three o'clock?", "Repeat it if you are unsure."],
      ["Person", "hear", "Ja, genau drei.", "Yes, exactly three.", "„Genau“ confirms."],
      ["You", "say", "Danke.", "Thanks.", "Then you go."],
    ],
    checks: [
      [1, "Ask the time.", "Wie spät ist es?", "Wie heißen Sie?", "Wo wohnen Sie?", "„Wie spät“ asks the time."],
      [2, "„Es ist drei Uhr.“", "It is 3:00.", "It costs 3 euros.", "The bus is number 3.", "„Uhr“ is the clock time."],
      [4, "They confirm.", "Genau drei.", "Halb drei.", "Viertel nach vier.", "„Genau drei“ is 3:00, not half past."],
    ],
  }),
  scene({
    id: "a1-half",
    title: "Half past",
    deTitle: "Halb drei",
    place: "A friend tells you when to meet.",
    goal: "Understand „halb“.",
    canDo: "understand half hours",
    register: "„Halb drei“ is 2:30, half an hour before three.",
    lines: [
      ["Friend", "hear", "Wir treffen uns um halb drei.", "We meet at half past two.", "„Um“ plus the time."],
      ["You", "say", "Halb drei ist vierzehn Uhr dreißig?", "Half past two is 14:30?", "Check it in the 24-hour clock."],
      ["Friend", "hear", "Ja. Nicht fünfzehn Uhr.", "Yes. Not 3 p.m.", "They stop the common mistake."],
      ["You", "say", "Okay, um halb drei.", "Okay, at 2:30.", "Repeat the meeting time."],
      ["Friend", "hear", "Bis dann.", "See you then.", "„Bis dann“ ends the plan."],
    ],
    checks: [
      [1, "„Um halb drei.“ What time is that?", "14:30", "15:30", "15:00", "Halb drei is thirty minutes before three."],
      [3, "They say it is not 15:00.", "The meeting is earlier than 3:00.", "The meeting is at 3:30.", "The shop closes for three days.", "They reject 15:00."],
      [5, "„Bis dann.“", "See you then.", "What time is it?", "Where do you live?", "It closes the plan."],
    ],
  }),
  scene({
    id: "a1-quarter",
    title: "Quarter past and quarter to",
    deTitle: "Viertel nach",
    place: "The train board and a friend do not match. You check.",
    goal: "Understand quarter hours.",
    canDo: "understand quarter past and quarter to",
    register: "„Viertel nach zwei“ is 2:15. „Viertel vor drei“ is 2:45.",
    lines: [
      ["Friend", "hear", "Der Zug fährt um Viertel nach zwei.", "The train leaves at quarter past two.", "„Viertel nach“ is :15."],
      ["You", "say", "Um vierzehn Uhr fünfzehn?", "At 14:15?", "Confirm the 24-hour time."],
      ["Friend", "hear", "Ja. Viertel vor drei ist später.", "Yes. Quarter to three is later.", "„Viertel vor“ is :45 of the previous hour."],
      ["You", "say", "Also nicht Viertel vor drei.", "So not quarter to three.", "You mark the wrong time."],
      ["Friend", "hear", "Richtig.", "Correct.", "You have it."],
    ],
    checks: [
      [1, "„Viertel nach zwei.“", "2:15", "2:45", "3:15", "„Nach“ is past the hour, fifteen minutes."],
      [3, "„Viertel vor drei.“", "2:45", "3:15", "3:45", "„Vor drei“ is before three, so 2:45."],
      [2, "You say 14:15.", "That is quarter past two.", "That is half past two.", "That is three o'clock.", "14:15 matches „Viertel nach zwei“."],
    ],
  }),
  scene({
    id: "a1-days",
    title: "Days of the week",
    deTitle: "Die Wochentage",
    place: "You want a course day. The office lists them.",
    goal: "Name the day you can come.",
    canDo: "name days of the week",
    register: "Days are capitalized. „Am“ plus the day.",
    lines: [
      ["Staff", "hear", "Welcher Tag passt?", "Which day works?", "„Welcher“ because „Tag“ is masculine."],
      ["You", "say", "Am Montag oder am Dienstag.", "On Monday or on Tuesday.", "„Am“ before the day."],
      ["Staff", "hear", "Mittwoch ist auch frei.", "Wednesday is free too.", "A third option."],
      ["You", "say", "Dann am Mittwoch.", "Then on Wednesday.", "You choose."],
      ["Staff", "hear", "Mittwoch um zehn Uhr.", "Wednesday at ten.", "Day plus time."],
    ],
    checks: [
      [2, "Monday or Tuesday.", "Am Montag oder am Dienstag.", "Am Morgen oder am Abend.", "Halb Montag.", "Those are two weekdays."],
      [4, "You choose Wednesday.", "Dann am Mittwoch.", "Dann am Sonntag Nacht nur.", "Mittwoch ist eine Stadt.", "„Mittwoch“ is Wednesday."],
      [5, "The appointment.", "Wednesday at 10:00.", "Monday at 2:30.", "Every day at 10.", "They named Mittwoch and zehn Uhr."],
    ],
  }),
  scene({
    id: "a1-today",
    title: "Today, tomorrow, yesterday",
    deTitle: "Heute und morgen",
    place: "You cannot come today. You offer tomorrow.",
    goal: "Use heute, morgen, and gestern.",
    canDo: "talk about today, tomorrow, and yesterday",
    register: "These three words cover most A1 plans.",
    lines: [
      ["Staff", "hear", "Können Sie heute kommen?", "Can you come today?", "„Heute“ is today."],
      ["You", "say", "Heute nicht. Morgen ja.", "Not today. Tomorrow, yes.", "Two short answers."],
      ["Staff", "hear", "Morgen um neun?", "Tomorrow at nine?", "They offer a time."],
      ["You", "say", "Ja. Gestern hatte ich keine Zeit.", "Yes. Yesterday I had no time.", "„Gestern“ is yesterday. „Hatte“ is the past of „haben“, common even at A1."],
      ["Staff", "hear", "Kein Problem.", "No problem.", "Tomorrow is agreed."],
    ],
    checks: [
      [2, "You can come tomorrow, not today.", "Heute nicht. Morgen ja.", "Gestern ja. Morgen nein immer.", "Heute um halb nie.", "„Heute“ and „morgen“ are the pair."],
      [1, "„Können Sie heute kommen?“", "Can you come today?", "Did you come last year?", "Where is today?", "„Heute“ is today. „Können“ is can."],
      [4, "„Gestern“.", "Yesterday.", "Tomorrow.", "Next week.", "„Gestern“ is the day before today."],
    ],
  }),
  scene({
    id: "a1-date",
    title: "The date",
    deTitle: "Der wievielte?",
    place: "A form asks for today's date.",
    goal: "Say the date with an ordinal.",
    canDo: "say today's date",
    register: "„Der erste“, „der zweite“, „der dritte“, then „-te“.",
    lines: [
      ["Staff", "hear", "Welches Datum haben wir heute?", "What is the date today?", "„Datum“ is the date."],
      ["You", "say", "Heute ist der sechste September.", "Today is the sixth of September.", "Ordinal plus month. „Der sechste“."],
      ["Staff", "hear", "Der sechste. Und das Jahr?", "The sixth. And the year?", "They want the year too."],
      ["You", "say", "Zweitausendsechsundzwanzig.", "2026.", "Say the year as one number."],
      ["Staff", "hear", "Danke.", "Thanks.", "Done."],
    ],
    checks: [
      [2, "The 6th of September.", "Der sechste September.", "Der sechs September Uhr.", "September ist sechs Jahre.", "The date uses the ordinal „sechste“."],
      [1, "„Welches Datum?“", "What date?", "What time?", "What price?", "„Datum“ is the calendar date."],
      [4, "The year 2026.", "Zweitausendsechsundzwanzig.", "Der sechsundzwanzigste nur.", "Zwanzig Uhr sechs.", "That is the year, not a clock time."],
    ],
  }),
  scene({
    id: "a1-months",
    title: "Months",
    deTitle: "Die Monate",
    place: "You book a trip and name the month.",
    goal: "Say a month.",
    canDo: "name months",
    register: "Months are capitalized. „Im“ plus the month.",
    lines: [
      ["Staff", "hear", "In welchem Monat?", "In which month?", "„Welchem“ because of „in“ plus month, but you mostly hear „welchem Monat“."],
      ["You", "say", "Im Juli, bitte.", "In July, please.", "„Im“ is in plus dem."],
      ["Staff", "hear", "Juli ist voll. August auch?", "July is full. August too?", "They offer the next month."],
      ["You", "say", "Ja, im August.", "Yes, in August.", "You accept."],
      ["Staff", "hear", "Vom ersten bis zum zehnten August.", "From the first to the tenth of August.", "A range of dates."],
    ],
    checks: [
      [2, "You want July.", "Im Juli.", "Am Juli Uhr.", "Juli heiße ich.", "„Im“ plus the month."],
      [4, "You switch to August.", "Im August.", "Im Montag.", "Halb August.", "„August“ is the month."],
      [5, "From the 1st to the 10th.", "Vom ersten bis zum zehnten.", "Um eins bis zehn Uhr nur.", "Zehn Jahre im August.", "„Vom … bis zum“ is the date range."],
    ],
  }),
  scene({
    id: "a1-open",
    title: "Opening hours",
    deTitle: "Öffnungszeiten",
    place: "You are outside a shop and read the sign, then ask.",
    goal: "Ask when a place opens and closes.",
    canDo: "ask about opening hours",
    register: "„Von … bis …“ is the pattern on signs.",
    lines: [
      ["You", "say", "Wann haben Sie geöffnet?", "When are you open?", "„Geöffnet“ means open for business."],
      ["Staff", "hear", "Von neun bis achtzehn Uhr.", "From 9 to 18.", "„Von … bis …“ is from … to …."],
      ["You", "say", "Auch am Samstag?", "On Saturday too?", "A useful follow-up."],
      ["Staff", "hear", "Samstag von zehn bis vierzehn Uhr. Sonntag zu.", "Saturday from 10 to 14. Sunday closed.", "„Zu“ here means closed."],
      ["You", "say", "Danke für die Info.", "Thanks for the information.", "You can leave."],
    ],
    checks: [
      [1, "Ask when they are open.", "Wann haben Sie geöffnet?", "Wo wohnen Sie?", "Wie heißen Sie?", "„Geöffnet“ is open."],
      [2, "„Von neun bis achtzehn Uhr.“", "From 9:00 to 18:00.", "At 9:00 only.", "Nine euros to eighteen euros.", "„Von … bis“ is a span of time."],
      [4, "Sunday.", "The shop is closed.", "The shop opens at 14:00.", "Sunday is the best day.", "„Zu“ on a shop sign means closed."],
    ],
  }),
  scene({
    id: "a1-numbers",
    title: "Numbers in a shop",
    deTitle: "Zahlen",
    place: "You buy several of the same thing.",
    goal: "Use numbers from 1 to 20 for a quantity.",
    canDo: "use numbers for quantities",
    register: "The number comes before the thing.",
    lines: [
      ["Staff", "hear", "Wie viele möchten Sie?", "How many would you like?", "„Wie viele“ asks the quantity."],
      ["You", "say", "Vier, bitte.", "Four, please.", "A number is a full answer."],
      ["Staff", "hear", "Vier Stück. Sonst noch etwas?", "Four. Anything else?", "„Stück“ is pieces, items."],
      ["You", "say", "Nein, danke. Das ist alles.", "No, thanks. That's all.", "„Das ist alles“ stops the order."],
      ["Staff", "hear", "Das macht zwölf Euro.", "That comes to twelve euros.", "„Zwölf“ is 12."],
    ],
    checks: [
      [2, "You want four.", "Vier, bitte.", "Vierzig Uhr.", "Vier wohne ich.", "The number answers „wie viele“."],
      [1, "„Wie viele?“", "How many?", "How are you?", "What time?", "„Viele“ asks a quantity."],
      [5, "„Zwölf Euro.“", "12 euros.", "20 euros.", "2 euros.", "„Zwölf“ is twelve."],
    ],
  }),
  scene({
    id: "a1-hundred",
    title: "Larger numbers",
    deTitle: "Hundert",
    place: "You say a price and a house number that are bigger than 20.",
    goal: "Understand tens and a hundred.",
    canDo: "understand numbers up to 100",
    register: "21 is „einundzwanzig“. 100 is „(ein)hundert“.",
    lines: [
      ["Staff", "hear", "Die Nummer ist einundzwanzig.", "The number is 21.", "Ones before tens."],
      ["You", "say", "Einundzwanzig, nicht zwölf.", "21, not 12.", "You distinguish them."],
      ["Staff", "hear", "Und der Preis ist fünfzig Euro.", "And the price is 50 euros.", "„Fünfzig“ is 50."],
      ["You", "say", "Fünfzig. Haben Sie auch etwas für dreißig?", "Fifty. Do you also have something for 30?", "„Dreißig“ is 30."],
      ["Staff", "hear", "Nein, erst ab fünfzig.", "No, only from 50 up.", "„Ab“ means starting from."],
    ],
    checks: [
      [1, "„Einundzwanzig.“", "21", "12", "20", "The one comes first in the German word."],
      [3, "„Fünfzig Euro.“", "50 euros.", "15 euros.", "5 euros.", "„-zig“ marks the tens. Fünfzig is 50."],
      [4, "You ask about 30.", "Dreißig.", "Dreizehn.", "Drei Uhr.", "„Dreißig“ is 30. „Dreizehn“ is 13."],
    ],
  }),
];
