import { scene } from "./build.js";

/** A1 town, shopping, transport, and plans. */
export const townScenes = [
  scene({
    id: "a1-where",
    title: "Where is it?",
    deTitle: "Wo ist …?",
    place: "You are looking for the station.",
    goal: "Ask where a place is.",
    canDo: "ask where a place is",
    register: "„Wo ist“ plus the place. „Entschuldigung“ first.",
    lines: [
      ["You", "say", "Entschuldigung, wo ist der Bahnhof?", "Excuse me, where is the station?", "„Bahnhof“ is the station."],
      ["Person", "hear", "Der Bahnhof ist geradeaus.", "The station is straight ahead.", "„Geradeaus“ is straight on."],
      ["You", "say", "Geradeaus. Ist es weit?", "Straight ahead. Is it far?", "„Weit“ is far."],
      ["Person", "hear", "Nein, fünf Minuten zu Fuß.", "No, five minutes on foot.", "„Zu Fuß“ is on foot."],
      ["You", "say", "Danke schön.", "Thank you.", "Then you walk."],
    ],
    checks: [
      [1, "Ask for the station.", "Wo ist der Bahnhof?", "Wie spät ist der Bahnhof?", "Der Bahnhof heiße ich.", "„Wo ist“ asks the place."],
      [2, "„Geradeaus.“", "Straight ahead.", "Turn around and go home.", "It is closed.", "„Geradeaus“ means straight on."],
      [4, "Five minutes on foot.", "Fünf Minuten zu Fuß.", "Fünf Euro zu Fuß.", "Fünf Zimmer.", "„Zu Fuß“ is walking."],
    ],
  }),
  scene({
    id: "a1-left",
    title: "Left and right",
    deTitle: "Links und rechts",
    place: "Someone gives you a short direction.",
    goal: "Follow left, right, and straight.",
    canDo: "follow simple directions",
    register: "„Links“, „rechts“, „geradeaus“, „dann“.",
    lines: [
      ["Person", "hear", "Gehen Sie links.", "Go left.", "First turn."],
      ["You", "say", "Links, und dann?", "Left, and then?", "Ask for the next step."],
      ["Person", "hear", "Dann rechts bis zur Ampel.", "Then right as far as the traffic light.", "„Ampel“ is the traffic light."],
      ["You", "say", "Rechts bis zur Ampel.", "Right as far as the traffic light.", "Repeat it."],
      ["Person", "hear", "Ja. Die Apotheke ist dort.", "Yes. The pharmacy is there.", "„Dort“ is there."],
    ],
    checks: [
      [1, "The first direction.", "Go left.", "Go straight for five stations.", "Pay eight euros.", "„Links“ is left."],
      [3, "Then right, to the traffic light.", "Dann rechts bis zur Ampel.", "Dann links ins Bett.", "Ampel ist ein Getränk.", "„Rechts“ is right. „Ampel“ is the traffic light."],
      [5, "The pharmacy is there.", "Dort.", "Zu Hause.", "Im Juli.", "„Dort“ points to the place."],
    ],
  }),
  scene({
    id: "a1-bus",
    title: "Which bus",
    deTitle: "Welcher Bus?",
    place: "You need a bus to the center.",
    goal: "Ask which bus to take.",
    canDo: "ask which bus to take",
    register: "„Der Bus“, „die Linie“, „einsteigen“.",
    lines: [
      ["You", "say", "Welcher Bus fährt ins Zentrum?", "Which bus goes to the center?", "„Zentrum“ is the city center."],
      ["Person", "hear", "Die Linie fünf.", "Line 5.", "Bus lines use „Linie“."],
      ["You", "say", "Wo steige ich ein?", "Where do I get on?", "„Einsteigen“ is to board."],
      ["Person", "hear", "Hier, an der Haltestelle.", "Here, at the stop.", "„Haltestelle“ is the stop."],
      ["You", "say", "Danke. Linie fünf.", "Thanks. Line 5.", "You have the number."],
    ],
    checks: [
      [1, "You want the center.", "Welcher Bus fährt ins Zentrum?", "Welcher Bus ist krank?", "Zentrum ist mein Name.", "„Zentrum“ is the destination."],
      [2, "Line 5.", "Die Linie fünf.", "Der Bus fünfzig Euro.", "Fünf Minuten im Bus nur als Preis.", "„Linie“ plus the number."],
      [4, "Where you get on.", "An der Haltestelle.", "In der Apotheke.", "Im Schlafzimmer.", "„Haltestelle“ is the bus stop."],
    ],
  }),
  scene({
    id: "a1-ticket",
    title: "A ticket",
    deTitle: "Eine Fahrkarte",
    place: "You buy a ticket before the train.",
    goal: "Buy a single ticket.",
    canDo: "buy a ticket",
    register: "„Eine Fahrkarte“, „einfach“, „hin und zurück“.",
    lines: [
      ["You", "say", "Eine Fahrkarte nach Berlin, bitte.", "A ticket to Berlin, please.", "„Nach“ plus the city."],
      ["Staff", "hear", "Einfach oder hin und zurück?", "Single or return?", "Two ticket types."],
      ["You", "say", "Einfach.", "Single.", "One way."],
      ["Staff", "hear", "Zweite Klasse. Neunundvierzig Euro.", "Second class. 49 euros.", "Class plus price."],
      ["You", "say", "Ja. Mit Karte.", "Yes. By card.", "You pay."],
    ],
    checks: [
      [1, "A ticket to Berlin.", "Eine Fahrkarte nach Berlin.", "Eine Fahrkarte um Berlin Uhr.", "Berlin ist die Größe.", "„Nach“ marks the destination."],
      [3, "One way.", "Einfach.", "Hin und zurück.", "Zusammen mit der Gruppe.", "„Einfach“ is a single."],
      [4, "The price.", "49 euros, second class.", "49 minutes.", "Nine euros.", "„Neunundvierzig“ is 49."],
    ],
  }),
  scene({
    id: "a1-platform",
    title: "The platform",
    deTitle: "Das Gleis",
    place: "You are in the station with a ticket.",
    goal: "Find the platform.",
    canDo: "ask for the platform",
    register: "„Gleis“ is the platform. „Abfahrt“ is departure.",
    lines: [
      ["You", "say", "Von welchem Gleis fährt der Zug?", "Which platform does the train leave from?", "„Von welchem Gleis“."],
      ["Staff", "hear", "Gleis drei.", "Platform 3.", "A short answer."],
      ["You", "say", "Um wie viel Uhr?", "At what time?", "Ask the departure."],
      ["Staff", "hear", "Abfahrt um zehn Uhr fünfzehn.", "Departure at 10:15.", "„Abfahrt“ is departure."],
      ["You", "say", "Gleis drei, zehn Uhr fünfzehn.", "Platform 3, 10:15.", "Repeat both facts."],
    ],
    checks: [
      [2, "Platform 3.", "Gleis drei.", "Linie drei.", "Drei Kilo.", "„Gleis“ is the platform."],
      [4, "Departure 10:15.", "Abfahrt um zehn Uhr fünfzehn.", "Ankunft gestern.", "Zehn Euro fünfzehn.", "„Abfahrt“ is when it leaves."],
      [1, "„Von welchem Gleis?“", "Which platform?", "Which size?", "Which month?", "„Gleis“ is the train platform."],
    ],
  }),
  scene({
    id: "a1-taxi",
    title: "A taxi",
    deTitle: "Ein Taxi",
    place: "You need a taxi to your street.",
    goal: "Say the destination.",
    canDo: "tell a taxi where to go",
    register: "„Zum Bahnhof“, „in die Hauptstraße“.",
    lines: [
      ["You", "say", "Zum Bahnhof, bitte.", "To the station, please.", "„Zum“ is to the, for masculine and neuter places."],
      ["Driver", "hear", "Zum Hauptbahnhof?", "To the main station?", "They check which station."],
      ["You", "say", "Nein, zum Bahnhof Altona.", "No, to Altona station.", "Name the right one."],
      ["Driver", "hear", "Alles klar.", "All right.", "They start."],
      ["You", "say", "Hier, bitte. Was kostet das?", "Here, please. What does it cost?", "At the end, ask the price."],
    ],
    checks: [
      [1, "You want the station.", "Zum Bahnhof.", "Um halb Bahnhof.", "Bahnhof Größe M.", "„Zum“ plus the place."],
      [3, "Not the main station.", "Zum Bahnhof Altona.", "Zum Hauptbahnhof.", "Nach China.", "You corrected the station."],
      [5, "Ask the price.", "Was kostet das?", "Wie heißen Sie?", "Wo ist das Bad?", "„Kosten“ is to cost."],
    ],
  }),
  scene({
    id: "a1-near",
    title: "Nearby",
    deTitle: "In der Nähe",
    place: "You want a pharmacy near the station.",
    goal: "Ask what is nearby.",
    canDo: "ask if a place is nearby",
    register: "„In der Nähe von“ plus the place.",
    lines: [
      ["You", "say", "Gibt es eine Apotheke in der Nähe?", "Is there a pharmacy nearby?", "„Gibt es“ is is there."],
      ["Person", "hear", "Ja, neben dem Bahnhof.", "Yes, next to the station.", "„Neben“ is next to."],
      ["You", "say", "Ist sie jetzt geöffnet?", "Is it open now?", "„Jetzt“ is now."],
      ["Person", "hear", "Ja, bis zwanzig Uhr.", "Yes, until 20:00.", "„Bis“ is until."],
      ["You", "say", "Perfekt, danke.", "Perfect, thanks.", "You go there."],
    ],
    checks: [
      [1, "A pharmacy nearby.", "Gibt es eine Apotheke in der Nähe?", "Gibt es Hunger?", "Apotheke ist ein Wochentag.", "„In der Nähe“ is nearby."],
      [2, "Next to the station.", "Neben dem Bahnhof.", "Im Schlafzimmer.", "Unter dem Bett.", "„Neben“ is next to."],
      [4, "Open until 8 p.m.", "Bis zwanzig Uhr.", "Ab zwanzig Tagen.", "Zwanzig Euro.", "„Bis“ plus a time is until."],
    ],
  }),
  scene({
    id: "a1-price",
    title: "How much",
    deTitle: "Was kostet das?",
    place: "You hold an item in a shop.",
    goal: "Ask the price and say it is too expensive.",
    canDo: "ask the price",
    register: "„Was kostet …?“ „Zu teuer.“",
    lines: [
      ["You", "say", "Was kostet das?", "What does this cost?", "Point at the item."],
      ["Staff", "hear", "Vierzig Euro.", "Forty euros.", "The price."],
      ["You", "say", "Das ist zu teuer.", "That is too expensive.", "„Teuer“ is expensive."],
      ["Staff", "hear", "Dieses hier kostet zwanzig.", "This one costs 20.", "A cheaper item."],
      ["You", "say", "Zwanzig ist gut. Das nehme ich.", "Twenty is good. I'll take that.", "„Nehmen“ is to take, to buy."],
    ],
    checks: [
      [1, "Ask the price.", "Was kostet das?", "Wo wohnt das?", "Wie alt ist das?", "„Kosten“ asks the price."],
      [3, "40 euros is too much.", "Das ist zu teuer.", "Das ist zu klein.", "Teuer ist eine Farbe.", "„Teuer“ is expensive."],
      [5, "You buy the cheaper one.", "Das nehme ich.", "Das buchstabiere ich.", "Zwanzig ist mein Alter nur.", "„Nehmen“ here means you buy it."],
    ],
  }),
  scene({
    id: "a1-shop",
    title: "In a shop",
    deTitle: "Im Geschäft",
    place: "You look for milk.",
    goal: "Ask where an item is.",
    canDo: "ask where something is in a shop",
    register: "„Haben Sie …?“ „Wo finde ich …?“",
    lines: [
      ["You", "say", "Wo finde ich die Milch?", "Where can I find the milk?", "„Finden“ is to find."],
      ["Staff", "hear", "Hinten links, im Kühlregal.", "At the back on the left, in the fridge.", "„Hinten“ is at the back."],
      ["You", "say", "Haben Sie auch Brot?", "Do you also have bread?", "„Auch“ adds a second item."],
      ["Staff", "hear", "Brot ist vorne rechts.", "Bread is at the front on the right.", "„Vorne“ is at the front."],
      ["You", "say", "Danke.", "Thanks.", "You can look."],
    ],
    checks: [
      [1, "You want milk.", "Wo finde ich die Milch?", "Wie buchstabiert man Milch?", "Milch ist ein Gleis.", "„Milch“ is the item. „Wo“ is where."],
      [2, "At the back, on the left.", "Hinten links.", "Vorne rechts.", "Neben dem Bett.", "„Hinten“ is the back. „Links“ is left."],
      [4, "Bread is at the front right.", "Vorne rechts.", "Hinten links.", "Im Juli.", "„Vorne“ is the front. „Rechts“ is right."],
    ],
  }),
  scene({
    id: "a1-bag",
    title: "A bag",
    deTitle: "Eine Tüte",
    place: "You pay and they ask about a bag.",
    goal: "Accept or refuse a bag.",
    canDo: "say whether you need a bag",
    register: "„Eine Tüte“ is a bag. „Ich habe eine Tasche.“",
    lines: [
      ["Staff", "hear", "Brauchen Sie eine Tüte?", "Do you need a bag?", "„Brauchen“ is to need."],
      ["You", "say", "Nein, danke. Ich habe eine Tasche.", "No, thanks. I have a bag with me.", "„Tasche“ is your own bag."],
      ["Staff", "hear", "Der Bon ist in der Tüte? Nein.", "The receipt is in the bag? No.", "They correct themselves."],
      ["You", "say", "Den Bon bitte extra.", "The receipt separately, please.", "„Der Bon“ is the receipt."],
      ["Staff", "hear", "Hier, bitte.", "Here you are.", "You have the receipt."],
    ],
    checks: [
      [2, "You do not need their bag.", "Ich habe eine Tasche.", "Ich brauche drei Tüten.", "Tasche ist teuer.", "Your own bag means no shop bag."],
      [4, "You want the receipt.", "Den Bon bitte extra.", "Den Bus bitte.", "Bon ist eine Farbe.", "„Bon“ is the receipt."],
      [1, "„Brauchen Sie eine Tüte?“", "Do you need a bag?", "Do you need a ticket?", "What size is the bag?", "„Tüte“ is the shop bag. „Brauchen“ is need."],
    ],
  }),
  scene({
    id: "a1-cheap",
    title: "Cheap or expensive",
    deTitle: "Billig oder teuer",
    place: "You compare two prices.",
    goal: "Say which one is cheaper.",
    canDo: "compare two prices simply",
    register: "„Billig“ is cheap. „Teuer“ is expensive. „Billiger“ is cheaper.",
    lines: [
      ["Friend", "hear", "Welches nimmst du?", "Which one are you taking?", "A choice."],
      ["You", "say", "Das billige.", "The cheap one.", "„Billig“ is cheap."],
      ["Friend", "hear", "Das andere ist besser.", "The other one is better.", "They prefer quality."],
      ["You", "say", "Aber es ist teurer.", "But it is more expensive.", "„Teurer“ is more expensive."],
      ["Friend", "hear", "Stimmt. Nimm das billige.", "True. Take the cheap one.", "They agree."],
    ],
    checks: [
      [2, "You choose the cheap one.", "Das billige.", "Das teure.", "Das weiße Hemd nur.", "„Billig“ is cheap."],
      [4, "The other one costs more.", "Es ist teurer.", "Es ist billiger.", "Es ist krank.", "„Teurer“ means more expensive."],
      [5, "They agree with the cheap one.", "Nimm das billige.", "Nimm das teure.", "Nimm den Bus.", "They say the cheap one."],
    ],
  }),
  scene({
    id: "a1-weekend",
    title: "The weekend",
    deTitle: "Am Wochenende",
    place: "A colleague asks about your weekend.",
    goal: "Say a simple weekend plan.",
    canDo: "talk about the weekend",
    register: "„Am Wochenende“, „am Samstag“, „am Sonntag“.",
    lines: [
      ["Colleague", "hear", "Was machen Sie am Wochenende?", "What are you doing at the weekend?", "A normal Monday question, or Friday."],
      ["You", "say", "Am Samstag gehe ich auf den Markt.", "On Saturday I go to the market.", "Day plus plan."],
      ["Colleague", "hear", "Und am Sonntag?", "And on Sunday?", "The second day."],
      ["You", "say", "Am Sonntag bleibe ich zu Hause.", "On Sunday I stay home.", "„Bleiben“ is to stay."],
      ["Colleague", "hear", "Das ist auch schön.", "That is nice too.", "No more questions needed."],
    ],
    checks: [
      [2, "Saturday: the market.", "Am Samstag auf den Markt.", "Am Samstag zum Arzt mit Fieber.", "Samstag ist ein Kilo.", "You named the market."],
      [4, "Sunday at home.", "Am Sonntag bleibe ich zu Hause.", "Am Sonntag fahre ich nach Berlin.", "Sonntag ist geöffnet bis acht.", "„Zu Hause bleiben“ is staying home."],
      [1, "„Am Wochenende“.", "At the weekend.", "This morning.", "In August only.", "„Wochenende“ is Saturday and Sunday."],
    ],
  }),
  scene({
    id: "a1-hobby",
    title: "Free time",
    deTitle: "Hobby",
    place: "Someone asks what you do in your free time.",
    goal: "Name a hobby.",
    canDo: "say what you do in your free time",
    register: "„In der Freizeit“. „Ich lese gern.“",
    lines: [
      ["Person", "hear", "Was machen Sie in der Freizeit?", "What do you do in your free time?", "„Freizeit“ is free time."],
      ["You", "say", "Ich lese gern.", "I like reading.", "„Lesen“ is to read. „Gern“ shows you like it."],
      ["Person", "hear", "Bücher?", "Books?", "They check."],
      ["You", "say", "Ja, und manchmal höre ich Musik.", "Yes, and sometimes I listen to music.", "„Musik hören“."],
      ["Person", "hear", "Schön.", "Nice.", "Enough."],
    ],
    checks: [
      [2, "You like reading.", "Ich lese gern.", "Ich lese die Fahrkarte nur als Beruf.", "Lesen ist um drei Uhr.", "„Lesen“ is reading."],
      [4, "Sometimes music.", "Manchmal höre ich Musik.", "Immer koche ich Musik.", "Musik ist eine Größe.", "„Hören“ is to listen."],
      [1, "„Freizeit“.", "Free time.", "Opening hours.", "A platform.", "„Freizeit“ is time off."],
    ],
  }),
  scene({
    id: "a1-sport",
    title: "Sport",
    deTitle: "Sport",
    place: "A classmate asks if you do sport.",
    goal: "Say a sport you do, or that you do none.",
    canDo: "talk about sport",
    register: "„Ich spiele Fußball.“ „Ich mache keinen Sport.“",
    lines: [
      ["Classmate", "hear", "Machst du Sport?", "Do you do sport?", "A yes/no question."],
      ["You", "say", "Ja, ich schwimme gern.", "Yes, I like swimming.", "„Schwimmen“ is to swim."],
      ["Classmate", "hear", "Wie oft?", "How often?", "Frequency."],
      ["You", "say", "Einmal in der Woche.", "Once a week.", "„Einmal“ is once."],
      ["Classmate", "hear", "Ich spiele Fußball.", "I play football.", "You only need to understand „Fußball“."],
    ],
    checks: [
      [2, "You like swimming.", "Ich schwimme gern.", "Ich schwimme nach Berlin als Ticket.", "Schwimmen ist teuer um halb.", "„Schwimmen“ is the sport."],
      [4, "Once a week.", "Einmal in der Woche.", "Dreimal am Tag Tabletten.", "Eine Woche ist ein Kilo.", "„Einmal in der Woche“ is weekly."],
      [5, "„Fußball“.", "Football.", "Swimming.", "A market.", "„Fußball“ is football."],
    ],
  }),
  scene({
    id: "a1-music",
    title: "Music",
    deTitle: "Musik",
    place: "Someone asks what music you like.",
    goal: "Say you like music, without a long opinion.",
    canDo: "say you like music",
    register: "„Ich höre gern Musik.“",
    lines: [
      ["Person", "hear", "Hörst du gern Musik?", "Do you like listening to music?", "„Hören“ is to hear, to listen."],
      ["You", "say", "Ja, sehr gern.", "Yes, very much.", "„Sehr gern“ is a full answer."],
      ["Person", "hear", "Welche Musik?", "Which music?", "They want a type."],
      ["You", "say", "Ruhige Musik.", "Quiet music.", "„Ruhig“ is quiet, calm."],
      ["Person", "hear", "Ich auch.", "Me too.", "Shared taste."],
    ],
    checks: [
      [2, "You like it a lot.", "Ja, sehr gern.", "Nein, nie.", "Musik ist eine Haltestelle.", "„Sehr gern“ is strongly yes."],
      [4, "Calm music.", "Ruhige Musik.", "Laute Arbeit.", "Ruhig ist ein Gleis.", "„Ruhig“ means quiet."],
      [1, "„Hörst du gern Musik?“", "Do you like music?", "Do you play football?", "Where is the music shop?", "„Hören“ plus „gern“ asks if you like listening."],
    ],
  }),
  scene({
    id: "a1-birthday",
    title: "A birthday",
    deTitle: "Geburtstag",
    place: "A colleague has a birthday.",
    goal: "Say happy birthday and give a small wish.",
    canDo: "wish someone a happy birthday",
    register: "„Herzlichen Glückwunsch zum Geburtstag.“",
    lines: [
      ["You", "say", "Herzlichen Glückwunsch zum Geburtstag.", "Happy birthday.", "The full wish. Learn it as one line."],
      ["Colleague", "hear", "Danke! Woher weißt du das?", "Thanks! How do you know?", "They are pleased."],
      ["You", "say", "Es steht im Kalender.", "It is in the calendar.", "„Kalender“ is the calendar."],
      ["Colleague", "hear", "Wie alt bist du eigentlich?", "How old are you, actually?", "They ask you, informal."],
      ["You", "say", "Dreißig.", "Thirty.", "A number is enough."],
    ],
    checks: [
      [1, "It is their birthday.", "Herzlichen Glückwunsch zum Geburtstag.", "Auf Wiedersehen zum Geburtstag.", "Gute Nacht zum Arzt.", "That is the birthday wish."],
      [3, "You saw it in the calendar.", "Im Kalender.", "Auf dem Gleis.", "In der Tüte.", "„Kalender“ is the calendar."],
      [5, "You are 30.", "Dreißig.", "Drei.", "Dreizehn Uhr.", "„Dreißig“ is 30, not 3."],
    ],
  }),
  scene({
    id: "a1-invite",
    title: "An invitation",
    deTitle: "Kommst du mit?",
    place: "A friend invites you for coffee.",
    goal: "Accept or refuse an invitation.",
    canDo: "accept or refuse an invitation",
    register: "„Gern.“ „Leider kann ich nicht.“",
    lines: [
      ["Friend", "hear", "Hast du am Freitag Zeit?", "Do you have time on Friday?", "„Zeit haben“ is to have time."],
      ["You", "say", "Am Freitag ja.", "On Friday, yes.", "You are free."],
      ["Friend", "hear", "Kommst du auf einen Kaffee?", "Will you come for a coffee?", "The invitation."],
      ["You", "say", "Gern. Um wie viel Uhr?", "Gladly. At what time?", "Accept, then ask the time."],
      ["Friend", "hear", "Um vier.", "At four.", "The time is set."],
    ],
    checks: [
      [1, "Friday.", "You have time.", "You are ill.", "You need a platform.", "You said yes for Friday."],
      [4, "You accept.", "Gern.", "Leider nicht.", "Zu teuer.", "„Gern“ accepts."],
      [5, "The meeting time.", "At 4:00.", "At 4 euros.", "On platform 4.", "„Um vier“ is the time."],
    ],
  }),
  scene({
    id: "a1-sorry",
    title: "You cannot come",
    deTitle: "Leider nicht",
    place: "Someone invites you. You are not free.",
    goal: "Refuse politely.",
    canDo: "refuse an invitation politely",
    register: "„Leider“ softens the no.",
    lines: [
      ["Friend", "hear", "Kommst du morgen mit?", "Are you coming along tomorrow?", "An invitation."],
      ["You", "say", "Leider kann ich nicht.", "Unfortunately I can't.", "„Leider“ first."],
      ["Friend", "hear", "Warum nicht?", "Why not?", "They ask the reason."],
      ["You", "say", "Ich muss arbeiten.", "I have to work.", "„Müssen“ is must, have to."],
      ["Friend", "hear", "Schade. Ein andermal.", "Pity. Another time.", "„Schade“ is a shame."],
    ],
    checks: [
      [2, "You cannot come.", "Leider kann ich nicht.", "Gern, um vier.", "Leider ist das billig.", "„Leider“ plus „nicht“ is a soft no."],
      [4, "The reason is work.", "Ich muss arbeiten.", "Ich muss ein Kilo Äpfel.", "Arbeiten ist eine Farbe.", "„Müssen“ plus „arbeiten“."],
      [5, "„Schade.“", "What a pity.", "See you at four.", "The shop is open.", "„Schade“ reacts to the refusal."],
    ],
  }),
  scene({
    id: "a1-work",
    title: "At work",
    deTitle: "Die Arbeit",
    place: "Someone asks about your working day.",
    goal: "Say when you work.",
    canDo: "say your working hours",
    register: "„Von … bis … arbeiten.“",
    lines: [
      ["Person", "hear", "Wann arbeiten Sie?", "When do you work?", "Hours, not the job title."],
      ["You", "say", "Von neun bis siebzehn Uhr.", "From 9 to 17.", "A normal office day."],
      ["Person", "hear", "Auch am Freitag?", "On Friday too?", "They check the week."],
      ["You", "say", "Ja, aber nur bis vierzehn Uhr.", "Yes, but only until 14:00.", "Friday is shorter."],
      ["Person", "hear", "Das ist schön.", "That is nice.", "Done."],
    ],
    checks: [
      [2, "9:00 to 17:00.", "Von neun bis siebzehn Uhr.", "Von neun bis siebzehn Euro.", "Neun Zimmer.", "A span of working hours."],
      [4, "Friday ends earlier.", "Nur bis vierzehn Uhr.", "Bis zwanzig Uhr.", "Am Freitag frei ganz.", "14:00 is the Friday end."],
      [1, "„Wann arbeiten Sie?“", "When do you work?", "Where is the office chair?", "What is your name?", "„Wann“ asks the time."],
    ],
  }),
  scene({
    id: "a1-office",
    title: "The office",
    deTitle: "Im Büro",
    place: "You arrive at work and greet a colleague.",
    goal: "Use a few office words.",
    canDo: "talk about a simple office morning",
    register: "„Das Büro“, „der Computer“, „die Pause“.",
    lines: [
      ["Colleague", "hear", "Morgen. Kaffee?", "Morning. Coffee?", "A short office hello."],
      ["You", "say", "Gern. Danach arbeite ich am Computer.", "Gladly. After that I work on the computer.", "„Danach“ is after that."],
      ["Colleague", "hear", "Wann ist deine Pause?", "When is your break?", "„Pause“ is the break."],
      ["You", "say", "Um zwölf.", "At twelve.", "Lunchtime."],
      ["Colleague", "hear", "Bis später.", "See you later.", "You both start work."],
    ],
    checks: [
      [2, "After coffee, the computer.", "Danach am Computer.", "Danach zum Gleis drei.", "Computer ist eine Suppe.", "„Computer“ is the work tool here."],
      [3, "They ask about the break.", "Wann ist deine Pause?", "Wo ist der Bahnhof?", "Wie buchstabiert man Pause?", "„Pause“ is the break."],
      [4, "The break is at noon.", "Um zwölf.", "Um zwei.", "Zwölf Euro.", "„Zwölf“ is 12:00."],
    ],
  }),
  scene({
    id: "a1-course",
    title: "The German course",
    deTitle: "Der Kurs",
    place: "You ask about a German class.",
    goal: "Ask when the course is.",
    canDo: "ask about a course",
    register: "„Der Deutschkurs“, „das Niveau A1“.",
    lines: [
      ["You", "say", "Gibt es einen Deutschkurs?", "Is there a German course?", "„Deutschkurs“ is the class."],
      ["Staff", "hear", "Ja, Niveau A1.", "Yes, level A1.", "„Niveau“ is the level."],
      ["You", "say", "Wann ist der Kurs?", "When is the course?", "Day and time."],
      ["Staff", "hear", "Dienstag und Donnerstag, um achtzehn Uhr.", "Tuesday and Thursday, at 18:00.", "Two days."],
      ["You", "say", "Ich möchte mich anmelden.", "I would like to register.", "„Sich anmelden“ is to sign up."],
    ],
    checks: [
      [1, "You want a German class.", "Gibt es einen Deutschkurs?", "Gibt es ein Kilo Äpfel?", "Deutschkurs ist das Wetter.", "„Deutschkurs“ is the course."],
      [4, "Tuesday and Thursday at 18:00.", "Dienstag und Donnerstag, achtzehn Uhr.", "Montag um acht.", "Donnerstag ist ein Monat.", "Those two weekdays, evening."],
      [5, "You want to sign up.", "Ich möchte mich anmelden.", "Ich möchte zahlen bitte nur.", "Anmelden ist links.", "„Anmelden“ is to register."],
    ],
  }),
  scene({
    id: "a1-understand",
    title: "I don't understand",
    deTitle: "Ich verstehe nicht",
    place: "In class, a sentence was too fast.",
    goal: "Ask someone to repeat and slow down.",
    canDo: "say you do not understand",
    register: "These three lines are worth knowing by heart.",
    lines: [
      ["You", "say", "Ich verstehe nicht.", "I don't understand.", "Say this early."],
      ["Teacher", "hear", "Was verstehen Sie nicht?", "What don't you understand?", "They ask which part."],
      ["You", "say", "Den letzten Satz.", "The last sentence.", "„Satz“ is a sentence."],
      ["Teacher", "hear", "Ich wiederhole.", "I'll repeat.", "„Wiederholen“ is to repeat."],
      ["You", "say", "Langsamer, bitte.", "More slowly, please.", "„Langsam“ is slow."],
    ],
    checks: [
      [1, "You did not understand.", "Ich verstehe nicht.", "Ich verstehe alles.", "Verstehen ist ein Ticket.", "The negative is the point."],
      [3, "The last sentence.", "Den letzten Satz.", "Den ersten Bus.", "Satz ist eine Farbe.", "„Satz“ is the sentence."],
      [5, "Ask for a slower repeat.", "Langsamer, bitte.", "Schneller, bitte.", "Lauter als Musik nur.", "„Langsamer“ means more slowly."],
    ],
  }),
  scene({
    id: "a1-spell-word",
    title: "How do you write it?",
    deTitle: "Wie schreibt man das?",
    place: "You hear a new word in class.",
    goal: "Ask for the spelling of a word.",
    canDo: "ask how a word is spelled",
    register: "„Wie schreibt man …?“ „Was bedeutet …?“",
    lines: [
      ["You", "say", "Wie schreibt man Bahnhof?", "How do you spell Bahnhof?", "The spelling question plus the word."],
      ["Teacher", "hear", "B-A-H-N-H-O-F.", "B-A-H-N-H-O-F.", "The letters."],
      ["You", "say", "Was bedeutet das?", "What does that mean?", "Meaning, after spelling."],
      ["Teacher", "hear", "Der Bahnhof ist die Station für Züge.", "The Bahnhof is the station for trains.", "A simple definition."],
      ["You", "say", "Danke, jetzt verstehe ich.", "Thanks, now I understand.", "„Jetzt“ closes it."],
    ],
    checks: [
      [1, "Ask the spelling.", "Wie schreibt man Bahnhof?", "Wo ist der Bahnhof nur als Weg.", "Bahnhof kostet dreißig.", "„Wie schreibt man“ asks for letters."],
      [3, "Ask the meaning.", "Was bedeutet das?", "Was kostet das?", "Wie alt ist das Wort?", "„Bedeuten“ is to mean."],
      [4, "A Bahnhof is for trains.", "Die Station für Züge.", "Ein Zimmer im Haus.", "Eine Farbe.", "The definition is the train station."],
    ],
  }),
];
