import { extraScenes } from "./extra-scenes.js";

/** Everyday scenes. Each one is a single counter, call, or conversation — five lines. */
const coreScenes = [
  {
    id: "bakery",
    level: 1,
    title: "At the bakery",
    deTitle: "Beim Bäcker",
    place: "Saturday morning. The counter is busy and someone is waiting behind you.",
    goal: "Order bread, and pay on one bill.",
    canDo: "order bread at a bakery counter",
    register: "No names and no small talk. „Ich hätte gern“ is the polite way to ask.",
    phrases: [
      {
        id: "bakery-1",
        speaker: "You",
        kind: "say",
        de: "Guten Morgen. Ich hätte gern zwei Brötchen.",
        en: "Good morning. I’d like two rolls.",
        tip: "Say this right after hello. „Hätte gern“ is softer than „ich will“, and it is what people actually say.",
        sound: "Brötchen sounds like BREWT-chen. The ö is the vowel in “burn”, with rounded lips.",
      },
      {
        id: "bakery-2",
        speaker: "Staff",
        kind: "hear",
        de: "Gerne. Sonst noch etwas?",
        en: "Sure. Anything else?",
        tip: "You will hear this before you pay. If you want more, name it. If not, the next line closes the order.",
      },
      {
        id: "bakery-3",
        speaker: "You",
        kind: "say",
        de: "Und ein Roggenbrot, bitte.",
        en: "And a rye bread, please.",
        tip: "Add „und“ when the order is still open. „Bitte“ at the end is enough politeness.",
      },
      {
        id: "bakery-4",
        speaker: "Staff",
        kind: "hear",
        de: "Zusammen oder getrennt?",
        en: "Together or separate?",
        tip: "They mean the bill: one payment, or split. This question shows up at bakeries and restaurants.",
      },
      {
        id: "bakery-5",
        speaker: "You",
        kind: "say",
        de: "Zusammen, bitte.",
        en: "Together, please.",
        tip: "One word does the job. „Getrennt“ if each person pays their own.",
      },
    ],
    checks: [
      {
        id: "bakery-c1",
        phraseId: "bakery-1",
        prompt: "You want two rolls. What do you say after hello?",
        options: [
          { text: "Ich hätte gern zwei Brötchen.", correct: true },
          { text: "Ich bin zwei Brötchen.", correct: false },
          { text: "Brötchen ist bitte morgen.", correct: false },
        ],
        why: "„Ich hätte gern …“ plus the thing you want. That is the normal order at a counter.",
      },
      {
        id: "bakery-c2",
        phraseId: "bakery-2",
        prompt: "The person at the counter says: „Sonst noch etwas?“",
        options: [
          { text: "They are asking if you want anything else.", correct: true },
          { text: "They are asking your name.", correct: false },
          { text: "They are saying the bakery is closed.", correct: false },
        ],
        why: "„Sonst noch etwas?“ means “anything else?”. You hear it every day before the total.",
      },
      {
        id: "bakery-c3",
        phraseId: "bakery-5",
        prompt: "You are paying one bill for everything. What do you answer to „Zusammen oder getrennt?“",
        options: [
          { text: "Zusammen, bitte.", correct: true },
          { text: "Getrennt, bitte.", correct: false },
          { text: "Guten Morgen.", correct: false },
        ],
        why: "„Zusammen“ is one payment. „Getrennt“ means you split it.",
      },
    ],
  },
  {
    id: "cafe",
    level: 1,
    title: "Coffee to go",
    deTitle: "Kaffee zum Mitnehmen",
    place: "A café on the way to work. You have two minutes.",
    goal: "Order a coffee to go, with oat milk.",
    canDo: "order a coffee to go",
    register: "Short and polite. The barista will ask „für hier oder zum Mitnehmen?“",
    phrases: [
      {
        id: "cafe-1",
        speaker: "You",
        kind: "say",
        de: "Einen Cappuccino zum Mitnehmen, bitte.",
        en: "A cappuccino to go, please.",
        tip: "Put „zum Mitnehmen“ in the first sentence and they will not have to ask.",
      },
      {
        id: "cafe-2",
        speaker: "Staff",
        kind: "hear",
        de: "Mit normaler Milch?",
        en: "With regular milk?",
        tip: "They mean cow’s milk. This is your moment to name a different one.",
      },
      {
        id: "cafe-3",
        speaker: "You",
        kind: "say",
        de: "Mit Hafermilch, bitte.",
        en: "With oat milk, please.",
        tip: "Hafermilch is oat milk. Say the milk type right after they ask.",
        sound: "Hafermilch sounds like HAH-fer-milsh.",
      },
      {
        id: "cafe-4",
        speaker: "Staff",
        kind: "hear",
        de: "Für hier haben wir Tassen, zum Mitnehmen nur Becher.",
        en: "For here we have cups; to go, only paper cups.",
        tip: "„Für hier“ means you stay. „Becher“ is the paper cup. You already chose to go.",
      },
      {
        id: "cafe-5",
        speaker: "You",
        kind: "say",
        de: "Zum Mitnehmen ist gut. Danke.",
        en: "To go is fine. Thanks.",
        tip: "„Ist gut“ accepts what they offered. Then you can pay.",
      },
    ],
    checks: [
      {
        id: "cafe-c1",
        phraseId: "cafe-1",
        prompt: "You will not stay. How do you order the coffee?",
        options: [
          { text: "Einen Cappuccino zum Mitnehmen, bitte.", correct: true },
          { text: "Einen Cappuccino für hier, bitte.", correct: false },
          { text: "Ich will Milch Kaffee.", correct: false },
        ],
        why: "„Zum Mitnehmen“ means to go. „Für hier“ means you are staying in.",
      },
      {
        id: "cafe-c2",
        phraseId: "cafe-3",
        prompt: "They ask „Mit normaler Milch?“ You want oat milk.",
        options: [
          { text: "Mit Hafermilch, bitte.", correct: true },
          { text: "Zum Mitnehmen, bitte.", correct: false },
          { text: "Keine Tasse, danke.", correct: false },
        ],
        why: "Answer the question they asked. Here that is the kind of milk.",
      },
      {
        id: "cafe-c3",
        phraseId: "cafe-4",
        prompt: "What is the barista telling you?",
        options: [
          { text: "To go, you get a paper cup, not a ceramic one.", correct: true },
          { text: "The café is out of coffee.", correct: false },
          { text: "Oat milk costs extra and is gone.", correct: false },
        ],
        why: "„Becher“ is the takeaway cup. They are explaining the cups, not refusing the order.",
      },
    ],
  },
  {
    id: "supermarket",
    level: 1,
    title: "At the checkout",
    deTitle: "An der Kasse",
    place: "Supermarket checkout. The belt is moving.",
    goal: "Ask for a bag and pay by card.",
    canDo: "pay at a supermarket checkout",
    register: "Cashiers are quick. Match their pace: one short line at a time.",
    phrases: [
      {
        id: "supermarket-1",
        speaker: "You",
        kind: "say",
        de: "Ich hätte gern eine Tüte, bitte.",
        en: "I’d like a bag, please.",
        tip: "Bags are often not free and not automatic. Ask before they finish scanning.",
        sound: "Tüte sounds like TEW-teh.",
      },
      {
        id: "supermarket-2",
        speaker: "Staff",
        kind: "hear",
        de: "Eine kleine?",
        en: "A small one?",
        tip: "They are checking the size. „Klein“ is small. You can just say yes.",
      },
      {
        id: "supermarket-3",
        speaker: "You",
        kind: "say",
        de: "Ja, eine kleine, bitte.",
        en: "Yes, a small one, please.",
        tip: "Repeat the size back. It is clearer than only „ja“ when the shop is loud.",
      },
      {
        id: "supermarket-4",
        speaker: "Staff",
        kind: "hear",
        de: "Das macht acht Euro zwanzig.",
        en: "That’s eight euros twenty.",
        tip: "„Das macht …“ is how you hear a total. The comma is the decimal point: 8,20.",
      },
      {
        id: "supermarket-5",
        speaker: "You",
        kind: "say",
        de: "Mit Karte, bitte.",
        en: "By card, please.",
        tip: "Say this as you hold the card out. „Bar“ would mean cash.",
      },
    ],
    checks: [
      {
        id: "supermarket-c1",
        phraseId: "supermarket-1",
        prompt: "You need a bag. What do you say?",
        options: [
          { text: "Ich hätte gern eine Tüte, bitte.", correct: true },
          { text: "Das macht eine Tüte.", correct: false },
          { text: "Mit Karte, bitte.", correct: false },
        ],
        why: "Ask for the bag the same way you ask for bread: „Ich hätte gern …“",
      },
      {
        id: "supermarket-c2",
        phraseId: "supermarket-4",
        prompt: "The cashier says: „Das macht acht Euro zwanzig.“",
        options: [
          { text: "The total is 8.20 euros.", correct: true },
          { text: "The store closes at 8:20.", correct: false },
          { text: "Your card was declined.", correct: false },
        ],
        why: "„Das macht“ introduces the price. In German the comma separates cents: 8,20.",
      },
      {
        id: "supermarket-c3",
        phraseId: "supermarket-5",
        prompt: "You want to pay by card, not cash.",
        options: [
          { text: "Mit Karte, bitte.", correct: true },
          { text: "Eine kleine, bitte.", correct: false },
          { text: "Bar, bitte.", correct: false },
        ],
        why: "„Mit Karte“ is card. „Bar“ is cash.",
      },
    ],
  },
  {
    id: "tram",
    level: 2,
    title: "A ticket in the station",
    deTitle: "Eine Fahrkarte",
    place: "You are at a staffed ticket window. Your train leaves soon.",
    goal: "Buy a one-way ticket and ask if you have to change.",
    canDo: "buy a train ticket and ask about changing",
    register: "„Sie“ is right at a window. Keep each request to one sentence.",
    phrases: [
      {
        id: "tram-1",
        speaker: "You",
        kind: "say",
        de: "Einmal zum Hauptbahnhof, bitte.",
        en: "One ticket to the main station, please.",
        tip: "„Einmal“ plus the destination is the standard way to ask for a single ticket.",
        sound: "Hauptbahnhof sounds like HOUPT-ban-hof.",
      },
      {
        id: "tram-2",
        speaker: "Staff",
        kind: "hear",
        de: "Einzelfahrt oder Tageskarte?",
        en: "A single ride or a day pass?",
        tip: "Einzelfahrt is one ride. A Tageskarte is worth it only if you will ride again today.",
      },
      {
        id: "tram-3",
        speaker: "You",
        kind: "say",
        de: "Eine Einzelfahrt, bitte.",
        en: "A single ride, please.",
        tip: "Use „eine“ here: die Einzelfahrt. Answer with the word they offered.",
      },
      {
        id: "tram-4",
        speaker: "Staff",
        kind: "hear",
        de: "Das macht drei Euro vierzig.",
        en: "That’s three euros forty.",
        tip: "Same price pattern as the supermarket. 3,40.",
      },
      {
        id: "tram-5",
        speaker: "You",
        kind: "say",
        de: "Muss ich umsteigen?",
        en: "Do I have to change?",
        tip: "Ask before you walk away. „Einmal umsteigen“ means you change once.",
        sound: "Umsteigen sounds like OOM-shty-gen.",
      },
    ],
    checks: [
      {
        id: "tram-c1",
        phraseId: "tram-1",
        prompt: "You need one ticket to the main station.",
        options: [
          { text: "Einmal zum Hauptbahnhof, bitte.", correct: true },
          { text: "Eine Tageskarte zum Kaffee, bitte.", correct: false },
          { text: "Wo ist die Milch?", correct: false },
        ],
        why: "„Einmal“ + destination is the sentence people use at the window.",
      },
      {
        id: "tram-c2",
        phraseId: "tram-2",
        prompt: "They ask: „Einzelfahrt oder Tageskarte?“",
        options: [
          { text: "They want to know: one ride, or unlimited rides today?", correct: true },
          { text: "They want to know your platform number.", correct: false },
          { text: "They are asking if you have a reservation.", correct: false },
        ],
        why: "Those are the two ordinary ticket types for a city trip.",
      },
      {
        id: "tram-c3",
        phraseId: "tram-5",
        prompt: "You do not know if this train goes all the way.",
        options: [
          { text: "Muss ich umsteigen?", correct: true },
          { text: "Zusammen, bitte.", correct: false },
          { text: "Mit Hafermilch, bitte.", correct: false },
        ],
        why: "„Umsteigen“ is changing trains. Ask it at the window, not on the platform in a rush.",
      },
    ],
  },
  {
    id: "pharmacy",
    level: 2,
    title: "At the pharmacy",
    deTitle: "In der Apotheke",
    place: "You have a headache and no prescription. The pharmacist is asking a few questions.",
    goal: "Ask for something for a headache and catch the dose.",
    canDo: "ask a pharmacy for headache medicine",
    register: "Pharmacies use „Sie“. Answer their question before you add your own.",
    phrases: [
      {
        id: "pharmacy-1",
        speaker: "You",
        kind: "say",
        de: "Ich brauche etwas gegen Kopfschmerzen.",
        en: "I need something for a headache.",
        tip: "„Etwas gegen …“ is the pattern: something for a symptom. It works for a cough or a cold too.",
        sound: "Kopfschmerzen sounds like KOPF-shmer-tsen.",
      },
      {
        id: "pharmacy-2",
        speaker: "Staff",
        kind: "hear",
        de: "Haben Sie Allergien?",
        en: "Do you have any allergies?",
        tip: "A yes/no question. Answer it before you talk about the packet.",
      },
      {
        id: "pharmacy-3",
        speaker: "You",
        kind: "say",
        de: "Nein, keine.",
        en: "No, none.",
        tip: "That is the whole answer. „Keine“ stands in for „keine Allergien“.",
      },
      {
        id: "pharmacy-4",
        speaker: "Staff",
        kind: "hear",
        de: "Eine Tablette bis zu dreimal am Tag, nach dem Essen.",
        en: "One tablet up to three times a day, after eating.",
        tip: "Dose, how often, and when. Repeat it back if the shop is noisy.",
      },
      {
        id: "pharmacy-5",
        speaker: "You",
        kind: "say",
        de: "Alles klar. Ich nehme diese Packung.",
        en: "Got it. I’ll take this packet.",
        tip: "„Packung“ is the box. Point at it as you say „diese“.",
      },
    ],
    checks: [
      {
        id: "pharmacy-c1",
        phraseId: "pharmacy-1",
        prompt: "You need headache medicine, nothing more specific.",
        options: [
          { text: "Ich brauche etwas gegen Kopfschmerzen.", correct: true },
          { text: "Ich hätte gern eine Tüte.", correct: false },
          { text: "Muss ich umsteigen?", correct: false },
        ],
        why: "„Etwas gegen“ + the symptom is enough. The pharmacist will choose a product.",
      },
      {
        id: "pharmacy-c2",
        phraseId: "pharmacy-2",
        prompt: "They ask „Haben Sie Allergien?“ and you do not.",
        options: [
          { text: "Nein, keine.", correct: true },
          { text: "Dreimal am Tag.", correct: false },
          { text: "Ja, eine Packung.", correct: false },
        ],
        why: "Answer the allergy question first. The dose comes from them, not from you.",
      },
      {
        id: "pharmacy-c3",
        phraseId: "pharmacy-4",
        prompt: "What did the pharmacist tell you to do?",
        options: [
          { text: "Up to three tablets a day, after food.", correct: true },
          { text: "Three packets once, before breakfast only.", correct: false },
          { text: "Stop eating for three days.", correct: false },
        ],
        why: "„Bis zu dreimal am Tag“ is “up to three times a day”. „Nach dem Essen“ is after meals.",
      },
    ],
  },
  {
    id: "restaurant",
    level: 2,
    title: "A table for two",
    deTitle: "Ein Tisch für zwei",
    place: "Evening. You did not reserve. You need a table and a vegetarian dish.",
    goal: "Get a table without a reservation and order the soup.",
    canDo: "ask for a table and a vegetarian dish",
    register: "„Sie“ with the staff. One request, then wait.",
    phrases: [
      {
        id: "restaurant-1",
        speaker: "You",
        kind: "say",
        de: "Einen Tisch für zwei, bitte.",
        en: "A table for two, please.",
        tip: "Say the number of people first. That is how they decide if they have room.",
      },
      {
        id: "restaurant-2",
        speaker: "Staff",
        kind: "hear",
        de: "Haben Sie reserviert?",
        en: "Do you have a reservation?",
        tip: "Yes/no. If the answer is no, say so plainly — it is a normal evening, not a problem yet.",
      },
      {
        id: "restaurant-3",
        speaker: "You",
        kind: "say",
        de: "Nein. Haben Sie etwas Vegetarisches?",
        en: "No. Do you have something vegetarian?",
        tip: "Two beats: answer, then the food question. „Etwas Vegetarisches“ is the useful chunk.",
      },
      {
        id: "restaurant-4",
        speaker: "Staff",
        kind: "hear",
        de: "Die Tagessuppe ist vegetarisch.",
        en: "The soup of the day is vegetarian.",
        tip: "„Tagessuppe“ changes every day. You can order it without reading the whole menu.",
        sound: "Tagessuppe sounds like TAH-ges-zoo-peh.",
      },
      {
        id: "restaurant-5",
        speaker: "You",
        kind: "say",
        de: "Dann die Tagessuppe, bitte.",
        en: "Then the soup of the day, please.",
        tip: "„Dann“ means you are choosing from what they just offered.",
      },
    ],
    checks: [
      {
        id: "restaurant-c1",
        phraseId: "restaurant-1",
        prompt: "Two people, no other details yet.",
        options: [
          { text: "Einen Tisch für zwei, bitte.", correct: true },
          { text: "Eine Tagessuppe für hier.", correct: false },
          { text: "Zusammen oder getrennt?", correct: false },
        ],
        why: "Ask for the table before the food. They need the number of people.",
      },
      {
        id: "restaurant-c2",
        phraseId: "restaurant-2",
        prompt: "„Haben Sie reserviert?“",
        options: [
          { text: "They are asking if you booked a table.", correct: true },
          { text: "They are asking if you are vegetarian.", correct: false },
          { text: "They are bringing the bill.", correct: false },
        ],
        why: "Reserviert = booked. The vegetarian question is yours to ask next.",
      },
      {
        id: "restaurant-c3",
        phraseId: "restaurant-5",
        prompt: "The soup of the day works. How do you order it?",
        options: [
          { text: "Dann die Tagessuppe, bitte.", correct: true },
          { text: "Nein, keine Tagessuppe.", correct: false },
          { text: "Ich brauche etwas gegen die Suppe.", correct: false },
        ],
        why: "„Dann“ plus the dish accepts their suggestion.",
      },
    ],
  },
  {
    id: "neighbor",
    level: 3,
    title: "The neighbor in the stairwell",
    deTitle: "Die Nachbarin im Treppenhaus",
    place: "Early evening. You will have people over and the walls are thin.",
    goal: "Warn the neighbor, and say when it will be quiet again.",
    canDo: "tell a neighbor about noise before it happens",
    register: "„Sie“ until they offer „du“. Lead with the warning, not an apology essay.",
    phrases: [
      {
        id: "neighbor-1",
        speaker: "You",
        kind: "say",
        de: "Guten Tag, ich wohne in der Wohnung nebenan.",
        en: "Hello, I live in the flat next door.",
        tip: "Place yourself first. „Nebenan“ means next door.",
      },
      {
        id: "neighbor-2",
        speaker: "You",
        kind: "say",
        de: "Ich wollte kurz Bescheid sagen.",
        en: "I just wanted to let you know.",
        tip: "„Bescheid sagen“ is the everyday phrase for a heads-up. People use it constantly.",
        sound: "Bescheid sounds like beh-SHIDE.",
      },
      {
        id: "neighbor-3",
        speaker: "You",
        kind: "say",
        de: "Heute Abend ist es bei uns etwas lauter.",
        en: "This evening it will be a bit louder at ours.",
        tip: "„Bei uns“ means at our place. „Etwas lauter“ is honest without dramatizing.",
      },
      {
        id: "neighbor-4",
        speaker: "Neighbor",
        kind: "hear",
        de: "Wie lange ungefähr?",
        en: "About how long?",
        tip: "They are not refusing. They want an end time. Give a clock time.",
      },
      {
        id: "neighbor-5",
        speaker: "You",
        kind: "say",
        de: "Bis zehn. Danach ist Ruhe. Danke.",
        en: "Until ten. Quiet after that. Thanks.",
        tip: "A clock time plus „danach ist Ruhe“ is the line neighbors hope to hear.",
      },
    ],
    checks: [
      {
        id: "neighbor-c1",
        phraseId: "neighbor-2",
        prompt: "You want to give a polite heads-up, not make a speech.",
        options: [
          { text: "Ich wollte kurz Bescheid sagen.", correct: true },
          { text: "Ich hätte gern eine Tüte.", correct: false },
          { text: "Das macht acht Euro.", correct: false },
        ],
        why: "„Bescheid sagen“ is “let someone know”. „Kurz“ keeps it small.",
      },
      {
        id: "neighbor-c2",
        phraseId: "neighbor-4",
        prompt: "The neighbor asks „Wie lange ungefähr?“",
        options: [
          { text: "They want to know when the noise stops.", correct: true },
          { text: "They want to know your flat number.", correct: false },
          { text: "They are asking you to leave the building.", correct: false },
        ],
        why: "„Wie lange“ is about duration. Answer with „bis“ and a time.",
      },
      {
        id: "neighbor-c3",
        phraseId: "neighbor-5",
        prompt: "It will be quiet again at 10.",
        options: [
          { text: "Bis zehn. Danach ist Ruhe.", correct: true },
          { text: "Ab zehn ist es lauter.", correct: false },
          { text: "Zehn Wohnungen, bitte.", correct: false },
        ],
        why: "„Bis zehn“ means until 10. „Ab zehn“ would mean starting at 10 — the opposite.",
      },
    ],
  },
  {
    id: "appointment",
    level: 3,
    title: "Booking a time",
    deTitle: "Einen Termin machen",
    place: "You are on the phone with a clinic desk. You need a morning slot.",
    goal: "Book Friday morning and confirm the half-hour.",
    canDo: "book an appointment for a morning time",
    register: "Phone German is „Sie“. Repeat the time back so you both have the same one.",
    phrases: [
      {
        id: "appointment-1",
        speaker: "You",
        kind: "say",
        de: "Guten Tag, ich brauche einen Termin.",
        en: "Hello, I need an appointment.",
        tip: "Say why you are calling in the first sentence. They will ask when.",
      },
      {
        id: "appointment-2",
        speaker: "Staff",
        kind: "hear",
        de: "Wann passt es Ihnen?",
        en: "When works for you?",
        tip: "„Passen“ means “to suit”. Give a part of the day, not a long story.",
      },
      {
        id: "appointment-3",
        speaker: "You",
        kind: "say",
        de: "Freitagvormittag, wenn das geht.",
        en: "Friday morning, if that’s possible.",
        tip: "„Vormittag“ is the morning before lunch. „Wenn das geht“ leaves them room.",
      },
      {
        id: "appointment-4",
        speaker: "Staff",
        kind: "hear",
        de: "Halb zehn?",
        en: "Half past nine?",
        tip: "„Halb zehn“ is 9:30, not 10:30. The hour named is the one you are going toward.",
        sound: "Halb zehn is 9:30. Halb acht is 7:30. The number is the coming hour.",
      },
      {
        id: "appointment-5",
        speaker: "You",
        kind: "say",
        de: "Ja, halb zehn passt. Vielen Dank.",
        en: "Yes, 9:30 works. Thank you.",
        tip: "Repeat „halb zehn“ out loud. If you heard it wrong, this is when it gets fixed.",
      },
    ],
    checks: [
      {
        id: "appointment-c1",
        phraseId: "appointment-3",
        prompt: "You can come Friday morning. Nothing else is fixed yet.",
        options: [
          { text: "Freitagvormittag, wenn das geht.", correct: true },
          { text: "Halb zehn ist vorbei.", correct: false },
          { text: "Ich wohne nebenan.", correct: false },
        ],
        why: "Offer the window of time first. Let them pick the exact slot.",
      },
      {
        id: "appointment-c2",
        phraseId: "appointment-4",
        prompt: "They say „Halb zehn?“ What time is that?",
        options: [
          { text: "9:30", correct: true },
          { text: "10:30", correct: false },
          { text: "10:00", correct: false },
        ],
        why: "Halb + an hour means 30 minutes before that hour. Halb zehn is half an hour before 10.",
      },
      {
        id: "appointment-c3",
        phraseId: "appointment-5",
        prompt: "9:30 is fine. Confirm it.",
        options: [
          { text: "Ja, halb zehn passt.", correct: true },
          { text: "Nein, zehn Uhr ist halb.", correct: false },
          { text: "Zusammen, bitte.", correct: false },
        ],
        why: "Say the time again. „Passt“ means it works for you.",
      },
    ],
  },
  {
    id: "friend",
    level: 3,
    title: "Coffee with a friend",
    deTitle: "Kaffee mit einer Freundin",
    place: "A message to a friend. You want to meet tomorrow, nothing fancy.",
    goal: "Suggest coffee and agree a place and a day.",
    canDo: "make a simple plan with a friend",
    register: "This one is „du“. With friends, „Sie“ sounds like a counter, not a person.",
    phrases: [
      {
        id: "friend-1",
        speaker: "You",
        kind: "say",
        de: "Hast du Lust auf einen Kaffee?",
        en: "Do you feel like a coffee?",
        tip: "„Lust auf“ is the friendly invitation. It is an offer, not a demand.",
      },
      {
        id: "friend-2",
        speaker: "You",
        kind: "say",
        de: "Heute oder morgen?",
        en: "Today or tomorrow?",
        tip: "Give two options. It is easier to answer than an open “when?”.",
      },
      {
        id: "friend-3",
        speaker: "Friend",
        kind: "hear",
        de: "Morgen passt besser.",
        en: "Tomorrow works better.",
        tip: "„Besser“ chooses one of your two options. Tomorrow it is.",
      },
      {
        id: "friend-4",
        speaker: "You",
        kind: "say",
        de: "Um vier am Bahnhof?",
        en: "At four, at the station?",
        tip: "Time plus place, as a question, so they can change one of them.",
      },
      {
        id: "friend-5",
        speaker: "You",
        kind: "say",
        de: "Perfekt, bis morgen.",
        en: "Perfect, see you tomorrow.",
        tip: "„Bis morgen“ closes the plan. You do not need a longer goodbye.",
      },
    ],
    checks: [
      {
        id: "friend-c1",
        phraseId: "friend-1",
        prompt: "You are texting a friend, not a clerk. Invite them for coffee.",
        options: [
          { text: "Hast du Lust auf einen Kaffee?", correct: true },
          { text: "Hätten Sie Lust auf einen Kaffee?", correct: false },
          { text: "Einen Kaffee zum Mitnehmen, bitte.", correct: false },
        ],
        why: "„Du“ is for the friend. „Sie“ would sound like you are serving them.",
      },
      {
        id: "friend-c2",
        phraseId: "friend-3",
        prompt: "They reply: „Morgen passt besser.“",
        options: [
          { text: "Tomorrow is the better day.", correct: true },
          { text: "This morning is already booked by them.", correct: false },
          { text: "They do not drink coffee.", correct: false },
        ],
        why: "„Morgen“ here means tomorrow, not morning. „Passt besser“ chooses that day.",
      },
      {
        id: "friend-c3",
        phraseId: "friend-5",
        prompt: "The plan is set. Close the chat.",
        options: [
          { text: "Perfekt, bis morgen.", correct: true },
          { text: "Bis zehn ist Ruhe.", correct: false },
          { text: "Mit Karte, bitte.", correct: false },
        ],
        why: "„Bis morgen“ is “see you tomorrow”. It ends the arrangement.",
      },
    ],
  },
  {
    id: "doctor",
    level: 3,
    title: "At the doctor",
    deTitle: "Beim Arzt",
    place: "A short appointment. Your throat has hurt since the day before yesterday. You need a sick note for work.",
    goal: "Describe the problem and ask for a sick note.",
    canDo: "describe a sore throat and ask for a sick note",
    register: "„Sie“ with the doctor. Symptoms first, the form second.",
    phrases: [
      {
        id: "doctor-1",
        speaker: "You",
        kind: "say",
        de: "Guten Tag. Ich bin seit zwei Tagen krank.",
        en: "Hello. I’ve been ill for two days.",
        tip: "„Seit“ plus a duration is how you say how long it has been going on.",
      },
      {
        id: "doctor-2",
        speaker: "Doctor",
        kind: "hear",
        de: "Was fehlt Ihnen?",
        en: "What’s the matter?",
        tip: "This is the doctor’s opening. Answer with the body part and what it does.",
        sound: "Was fehlt Ihnen? — “What is missing / what’s wrong?” It is the standard question.",
      },
      {
        id: "doctor-3",
        speaker: "You",
        kind: "say",
        de: "Der Hals tut weh, besonders beim Schlucken.",
        en: "My throat hurts, especially when I swallow.",
        tip: "„Tut weh“ is hurts. „Beim Schlucken“ pins it to a moment they can use.",
      },
      {
        id: "doctor-4",
        speaker: "Doctor",
        kind: "hear",
        de: "Fieber?",
        en: "A fever?",
        tip: "One word. Answer with yes or no, then stop. They will ask more if they need it.",
      },
      {
        id: "doctor-5",
        speaker: "You",
        kind: "say",
        de: "Nein. Ich brauche aber eine Krankmeldung.",
        en: "No. I do need a sick note, though.",
        tip: "„Krankmeldung“ is the note for your employer. „Aber“ brings it in after the no.",
        sound: "Krankmeldung sounds like KRANK-mel-doong.",
      },
    ],
    checks: [
      {
        id: "doctor-c1",
        phraseId: "doctor-2",
        prompt: "The doctor asks „Was fehlt Ihnen?“",
        options: [
          { text: "They want to know what is wrong.", correct: true },
          { text: "They want your insurance card only.", correct: false },
          { text: "They are asking you to come back in two days.", correct: false },
        ],
        why: "This question opens almost every appointment. Answer with the symptom.",
      },
      {
        id: "doctor-c2",
        phraseId: "doctor-3",
        prompt: "Your throat hurts when you swallow.",
        options: [
          { text: "Der Hals tut weh, besonders beim Schlucken.", correct: true },
          { text: "Der Hals ist seit zwei Euro krank.", correct: false },
          { text: "Ich nehme diese Packung.", correct: false },
        ],
        why: "Name the place („der Hals“) and the moment („beim Schlucken“).",
      },
      {
        id: "doctor-c3",
        phraseId: "doctor-5",
        prompt: "No fever, but you need the note for work.",
        options: [
          { text: "Nein. Ich brauche aber eine Krankmeldung.", correct: true },
          { text: "Ja, Fieber bis zehn.", correct: false },
          { text: "Halb zehn passt.", correct: false },
        ],
        why: "Answer „Fieber?“ first. Then „Krankmeldung“ is the form your job expects.",
      },
    ],
  },
  {
    id: "train",
    level: 3,
    title: "The train is late",
    deTitle: "Der Zug hat Verspätung",
    place: "The board has changed. You have a connection and you need a person, not the app.",
    goal: "Ask about the delay, the platform, and your connection.",
    canDo: "ask about a delay and a connection",
    register: "„Sie“ at the information desk. Ask one fact at a time.",
    phrases: [
      {
        id: "train-1",
        speaker: "You",
        kind: "say",
        de: "Entschuldigung, hat der Zug nach Hamburg Verspätung?",
        en: "Excuse me, is the train to Hamburg delayed?",
        tip: "Name the destination so they know which train. „Verspätung“ is the delay.",
        sound: "Verspätung sounds like fer-SHPAY-toong.",
      },
      {
        id: "train-2",
        speaker: "Staff",
        kind: "hear",
        de: "Ja, ungefähr fünfzehn Minuten.",
        en: "Yes, about fifteen minutes.",
        tip: "„Ungefähr“ means roughly. Fifteen minutes may still leave you the connection — ask.",
      },
      {
        id: "train-3",
        speaker: "You",
        kind: "say",
        de: "Von welchem Gleis fährt er?",
        en: "Which platform does it leave from?",
        tip: "Platforms change when trains are late. „Gleis“ is the track or platform.",
      },
      {
        id: "train-4",
        speaker: "Staff",
        kind: "hear",
        de: "Heute von Gleis zwölf.",
        en: "Today from platform twelve.",
        tip: "„Heute“ is doing real work: the usual platform is different today.",
      },
      {
        id: "train-5",
        speaker: "You",
        kind: "say",
        de: "Schaffe ich den Anschluss noch?",
        en: "Will I still make the connection?",
        tip: "„Schaffen“ here means manage in time. „Der Anschluss“ is the train you change onto.",
      },
    ],
    checks: [
      {
        id: "train-c1",
        phraseId: "train-1",
        prompt: "You think the Hamburg train is late. Ask.",
        options: [
          { text: "Hat der Zug nach Hamburg Verspätung?", correct: true },
          { text: "Hat der Zug nach Hamburg Feierabend?", correct: false },
          { text: "Ist Hamburg eine Tageskarte?", correct: false },
        ],
        why: "„Verspätung“ is the word on the board and at the desk.",
      },
      {
        id: "train-c2",
        phraseId: "train-4",
        prompt: "They say „Heute von Gleis zwölf.“",
        options: [
          { text: "Today it leaves from platform 12, which may not be the usual one.", correct: true },
          { text: "The train is cancelled for twelve days.", correct: false },
          { text: "You already missed it by twelve minutes.", correct: false },
        ],
        why: "„Gleis“ is the platform. „Heute“ tells you not to trust the printed plan.",
      },
      {
        id: "train-c3",
        phraseId: "train-5",
        prompt: "You need to know if the connecting train is still possible.",
        options: [
          { text: "Schaffe ich den Anschluss noch?", correct: true },
          { text: "Muss ich eine Tüte umsteigen?", correct: false },
          { text: "Von welchem Kaffee fährt er?", correct: false },
        ],
        why: "„Den Anschluss schaffen“ means make the connection. „Noch“ asks if there is still time.",
      },
    ],
  },
  {
    id: "package",
    level: 3,
    title: "The parcel did not come",
    deTitle: "Das Paket ist nicht da",
    place: "You are on the phone with the delivery company. You were home. The parcel was not.",
    goal: "Say it did not arrive, and give a time when you will be in.",
    canDo: "sort out a missed delivery on the phone",
    register: "„Sie“ on a service line. Have the tracking number in your hand before you call.",
    phrases: [
      {
        id: "package-1",
        speaker: "You",
        kind: "say",
        de: "Guten Tag, mein Paket ist nicht angekommen.",
        en: "Hello, my parcel hasn’t arrived.",
        tip: "Start with the problem in one line. They will ask for the number next.",
      },
      {
        id: "package-2",
        speaker: "Staff",
        kind: "hear",
        de: "Haben Sie eine Sendungsnummer?",
        en: "Do you have a tracking number?",
        tip: "„Sendungsnummer“ is the tracking number. Read it slowly, in groups.",
        sound: "Sendungsnummer sounds like ZEN-doongs-noom-er.",
      },
      {
        id: "package-3",
        speaker: "You",
        kind: "say",
        de: "Ja, einen Moment, ich habe sie hier.",
        en: "Yes, one moment, I have it here.",
        tip: "„Sie“ means the number (die Nummer). This line buys you three quiet seconds.",
      },
      {
        id: "package-4",
        speaker: "Staff",
        kind: "hear",
        de: "Wir stellen es morgen noch einmal zu.",
        en: "We’ll try to deliver it again tomorrow.",
        tip: "„Zustellen“ is what the carrier does. Pin down a time or you may miss it again.",
      },
      {
        id: "package-5",
        speaker: "You",
        kind: "say",
        de: "Nach vier Uhr bin ich zu Hause. Können Sie das notieren?",
        en: "I’ll be home after four. Can you note that?",
        tip: "„Notieren“ means write it down. A clock time is more useful than “afternoon”.",
      },
    ],
    checks: [
      {
        id: "package-c1",
        phraseId: "package-1",
        prompt: "Open the call. The parcel never came.",
        options: [
          { text: "Mein Paket ist nicht angekommen.", correct: true },
          { text: "Mein Paket hat Verspätung zum Mitnehmen.", correct: false },
          { text: "Ich stelle das Paket zu.", correct: false },
        ],
        why: "„Nicht angekommen“ is the customer’s sentence. „Zustellen“ is their job, not yours.",
      },
      {
        id: "package-c2",
        phraseId: "package-2",
        prompt: "They ask for the „Sendungsnummer“.",
        options: [
          { text: "They want the tracking number.", correct: true },
          { text: "They want your door code only.", correct: false },
          { text: "They are telling you the parcel was delivered.", correct: false },
        ],
        why: "Have that number visible before you call. The rest of the call depends on it.",
      },
      {
        id: "package-c3",
        phraseId: "package-5",
        prompt: "You will be home after 4, and you want that written down.",
        options: [
          { text: "Nach vier Uhr bin ich zu Hause. Können Sie das notieren?", correct: true },
          { text: "Vor vier Uhr ist die Sendung eine Tüte.", correct: false },
          { text: "Halb vier passt nicht zur Kasse.", correct: false },
        ],
        why: "Give the time and ask them to note it. „Nach vier“ means after four, not before.",
      },
    ],
  },
  {
    id: "mixup",
    level: 4,
    title: "The wrong drink",
    deTitle: "Der falsche Kaffee",
    place: "The cup in front of you is coffee. You ordered tea. The place is full, and you want it fixed without a scene.",
    goal: "Correct the order calmly and let them redo it.",
    canDo: "correct a wrong order without raising your voice",
    register: "„Sie“ with staff. State the fact, then the request. No speech about your day.",
    phrases: [
      {
        id: "mixup-1",
        speaker: "You",
        kind: "say",
        de: "Entschuldigung, ich habe einen Tee bestellt, keinen Kaffee.",
        en: "Sorry, I ordered a tea, not a coffee.",
        tip: "Fact, then the contrast: „einen Tee … keinen Kaffee“. „Keinen“ because Kaffee is masculine.",
      },
      {
        id: "mixup-2",
        speaker: "Staff",
        kind: "hear",
        de: "Oh, das tut mir leid.",
        en: "Oh, I’m sorry.",
        tip: "They have accepted it. You do not need to prove you are right. Ask for the swap.",
      },
      {
        id: "mixup-3",
        speaker: "You",
        kind: "say",
        de: "Können Sie den bitte tauschen?",
        en: "Could you swap this one, please?",
        tip: "„Den“ is the drink in front of you. „Tauschen“ is the polite operational verb.",
      },
      {
        id: "mixup-4",
        speaker: "Staff",
        kind: "hear",
        de: "Ja, klar. Einen Moment.",
        en: "Yes, of course. One moment.",
        tip: "It is handled. „Einen Moment“ means wait here, they are doing it.",
      },
      {
        id: "mixup-5",
        speaker: "You",
        kind: "say",
        de: "Danke, alles gut.",
        en: "Thanks, we’re fine.",
        tip: "„Alles gut“ closes it warmly. The mistake does not need a second paragraph.",
      },
    ],
    checks: [
      {
        id: "mixup-c1",
        phraseId: "mixup-1",
        prompt: "You ordered tea and received coffee. Say it in one calm line.",
        options: [
          { text: "Ich habe einen Tee bestellt, keinen Kaffee.", correct: true },
          { text: "Ich will keinen Moment bestellen.", correct: false },
          { text: "Der Kaffee ist seit zwei Tagen krank.", correct: false },
        ],
        why: "Name what you ordered, then „keinen“ plus what you got.",
      },
      {
        id: "mixup-c2",
        phraseId: "mixup-3",
        prompt: "You want them to replace the cup, not apologize again.",
        options: [
          { text: "Können Sie den bitte tauschen?", correct: true },
          { text: "Können Sie den bitte notieren?", correct: false },
          { text: "Schaffe ich den Kaffee noch?", correct: false },
        ],
        why: "„Tauschen“ asks for a swap. „Notieren“ would ask them to write something down.",
      },
      {
        id: "mixup-c3",
        phraseId: "mixup-5",
        prompt: "The new drink is coming. End it kindly.",
        options: [
          { text: "Danke, alles gut.", correct: true },
          { text: "Das macht mir leid, getrennt.", correct: false },
          { text: "Bis zehn ist der Kaffee Ruhe.", correct: false },
        ],
        why: "„Alles gut“ tells them the matter is finished.",
      },
    ],
  },
  {
    id: "weekend",
    level: 4,
    title: "Saturday evening",
    deTitle: "Samstagabend",
    place: "You are making a real plan with a friend: dinner out, not too late.",
    goal: "Suggest dinner and set 7:30.",
    canDo: "set an evening plan, including a half-hour time",
    register: "„Du“. Suggest, then let them narrow it. Repeat the time you agree.",
    phrases: [
      {
        id: "weekend-1",
        speaker: "You",
        kind: "say",
        de: "Hast du am Samstag schon was vor?",
        en: "Do you already have plans on Saturday?",
        tip: "„Was vorhaben“ means to have plans. It leaves them an easy no.",
      },
      {
        id: "weekend-2",
        speaker: "Friend",
        kind: "hear",
        de: "Noch nicht. Woran denkst du?",
        en: "Not yet. What are you thinking?",
        tip: "The day is open. They are asking for your idea, not for a restaurant essay.",
      },
      {
        id: "weekend-3",
        speaker: "You",
        kind: "say",
        de: "Wollen wir abends was essen gehen?",
        en: "Want to go out for dinner?",
        tip: "„Was essen gehen“ is eating out. „Abends“ keeps the time of day loose for one more line.",
      },
      {
        id: "weekend-4",
        speaker: "Friend",
        kind: "hear",
        de: "Gerne. Lieber nicht zu spät.",
        en: "Yes. Preferably not too late.",
        tip: "„Lieber“ is a soft preference. Offer a time that respects it.",
      },
      {
        id: "weekend-5",
        speaker: "You",
        kind: "say",
        de: "Dann halb acht. Ich reserviere uns was.",
        en: "Then 7:30. I’ll reserve us something.",
        tip: "„Halb acht“ is 7:30. „Ich reserviere“ means you are taking the booking.",
        sound: "Halb acht is 7:30 — thirty minutes before eight.",
      },
    ],
    checks: [
      {
        id: "weekend-c1",
        phraseId: "weekend-1",
        prompt: "Check whether Saturday is free before you propose a place.",
        options: [
          { text: "Hast du am Samstag schon was vor?", correct: true },
          { text: "Haben Sie am Samstag reserviert?", correct: false },
          { text: "Samstag ist eine Einzelfahrt.", correct: false },
        ],
        why: "„Was vorhaben“ asks about plans. „Du“ fits a friend.",
      },
      {
        id: "weekend-c2",
        phraseId: "weekend-4",
        prompt: "They say „Lieber nicht zu spät.“",
        options: [
          { text: "They want the evening to start early enough.", correct: true },
          { text: "They cannot come on Saturday.", correct: false },
          { text: "They want you to choose the most expensive place.", correct: false },
        ],
        why: "„Lieber“ softens it. Answer with an early-evening time, not a new topic.",
      },
      {
        id: "weekend-c3",
        phraseId: "weekend-5",
        prompt: "You suggest 7:30 and you will book.",
        options: [
          { text: "Dann halb acht. Ich reserviere uns was.", correct: true },
          { text: "Dann halb neun. Du reservierst uns was.", correct: false },
          { text: "Dann um acht Uhr halb.", correct: false },
        ],
        why: "Halb acht is 7:30. Saying „ich reserviere“ tells them the booking is yours.",
      },
    ],
  },
  {
    id: "decline",
    level: 4,
    title: "Saying no to an invitation",
    deTitle: "Eine Einladung absagen",
    place: "A friend invited you this week. You cannot go. You want to stay friends with the plan.",
    goal: "Decline clearly and leave next week open.",
    canDo: "turn down an invitation and keep the door open",
    register: "„Du“. Thank them first. The no is about the week, not about them.",
    phrases: [
      {
        id: "decline-1",
        speaker: "You",
        kind: "say",
        de: "Danke für die Einladung.",
        en: "Thanks for the invitation.",
        tip: "Start with the thanks. The no lands more cleanly after it.",
      },
      {
        id: "decline-2",
        speaker: "You",
        kind: "say",
        de: "Diese Woche schaffe ich es leider nicht.",
        en: "I can’t manage it this week, unfortunately.",
        tip: "„Schaffen“ is about your time, not their idea. „Leider“ is enough regret.",
      },
      {
        id: "decline-3",
        speaker: "Friend",
        kind: "hear",
        de: "Schade. Nächste Woche?",
        en: "Shame. Next week?",
        tip: "They are offering another slot, not arguing. You can accept that offer.",
      },
      {
        id: "decline-4",
        speaker: "You",
        kind: "say",
        de: "Nächste Woche sehr gern.",
        en: "Next week, I’d really like to.",
        tip: "„Sehr gern“ is a warm yes to the new week. It replaces the no.",
      },
      {
        id: "decline-5",
        speaker: "You",
        kind: "say",
        de: "Meld dich einfach.",
        en: "Just get in touch.",
        tip: "Short for „meld dich bei mir“. With friends, this leaves the plan in their hands.",
      },
    ],
    checks: [
      {
        id: "decline-c1",
        phraseId: "decline-2",
        prompt: "You cannot do this week. Say that without rejecting them.",
        options: [
          { text: "Diese Woche schaffe ich es leider nicht.", correct: true },
          { text: "Diese Woche ist deine Einladung falsch.", correct: false },
          { text: "Ich habe dich nicht bestellt.", correct: false },
        ],
        why: "The limit is „diese Woche“, and „leider“ keeps it kind.",
      },
      {
        id: "decline-c2",
        phraseId: "decline-3",
        prompt: "They say „Schade. Nächste Woche?“",
        options: [
          { text: "They are disappointed, and they are offering next week.", correct: true },
          { text: "They are cancelling the friendship.", correct: false },
          { text: "They are asking for a tracking number.", correct: false },
        ],
        why: "„Schade“ is “that’s a shame”. The question after it is a new invitation.",
      },
      {
        id: "decline-c3",
        phraseId: "decline-5",
        prompt: "Next week works. Let them write you.",
        options: [
          { text: "Nächste Woche sehr gern. Meld dich einfach.", correct: true },
          { text: "Diese Woche leider sehr gern.", correct: false },
          { text: "Meld dich an der Kasse.", correct: false },
        ],
        why: "Yes to next week, then „meld dich“ so they pick the moment.",
      },
    ],
  },
  {
    id: "toilet",
    level: 1,
    title: "Where is the toilet?",
    deTitle: "Wo ist die Toilette?",
    place: "You are in a café and you need the toilet before you order.",
    goal: "Ask where it is, and check you heard the direction.",
    canDo: "ask where the toilet is",
    register: "„Entschuldigung“ first. Then one short question.",
    phrases: [
      {
        id: "toilet-1",
        speaker: "You",
        kind: "say",
        de: "Entschuldigung, wo ist die Toilette?",
        en: "Excuse me, where is the toilet?",
        tip: "This is the normal question. „Wo ist …?“ works for the exit, the till, or the platform too.",
        sound: "Entschuldigung sounds like ent-SHOOL-di-goong.",
      },
      {
        id: "toilet-2",
        speaker: "Staff",
        kind: "hear",
        de: "Hinten rechts.",
        en: "At the back, on the right.",
        tip: "„Hinten“ is at the back. „Rechts“ is right. „Links“ would be left.",
      },
      {
        id: "toilet-3",
        speaker: "You",
        kind: "say",
        de: "Geradeaus und dann rechts?",
        en: "Straight ahead and then right?",
        tip: "Repeat the direction back. If you heard it wrong, they will correct you.",
      },
      {
        id: "toilet-4",
        speaker: "Staff",
        kind: "hear",
        de: "Ja, neben der Küche.",
        en: "Yes, next to the kitchen.",
        tip: "„Neben“ means next to. The kitchen is your landmark.",
      },
      {
        id: "toilet-5",
        speaker: "You",
        kind: "say",
        de: "Danke schön.",
        en: "Thank you.",
        tip: "„Danke schön“ is a little warmer than a bare „danke“. Then you go.",
      },
    ],
    checks: [
      {
        id: "toilet-c1",
        phraseId: "toilet-1",
        prompt: "You need the toilet. What do you ask?",
        options: [
          { text: "Entschuldigung, wo ist die Toilette?", correct: true },
          { text: "Entschuldigung, wer ist die Toilette?", correct: false },
          { text: "Die Toilette ist bitte teuer.", correct: false },
        ],
        why: "„Wo ist …?“ asks where something is. „Wer“ would ask who.",
      },
      {
        id: "toilet-c2",
        phraseId: "toilet-2",
        prompt: "They say „Hinten rechts.“",
        options: [
          { text: "At the back, on the right.", correct: true },
          { text: "Upstairs, on the left.", correct: false },
          { text: "The toilet is closed today.", correct: false },
        ],
        why: "„Hinten“ is towards the back of the room. „Rechts“ is right.",
      },
      {
        id: "toilet-c3",
        phraseId: "toilet-4",
        prompt: "They add „Neben der Küche.“",
        options: [
          { text: "It is next to the kitchen.", correct: true },
          { text: "It is inside the kitchen.", correct: false },
          { text: "You have to ask the kitchen for a key.", correct: false },
        ],
        why: "„Neben“ means beside, not inside.",
      },
    ],
  },
  {
    id: "kiosk",
    level: 1,
    title: "A bottle of water",
    deTitle: "Eine Flasche Wasser",
    place: "A kiosk on the platform. You want water, and the train is soon.",
    goal: "Ask for still water and close the purchase.",
    canDo: "buy still water at a kiosk",
    register: "Keep it to the bottle and the answer. No story about the train.",
    phrases: [
      {
        id: "kiosk-1",
        speaker: "You",
        kind: "say",
        de: "Eine Flasche Wasser, bitte.",
        en: "A bottle of water, please.",
        tip: "Name the thing and the size in the first sentence. „Flasche“ is the bottle.",
      },
      {
        id: "kiosk-2",
        speaker: "Staff",
        kind: "hear",
        de: "Mit oder ohne Kohlensäure?",
        en: "Sparkling or still?",
        tip: "„Mit Kohlensäure“ is sparkling. „Ohne“ is still. You will hear this almost every time.",
        sound: "Kohlensäure sounds like KOH-len-zoy-reh.",
      },
      {
        id: "kiosk-3",
        speaker: "You",
        kind: "say",
        de: "Ohne, bitte.",
        en: "Still, please.",
        tip: "„Ohne“ answers their question. You do not need to repeat the whole word.",
      },
      {
        id: "kiosk-4",
        speaker: "Staff",
        kind: "hear",
        de: "Sonst noch etwas?",
        en: "Anything else?",
        tip: "Same question as at the bakery. One more item, or you close it.",
      },
      {
        id: "kiosk-5",
        speaker: "You",
        kind: "say",
        de: "Nein, danke. Das war's.",
        en: "No, thanks. That's all.",
        tip: "„Das war's“ ends the sale. It is short for „das war es“.",
      },
    ],
    checks: [
      {
        id: "kiosk-c1",
        phraseId: "kiosk-1",
        prompt: "You want one bottle of water.",
        options: [
          { text: "Eine Flasche Wasser, bitte.", correct: true },
          { text: "Ein Wasser Flasche bitte ohne.", correct: false },
          { text: "Wasser ist eine Toilette.", correct: false },
        ],
        why: "„Eine Flasche“ plus what is in it. That is the whole order.",
      },
      {
        id: "kiosk-c2",
        phraseId: "kiosk-2",
        prompt: "They ask „Mit oder ohne Kohlensäure?“ You want still water.",
        options: [
          { text: "Ohne, bitte.", correct: true },
          { text: "Mit, bitte.", correct: false },
          { text: "Hinten rechts.", correct: false },
        ],
        why: "„Ohne“ means without sparkling. „Mit“ would be fizzy.",
      },
      {
        id: "kiosk-c3",
        phraseId: "kiosk-5",
        prompt: "You do not want anything else.",
        options: [
          { text: "Nein, danke. Das war's.", correct: true },
          { text: "Ja, noch eine Küche.", correct: false },
          { text: "Sonst noch etwas?", correct: false },
        ],
        why: "„Das war's“ tells them the order is finished.",
      },
    ],
  },
  {
    id: "way",
    level: 2,
    title: "The way to the pharmacy",
    deTitle: "Der Weg zur Apotheke",
    place: "You are on the pavement. You can see a person with a minute to spare.",
    goal: "Ask the way, and catch whether it is walkable.",
    canDo: "ask for walking directions",
    register: "„Sie“ with a stranger. One question, then let them answer.",
    phrases: [
      {
        id: "way-1",
        speaker: "You",
        kind: "say",
        de: "Entschuldigung, wie komme ich zur Apotheke?",
        en: "Excuse me, how do I get to the pharmacy?",
        tip: "„Wie komme ich zu …?“ is the sentence for any place you can walk to.",
      },
      {
        id: "way-2",
        speaker: "Stranger",
        kind: "hear",
        de: "Zu Fuß sind es fünf Minuten.",
        en: "On foot it is five minutes.",
        tip: "„Zu Fuß“ means walking. Five minutes means you do not need a bus.",
      },
      {
        id: "way-3",
        speaker: "You",
        kind: "say",
        de: "Ist das weit?",
        en: "Is that far?",
        tip: "A useful check when you are tired or carrying bags. They already said five minutes.",
      },
      {
        id: "way-4",
        speaker: "Stranger",
        kind: "hear",
        de: "Nein. Die nächste Straße links.",
        en: "No. The next street on the left.",
        tip: "„Die nächste“ is the next one. „Links“ is left.",
      },
      {
        id: "way-5",
        speaker: "You",
        kind: "say",
        de: "Vielen Dank für die Hilfe.",
        en: "Thank you very much for the help.",
        tip: "A full thank-you fits a stranger who stopped for you. Then you walk.",
      },
    ],
    checks: [
      {
        id: "way-c1",
        phraseId: "way-1",
        prompt: "You need the pharmacy and you are on foot.",
        options: [
          { text: "Wie komme ich zur Apotheke?", correct: true },
          { text: "Wo ist die Flasche Wasser?", correct: false },
          { text: "Die Apotheke kommt mich.", correct: false },
        ],
        why: "„Wie komme ich zu …?“ asks for the way, not only the place name.",
      },
      {
        id: "way-c2",
        phraseId: "way-2",
        prompt: "They say „Zu Fuß sind es fünf Minuten.“",
        options: [
          { text: "Walking there takes about five minutes.", correct: true },
          { text: "The pharmacy closes in five minutes.", correct: false },
          { text: "You need bus line five.", correct: false },
        ],
        why: "„Zu Fuß“ is on foot. The number is the walking time.",
      },
      {
        id: "way-c3",
        phraseId: "way-4",
        prompt: "Which way do they send you?",
        options: [
          { text: "The next street on the left.", correct: true },
          { text: "The next street on the right, then straight for a kilometer.", correct: false },
          { text: "Back to the station.", correct: false },
        ],
        why: "„Die nächste Straße links“ is one turn: the next street, left.",
      },
    ],
  },
  {
    id: "hours",
    level: 2,
    title: "Are you still open?",
    deTitle: "Haben Sie noch offen?",
    place: "You are at a shop door in the evening. The lights are on. You are not sure.",
    goal: "Ask if they are open now, and when they open tomorrow.",
    canDo: "ask about opening hours",
    register: "„Sie“ at the door. Today first, tomorrow second.",
    phrases: [
      {
        id: "hours-1",
        speaker: "You",
        kind: "say",
        de: "Entschuldigung, haben Sie noch offen?",
        en: "Excuse me, are you still open?",
        tip: "This is the ordinary evening question. „Noch“ means still, at this hour.",
      },
      {
        id: "hours-2",
        speaker: "Staff",
        kind: "hear",
        de: "Wir schließen um acht.",
        en: "We close at eight.",
        tip: "„Schließen“ is close for the day. Eight means you still have a little time.",
      },
      {
        id: "hours-3",
        speaker: "You",
        kind: "say",
        de: "Und morgen?",
        en: "And tomorrow?",
        tip: "Two words are enough. They know you mean the hours.",
      },
      {
        id: "hours-4",
        speaker: "Staff",
        kind: "hear",
        de: "Morgen ab neun.",
        en: "Tomorrow from nine.",
        tip: "„Ab neun“ means starting at nine, not until nine.",
      },
      {
        id: "hours-5",
        speaker: "You",
        kind: "say",
        de: "Gut, dann komme ich morgen früh.",
        en: "Good, then I'll come tomorrow morning.",
        tip: "„Morgen früh“ is tomorrow morning. You have told them you will be back.",
      },
    ],
    checks: [
      {
        id: "hours-c1",
        phraseId: "hours-1",
        prompt: "It is evening and you are at the door.",
        options: [
          { text: "Haben Sie noch offen?", correct: true },
          { text: "Haben Sie noch Kohlensäure?", correct: false },
          { text: "Schließen Sie mich um acht?", correct: false },
        ],
        why: "„Noch offen“ asks if the shop is still open.",
      },
      {
        id: "hours-c2",
        phraseId: "hours-2",
        prompt: "They say „Wir schließen um acht.“",
        options: [
          { text: "They close at 8.", correct: true },
          { text: "They open at 8.", correct: false },
          { text: "Eight people are still inside.", correct: false },
        ],
        why: "„Schließen“ is closing time. „Ab“ would be the opening time.",
      },
      {
        id: "hours-c3",
        phraseId: "hours-4",
        prompt: "„Morgen ab neun.“ What does that mean?",
        options: [
          { text: "Tomorrow they are open from 9.", correct: true },
          { text: "Tomorrow they close at 9.", correct: false },
          { text: "You should come back in nine days.", correct: false },
        ],
        why: "„Ab“ plus a time means from that time onward.",
      },
    ],
  },
  {
    id: "feierabend",
    level: 3,
    title: "Leaving work",
    deTitle: "Feierabend",
    place: "The end of the day in the office kitchen. A colleague is still there.",
    goal: "Say you are leaving, and answer the goodbye.",
    canDo: "leave work and wish someone a good evening",
    register: "This colleague uses „du“. „Feierabend“ is the word for the end of the working day.",
    phrases: [
      {
        id: "feierabend-1",
        speaker: "You",
        kind: "say",
        de: "Ich mach dann Schluss für heute.",
        en: "I'll finish for today, then.",
        tip: "Spoken German often drops the -e: „ich mach“. The full form is „ich mache“.",
      },
      {
        id: "feierabend-2",
        speaker: "Colleague",
        kind: "hear",
        de: "Schon?",
        en: "Already?",
        tip: "One word of surprise, not a complaint. You can give a short reason.",
      },
      {
        id: "feierabend-3",
        speaker: "You",
        kind: "say",
        de: "Ja, ich habe noch einen Termin.",
        en: "Yes, I still have an appointment.",
        tip: "„Noch“ here means still on your list. One reason is enough.",
      },
      {
        id: "feierabend-4",
        speaker: "Colleague",
        kind: "hear",
        de: "Alles klar. Schönen Feierabend!",
        en: "All right. Have a good evening!",
        tip: "„Schönen Feierabend“ is what people say when you leave work. You will hear it every day.",
        sound: "Feierabend sounds like FY-er-ah-bent.",
      },
      {
        id: "feierabend-5",
        speaker: "You",
        kind: "say",
        de: "Danke, bis morgen.",
        en: "Thanks, see you tomorrow.",
        tip: "Wish it back with „danke“, then „bis morgen“ if you will see them next day.",
      },
    ],
    checks: [
      {
        id: "feierabend-c1",
        phraseId: "feierabend-1",
        prompt: "You are done for the day. Tell a colleague.",
        options: [
          { text: "Ich mach dann Schluss für heute.", correct: true },
          { text: "Ich schließe den Laden um acht.", correct: false },
          { text: "Haben Sie noch offen?", correct: false },
        ],
        why: "„Schluss für heute“ means you are stopping work today.",
      },
      {
        id: "feierabend-c2",
        phraseId: "feierabend-4",
        prompt: "They say „Schönen Feierabend!“",
        options: [
          { text: "They are wishing you a good end of the working day.", correct: true },
          { text: "They are asking you to stay and close the office.", correct: false },
          { text: "They are telling you the shop opens at nine.", correct: false },
        ],
        why: "„Feierabend“ is the moment work is over. The wish is friendly and ordinary.",
      },
      {
        id: "feierabend-c3",
        phraseId: "feierabend-5",
        prompt: "You will see them tomorrow. Answer the goodbye.",
        options: [
          { text: "Danke, bis morgen.", correct: true },
          { text: "Danke, neben der Küche.", correct: false },
          { text: "Schon? Ich komme zu Fuß.", correct: false },
        ],
        why: "„Bis morgen“ closes it. „Danke“ answers their wish.",
      },
    ],
  },
  {
    id: "door",
    level: 3,
    title: "The door does not close",
    deTitle: "Die Tür schließt nicht",
    place: "You phone the building caretaker. The flat door does not shut properly.",
    goal: "Describe the problem and agree a time.",
    canDo: "report a door problem and agree a time",
    register: "„Sie“ with the caretaker. Problem first, time second.",
    phrases: [
      {
        id: "door-1",
        speaker: "You",
        kind: "say",
        de: "Guten Tag, die Wohnungstür schließt nicht richtig.",
        en: "Hello, the flat door doesn't close properly.",
        tip: "Lead with the thing and what it fails to do. „Richtig“ means properly.",
      },
      {
        id: "door-2",
        speaker: "Caretaker",
        kind: "hear",
        de: "Seit wann?",
        en: "Since when?",
        tip: "They want the start, not the whole story. A time of day is enough.",
      },
      {
        id: "door-3",
        speaker: "You",
        kind: "say",
        de: "Seit heute Morgen.",
        en: "Since this morning.",
        tip: "„Seit“ plus when it began. „Heute Morgen“ is this morning.",
      },
      {
        id: "door-4",
        speaker: "Caretaker",
        kind: "hear",
        de: "Ich kann gegen fünf vorbeikommen.",
        en: "I can come by around five.",
        tip: "„Gegen fünf“ is around five, not exactly five. „Vorbeikommen“ means stop by.",
        sound: "Gegen fünf is about 5:00, with a little room on either side.",
      },
      {
        id: "door-5",
        speaker: "You",
        kind: "say",
        de: "Gegen fünf bin ich da. Danke.",
        en: "I'll be there around five. Thanks.",
        tip: "Repeat „gegen fünf“ so you both mean the same window of time.",
      },
    ],
    checks: [
      {
        id: "door-c1",
        phraseId: "door-1",
        prompt: "The flat door will not shut. Say that first.",
        options: [
          { text: "Die Wohnungstür schließt nicht richtig.", correct: true },
          { text: "Die Wohnungstür ist seit fünf offen im Laden.", correct: false },
          { text: "Ich mach dann Schluss für die Tür.", correct: false },
        ],
        why: "Name the door and the problem: it does not close properly.",
      },
      {
        id: "door-c2",
        phraseId: "door-4",
        prompt: "They say „Gegen fünf.“",
        options: [
          { text: "Around five o'clock.", correct: true },
          { text: "Exactly five minutes.", correct: false },
          { text: "Not until the fifth of the month.", correct: false },
        ],
        why: "„Gegen“ plus a clock time means around that hour.",
      },
      {
        id: "door-c3",
        phraseId: "door-5",
        prompt: "You can be home for that visit. Confirm it.",
        options: [
          { text: "Gegen fünf bin ich da.", correct: true },
          { text: "Gegen fünf schließt der Laden.", correct: false },
          { text: "Seit fünf bin ich zu Fuß.", correct: false },
        ],
        why: "„Bin ich da“ means you will be there. Repeat their time.",
      },
    ],
  },
  {
    id: "again",
    level: 3,
    title: "Could you repeat that?",
    deTitle: "Können Sie das wiederholen?",
    place: "A clinic desk, on the phone. They spoke quickly and you lost the time.",
    goal: "Ask them to repeat it more slowly, then say the time back.",
    canDo: "ask someone to repeat and slow down",
    register: "„Sie“ on the phone. Asking them to repeat is ordinary, not rude.",
    phrases: [
      {
        id: "again-1",
        speaker: "You",
        kind: "say",
        de: "Können Sie das bitte wiederholen?",
        en: "Could you repeat that, please?",
        tip: "Use this the moment you lose the sentence. People expect it.",
      },
      {
        id: "again-2",
        speaker: "Staff",
        kind: "hear",
        de: "Natürlich. Langsamer?",
        en: "Of course. Slower?",
        tip: "They are offering a slower pace. Say yes.",
      },
      {
        id: "again-3",
        speaker: "You",
        kind: "say",
        de: "Ja, etwas langsamer, bitte.",
        en: "Yes, a bit slower, please.",
        tip: "„Etwas langsamer“ is polite and precise. You are not asking them to stop.",
      },
      {
        id: "again-4",
        speaker: "Staff",
        kind: "hear",
        de: "Der Termin ist am Montag um elf.",
        en: "The appointment is on Monday at eleven.",
        tip: "Day plus „um“ plus the hour. This is the part to repeat back.",
      },
      {
        id: "again-5",
        speaker: "You",
        kind: "say",
        de: "Am Montag um elf. Danke, jetzt habe ich es.",
        en: "Monday at eleven. Thanks, I've got it now.",
        tip: "Say the fact back. „Jetzt habe ich es“ tells them they can stop repeating.",
      },
    ],
    checks: [
      {
        id: "again-c1",
        phraseId: "again-1",
        prompt: "You did not catch what they said.",
        options: [
          { text: "Können Sie das bitte wiederholen?", correct: true },
          { text: "Können Sie das bitte schließen?", correct: false },
          { text: "Wiederholen Sie mich um elf?", correct: false },
        ],
        why: "„Wiederholen“ means say it again. It is a normal request.",
      },
      {
        id: "again-c2",
        phraseId: "again-3",
        prompt: "They offer to go slower. Accept.",
        options: [
          { text: "Ja, etwas langsamer, bitte.", correct: true },
          { text: "Nein, etwas lauter nach zehn.", correct: false },
          { text: "Montag ist langsamer.", correct: false },
        ],
        why: "„Etwas langsamer“ is the pace you need. „Ja“ accepts their offer.",
      },
      {
        id: "again-c3",
        phraseId: "again-5",
        prompt: "The appointment is Monday at 11. Show you heard it.",
        options: [
          { text: "Am Montag um elf. Jetzt habe ich es.", correct: true },
          { text: "Am elf um Montag. Ich wiederhole Sie.", correct: false },
          { text: "Gegen elf schließt die Tür.", correct: false },
        ],
        why: "Repeat the day and the hour. „Jetzt habe ich es“ ends the repetition.",
      },
    ],
  },
  {
    id: "late",
    level: 3,
    title: "Running late",
    deTitle: "Ich komme später",
    place: "You are on the platform. The train is late, and someone is waiting for you.",
    goal: "Say you will be ten minutes late, and why.",
    canDo: "say you are late and give the reason",
    register: "„Sie“, because this is a desk or a person you do not know well. Lead with the apology and the number of minutes.",
    phrases: [
      {
        id: "late-1",
        speaker: "You",
        kind: "say",
        de: "Es tut mir leid, ich komme zehn Minuten später.",
        en: "I'm sorry, I'll be ten minutes late.",
        tip: "Minutes first. „Später“ without a number is vague. Ten minutes is a fact they can use.",
      },
      {
        id: "late-2",
        speaker: "Staff",
        kind: "hear",
        de: "Kein Problem. Wir warten.",
        en: "No problem. We'll wait.",
        tip: "You are not in trouble. They have agreed to wait.",
      },
      {
        id: "late-3",
        speaker: "You",
        kind: "say",
        de: "Die Bahn hat Verspätung.",
        en: "The train is delayed.",
        tip: "One reason. „Die Bahn“ is the train or the railway. You do not need the whole journey.",
      },
      {
        id: "late-4",
        speaker: "Staff",
        kind: "hear",
        de: "Dann bis gleich.",
        en: "See you in a moment, then.",
        tip: "„Bis gleich“ means soon, not tomorrow. They expect you shortly.",
      },
      {
        id: "late-5",
        speaker: "You",
        kind: "say",
        de: "Danke für Ihr Verständnis.",
        en: "Thank you for understanding.",
        tip: "„Ihr“ is the formal your. This thanks them for being flexible.",
      },
    ],
    checks: [
      {
        id: "late-c1",
        phraseId: "late-1",
        prompt: "You will arrive ten minutes late. Send that.",
        options: [
          { text: "Es tut mir leid, ich komme zehn Minuten später.", correct: true },
          { text: "Es tut mir leid, ich komme zehn Minuten früher.", correct: false },
          { text: "Zehn Minuten sind die Bahn zu.", correct: false },
        ],
        why: "„Später“ is late. „Früher“ would mean earlier — the opposite.",
      },
      {
        id: "late-c2",
        phraseId: "late-3",
        prompt: "Give the reason in one line.",
        options: [
          { text: "Die Bahn hat Verspätung.", correct: true },
          { text: "Die Bahn hat Feierabend.", correct: false },
          { text: "Die Bahn schließt um zehn.", correct: false },
        ],
        why: "„Verspätung“ is the delay. It is the same word you see on the board.",
      },
      {
        id: "late-c3",
        phraseId: "late-4",
        prompt: "They say „Dann bis gleich.“",
        options: [
          { text: "They expect you shortly.", correct: true },
          { text: "They have cancelled and will write tomorrow.", correct: false },
          { text: "They want you to wait ten hours.", correct: false },
        ],
        why: "„Bis gleich“ is “see you shortly”. The plan is still on.",
      },
    ],
  },
  {
    id: "quieter",
    level: 4,
    title: "It is a bit loud",
    deTitle: "Es ist etwas laut",
    place: "Evening, in the stairwell. The flat above is loud, and you want a calm request, not a fight.",
    goal: "Ask them to be quieter after ten.",
    canDo: "ask a neighbor to be quieter without a scene",
    register: "„Sie“. Ask if you may interrupt, then the fact, then the request.",
    phrases: [
      {
        id: "quieter-1",
        speaker: "You",
        kind: "say",
        de: "Entschuldigung, darf ich Sie kurz stören?",
        en: "Sorry, may I disturb you for a moment?",
        tip: "This opens a delicate request. „Kurz“ promises it will be brief.",
      },
      {
        id: "quieter-2",
        speaker: "Neighbor",
        kind: "hear",
        de: "Ja, bitte.",
        en: "Yes, go ahead.",
        tip: "They are listening. Say the fact next, not a speech.",
      },
      {
        id: "quieter-3",
        speaker: "You",
        kind: "say",
        de: "Es ist abends etwas laut bei Ihnen.",
        en: "It's a bit loud at your place in the evenings.",
        tip: "„Bei Ihnen“ is their flat. „Etwas laut“ is honest and not dramatic.",
      },
      {
        id: "quieter-4",
        speaker: "Neighbor",
        kind: "hear",
        de: "Oh, das wusste ich nicht.",
        en: "Oh, I didn't know that.",
        tip: "They have heard you. This is the moment for the actual request.",
      },
      {
        id: "quieter-5",
        speaker: "You",
        kind: "say",
        de: "Könnten Sie nach zehn etwas leiser sein?",
        en: "Could you be a bit quieter after ten?",
        tip: "„Könnten Sie“ is the soft request. A clock time makes it concrete.",
      },
    ],
    checks: [
      {
        id: "quieter-c1",
        phraseId: "quieter-1",
        prompt: "You need a careful opening, not a complaint yet.",
        options: [
          { text: "Darf ich Sie kurz stören?", correct: true },
          { text: "Sie sind abends zu laut, Schluss.", correct: false },
          { text: "Ihre Tür schließt nicht richtig.", correct: false },
        ],
        why: "„Darf ich Sie kurz stören?“ asks permission to raise it.",
      },
      {
        id: "quieter-c2",
        phraseId: "quieter-3",
        prompt: "Say what is happening, calmly.",
        options: [
          { text: "Es ist abends etwas laut bei Ihnen.", correct: true },
          { text: "Es ist abends etwas laut bei uns, Sie müssen gehen.", correct: false },
          { text: "Nach zehn ist Ihr Feierabend falsch.", correct: false },
        ],
        why: "„Bei Ihnen“ places the noise in their flat. „Etwas“ keeps the tone even.",
      },
      {
        id: "quieter-c3",
        phraseId: "quieter-5",
        prompt: "Ask for quiet after 10.",
        options: [
          { text: "Könnten Sie nach zehn etwas leiser sein?", correct: true },
          { text: "Könnten Sie vor zehn etwas lauter sein?", correct: false },
          { text: "Nach zehn wiederholen Sie die Bahn.", correct: false },
        ],
        why: "„Leiser“ is quieter. „Nach zehn“ is after ten. „Könnten Sie“ keeps it a request.",
      },
    ],
  },
  {
    id: "mail",
    level: 4,
    title: "Send it by email",
    deTitle: "Per Mail, bitte",
    place: "You just hung up. The numbers went past too quickly. You call back.",
    goal: "Say you missed the figures and ask for them by email.",
    canDo: "ask for a short email after a fast phone call",
    register: "„Sie“. You are not blaming them. You are asking for a form you can read slowly.",
    phrases: [
      {
        id: "mail-1",
        speaker: "You",
        kind: "say",
        de: "Ich habe das am Telefon nicht ganz mitbekommen.",
        en: "I didn't quite catch that on the phone.",
        tip: "„Nicht ganz mitbekommen“ means you missed part of it. It does not accuse them of being unclear.",
        sound: "Mitbekommen here means “to catch what was said”.",
      },
      {
        id: "mail-2",
        speaker: "Staff",
        kind: "hear",
        de: "Was ist unklar?",
        en: "What is unclear?",
        tip: "Name the part. Do not say “everything”.",
      },
      {
        id: "mail-3",
        speaker: "You",
        kind: "say",
        de: "Die Zahlen. Können Sie mir das per Mail schicken?",
        en: "The figures. Can you send that to me by email?",
        tip: "Two beats: what you missed, then „per Mail“. That is the useful request.",
      },
      {
        id: "mail-4",
        speaker: "Staff",
        kind: "hear",
        de: "Ja, mache ich heute noch.",
        en: "Yes, I'll do it today.",
        tip: "„Heute noch“ means still today, not sometime. You can stop there.",
      },
      {
        id: "mail-5",
        speaker: "You",
        kind: "say",
        de: "Danke, dann lese ich es in Ruhe.",
        en: "Thanks, then I'll read it when I have a quiet moment.",
        tip: "„In Ruhe“ means without rushing. It explains why you wanted the email.",
      },
    ],
    checks: [
      {
        id: "mail-c1",
        phraseId: "mail-1",
        prompt: "The phone call went too fast. Say so without blaming them.",
        options: [
          { text: "Ich habe das am Telefon nicht ganz mitbekommen.", correct: true },
          { text: "Sie haben am Telefon falsch gesprochen.", correct: false },
          { text: "Das Telefon schließt um neun.", correct: false },
        ],
        why: "„Nicht ganz mitbekommen“ is “I didn’t quite catch it”. The problem stays with what you heard.",
      },
      {
        id: "mail-c2",
        phraseId: "mail-3",
        prompt: "You need the figures in writing.",
        options: [
          { text: "Die Zahlen. Können Sie mir das per Mail schicken?", correct: true },
          { text: "Die Zahlen sind laut. Können Sie leiser mailen?", correct: false },
          { text: "Per Mail komme ich zehn Minuten später.", correct: false },
        ],
        why: "Name the missing part, then „per Mail schicken“.",
      },
      {
        id: "mail-c3",
        phraseId: "mail-4",
        prompt: "They say „Ja, mache ich heute noch.“",
        options: [
          { text: "They will send it today.", correct: true },
          { text: "They will call again tonight and repeat it quickly.", correct: false },
          { text: "They cannot send email.", correct: false },
        ],
        why: "„Heute noch“ means later today. The email is agreed.",
      },
    ],
  },
];

export const scenes = [...coreScenes, ...extraScenes];

export const LEVELS = [
  {
    id: 1,
    de: "A1",
    en: "Simple daily needs",
    can: "Greet people, order, pay, and ask where something is.",
  },
  {
    id: 2,
    de: "A2",
    en: "Routine errands",
    can: "Get around, handle a short counter exchange, and ask for a time.",
  },
  {
    id: 3,
    de: "B1",
    en: "Real situations",
    can: "Explain a problem, keep a conversation going, and deal with a delay or a doctor.",
  },
  {
    id: 4,
    de: "B2",
    en: "Ordinary nuance",
    can: "Soften a request, fix a mix-up, and say what you mean without raising your voice.",
  },
];

export const placementItems = [
  {
    type: "self",
    prompt: "When you need something in German, what is actually true?",
    options: [
      { level: 1, text: "A1 — I mostly point, or I switch to English." },
      { level: 2, text: "A2 — I can greet people, order, and follow a slow answer." },
      { level: 3, text: "B1 — I can explain a problem and keep the conversation going." },
      { level: 4, text: "B2 — I can fix a mix-up and say what I mean." },
    ],
  },
  {
    type: "check",
    prompt: "At the bakery they ask: „Zusammen oder getrennt?“",
    options: [
      { text: "One bill, or separate bills?", correct: true },
      { text: "Eat in, or take away?", correct: false },
      { text: "Whole loaf, or sliced?", correct: false },
    ],
    why: "It is about payment. You will hear it as soon as the order is done.",
  },
  {
    type: "check",
    prompt: "You want two rolls. Which line would you actually say?",
    options: [
      { text: "Ich hätte gern zwei Brötchen.", correct: true },
      { text: "Ich will Brot du geben.", correct: false },
      { text: "Brötchen macht zwei bitte.", correct: false },
    ],
    why: "„Ich hätte gern“ plus the thing is the polite everyday order.",
  },
  {
    type: "check",
    prompt: "„Einzelfahrt oder Tageskarte?“",
    options: [
      { text: "One ride, or a pass for the whole day?", correct: true },
      { text: "Window seat, or aisle?", correct: false },
      { text: "Which city are you from?", correct: false },
    ],
    why: "Those are the two ordinary choices when you buy a local ticket.",
  },
  {
    type: "check",
    prompt: "A neighbor says: „Wie lange ungefähr?“",
    options: [
      { text: "They want to know how long something will go on.", correct: true },
      { text: "They want to know your shoe size.", correct: false },
      { text: "They are asking you to move out.", correct: false },
    ],
    why: "Answer with „bis“ and a time. That is the whole neighbor-conversation.",
  },
  {
    type: "check",
    prompt: "At the information desk you ask: „Schaffe ich den Anschluss noch?“",
    options: [
      { text: "Will I still make my connecting train?", correct: true },
      { text: "Is this seat reserved for someone else?", correct: false },
      { text: "Do you sell day passes here?", correct: false },
    ],
    why: "„Der Anschluss“ is the connection. „Schaffen“ means manage it in time.",
  },
];
