/** More everyday scenes so each CEFR band covers a real slice of daily life. */
export const extraScenes = [
  {
    id: "introduce",
    level: 1,
    title: "Saying who you are",
    deTitle: "Wer ich bin",
    place: "A neighbor stops you in the stairwell on your first week.",
    goal: "Say your name and where you live.",
    canDo: "introduce yourself with your name and flat",
    register: "„Sie“ at the start. Short answers are enough.",
    phrases: [
      { id: "introduce-1", speaker: "Neighbor", kind: "hear", de: "Guten Tag, wohnen Sie hier?", en: "Hello, do you live here?", tip: "A yes/no question. Answer it, then give your name." },
      { id: "introduce-2", speaker: "You", kind: "say", de: "Ja. Ich heiße Lena.", en: "Yes. My name is Lena.", tip: "„Ich heiße …“ is the ordinary way to say your name. Use your own." },
      { id: "introduce-3", speaker: "Neighbor", kind: "hear", de: "Welche Wohnung?", en: "Which flat?", tip: "They want the number, not your life story." },
      { id: "introduce-4", speaker: "You", kind: "say", de: "Wohnung drei, im zweiten Stock.", en: "Flat three, on the second floor.", tip: "In Germany the first floor above the ground is often the first. „Zweiter Stock“ is two floors up from the ground in everyday counting — listen for how your building says it." },
      { id: "introduce-5", speaker: "You", kind: "say", de: "Freut mich.", en: "Nice to meet you.", tip: "Say this after names. Then you can both go." },
    ],
    checks: [
      { id: "introduce-c1", phraseId: "introduce-2", prompt: "Tell them your name.", options: [{ text: "Ich heiße Lena.", correct: true }, { text: "Ich wohne Lena.", correct: false }, { text: "Wohnung heißt drei.", correct: false }], why: "„Ich heiße“ plus your name. „Wohnen“ is where you live, not what you are called." },
      { id: "introduce-c2", phraseId: "introduce-1", prompt: "They ask „Wohnen Sie hier?“", options: [{ text: "They are asking if you live in the building.", correct: true }, { text: "They are asking you to leave.", correct: false }, { text: "They want the time.", correct: false }], why: "„Wohnen“ is to live somewhere. „Hier“ is here." },
      { id: "introduce-c3", phraseId: "introduce-5", prompt: "You have both said your names. Close it.", options: [{ text: "Freut mich.", correct: true }, { text: "Welche Wohnung?", correct: false }, { text: "Zweiter Stock, bitte.", correct: false }], why: "„Freut mich“ is “pleased to meet you”. It ends the introduction." },
    ],
  },
  {
    id: "slow",
    level: 1,
    title: "I don't understand",
    deTitle: "Ich verstehe nicht",
    place: "Someone at a counter speaks quickly. You need them to slow down.",
    goal: "Say you don't understand and ask for it again, slowly.",
    canDo: "stop a fast sentence and ask for it slowly",
    register: "„Sie“. This is polite. People do it every day.",
    phrases: [
      { id: "slow-1", speaker: "You", kind: "say", de: "Entschuldigung, ich verstehe nicht.", en: "Sorry, I don't understand.", tip: "Say it as soon as you are lost. Waiting makes it harder." },
      { id: "slow-2", speaker: "You", kind: "say", de: "Können Sie das bitte langsam sagen?", en: "Can you say that slowly, please?", tip: "„Langsam“ is slowly. One clear request." },
      { id: "slow-3", speaker: "Staff", kind: "hear", de: "Natürlich. Nochmal.", en: "Of course. Once more.", tip: "„Nochmal“ means one more time. Listen now." },
      { id: "slow-4", speaker: "Staff", kind: "hear", de: "Das macht vier Euro.", en: "That'll be four euros.", tip: "This was the sentence you missed. Prices often hide in the fast part." },
      { id: "slow-5", speaker: "You", kind: "say", de: "Vier Euro. Danke, jetzt verstehe ich.", en: "Four euros. Thanks, now I understand.", tip: "Repeat the fact. „Jetzt verstehe ich“ tells them they can stop." },
    ],
    checks: [
      { id: "slow-c1", phraseId: "slow-1", prompt: "The sentence went past you.", options: [{ text: "Ich verstehe nicht.", correct: true }, { text: "Ich verstehe vier Euro.", correct: false }, { text: "Langsam wohne ich hier.", correct: false }], why: "„Ich verstehe nicht“ stops the exchange so they can help." },
      { id: "slow-c2", phraseId: "slow-2", prompt: "Ask them to say it slowly.", options: [{ text: "Können Sie das bitte langsam sagen?", correct: true }, { text: "Können Sie das bitte teuer sagen?", correct: false }, { text: "Nochmal ist vier.", correct: false }], why: "„Langsam sagen“ is the request. „Bitte“ keeps it polite." },
      { id: "slow-c3", phraseId: "slow-5", prompt: "You heard „vier Euro“. Show that you got it.", options: [{ text: "Vier Euro. Jetzt verstehe ich.", correct: true }, { text: "Vier Euro wohnen hier.", correct: false }, { text: "Ich verstehe nicht nochmal.", correct: false }], why: "Repeat the number, then say you understand." },
    ],
  },
  {
    id: "market",
    level: 1,
    title: "At the market",
    deTitle: "Auf dem Markt",
    place: "A Saturday market stall. You want apples.",
    goal: "Ask for a kilo and hear the price.",
    canDo: "buy fruit by the kilo",
    register: "Short, friendly, and loud enough for a stall.",
    phrases: [
      { id: "market-1", speaker: "You", kind: "say", de: "Ich hätte gern ein Kilo Äpfel.", en: "I'd like a kilo of apples.", tip: "„Ein Kilo“ plus the fruit. Point if you need to.", sound: "Äpfel sounds like EP-fel." },
      { id: "market-2", speaker: "Staff", kind: "hear", de: "Die roten oder die grünen?", en: "The red ones or the green ones?", tip: "They are asking which kind. Point, or say the color." },
      { id: "market-3", speaker: "You", kind: "say", de: "Die roten, bitte.", en: "The red ones, please.", tip: "„Die“ matches Äpfel. Repeat their word." },
      { id: "market-4", speaker: "Staff", kind: "hear", de: "Das sind zwei Euro fünfzig.", en: "That's two euros fifty.", tip: "„Das sind“ introduces the price. 2,50." },
      { id: "market-5", speaker: "You", kind: "say", de: "Gut. Ich nehme sie.", en: "Good. I'll take them.", tip: "„Ich nehme sie“ means you are buying those ones. „Sie“ is the apples." },
    ],
    checks: [
      { id: "market-c1", phraseId: "market-1", prompt: "You want one kilo of apples.", options: [{ text: "Ich hätte gern ein Kilo Äpfel.", correct: true }, { text: "Ein Euro Äpfel, bitte Kilo.", correct: false }, { text: "Die grünen sind zwei.", correct: false }], why: "Amount first: „ein Kilo“, then the fruit." },
      { id: "market-c2", phraseId: "market-2", prompt: "„Die roten oder die grünen?“", options: [{ text: "Which apples: red or green?", correct: true }, { text: "Is the price red or green?", correct: false }, { text: "Do you want one kilo or two?", correct: false }], why: "The colors are the two kinds of apple." },
      { id: "market-c3", phraseId: "market-5", prompt: "The red ones are fine. You will buy them.", options: [{ text: "Gut. Ich nehme sie.", correct: true }, { text: "Gut. Ich verstehe sie nicht.", correct: false }, { text: "Die roten wohnen hier.", correct: false }], why: "„Ich nehme sie“ closes the purchase." },
    ],
  },
  {
    id: "clock",
    level: 1,
    title: "What time is it?",
    deTitle: "Wie spät ist es?",
    place: "You are between appointments and your phone is dead.",
    goal: "Ask the time and understand a simple answer.",
    canDo: "ask the time and catch the hour",
    register: "„Sie“ with a stranger. One question.",
    phrases: [
      { id: "clock-1", speaker: "You", kind: "say", de: "Entschuldigung, wie spät ist es?", en: "Excuse me, what time is it?", tip: "This is the normal question. „Wie viel Uhr ist es?“ means the same." },
      { id: "clock-2", speaker: "Stranger", kind: "hear", de: "Es ist gleich drei.", en: "It's almost three.", tip: "„Gleich“ means almost, in a moment. Not exactly three yet." },
      { id: "clock-3", speaker: "You", kind: "say", de: "Gleich drei?", en: "Almost three?", tip: "Repeat it. If you heard wrong, they will say it again." },
      { id: "clock-4", speaker: "Stranger", kind: "hear", de: "Ja, in fünf Minuten.", en: "Yes, in five minutes.", tip: "So it is about 2:55. „In fünf Minuten“ is five minutes from now." },
      { id: "clock-5", speaker: "You", kind: "say", de: "Danke schön.", en: "Thank you.", tip: "That is the whole conversation." },
    ],
    checks: [
      { id: "clock-c1", phraseId: "clock-1", prompt: "Ask a stranger for the time.", options: [{ text: "Wie spät ist es?", correct: true }, { text: "Wie Kilo ist es?", correct: false }, { text: "Es ist gleich Wohnung.", correct: false }], why: "„Wie spät ist es?“ asks the time." },
      { id: "clock-c2", phraseId: "clock-2", prompt: "They say „Es ist gleich drei.“", options: [{ text: "It is almost 3:00.", correct: true }, { text: "It is exactly 3:00.", correct: false }, { text: "The shop closes for three days.", correct: false }], why: "„Gleich“ means it is about to be that hour." },
      { id: "clock-c3", phraseId: "clock-4", prompt: "„In fünf Minuten.“", options: [{ text: "Five minutes from now.", correct: true }, { text: "Five minutes ago.", correct: false }, { text: "The price is five euros.", correct: false }], why: "„In“ plus a time means from now until then." },
    ],
  },
  {
    id: "bus",
    level: 1,
    title: "One bus ticket",
    deTitle: "Ein Busticket",
    place: "You are on the bus. You need a ticket from the driver.",
    goal: "Buy one ticket and ask if this bus goes to the center.",
    canDo: "buy a single bus ticket from the driver",
    register: "Very short. The bus is moving.",
    phrases: [
      { id: "bus-1", speaker: "You", kind: "say", de: "Einmal Innenstadt, bitte.", en: "One ticket to the center, please.", tip: "„Einmal“ plus the place is enough for a single ride." },
      { id: "bus-2", speaker: "Driver", kind: "hear", de: "Zwei Euro achtzig.", en: "Two euros eighty.", tip: "Have the coins ready. 2,80." },
      { id: "bus-3", speaker: "You", kind: "say", de: "Fährt der Bus zur Innenstadt?", en: "Does this bus go to the center?", tip: "Ask before you sit down, if you are not sure." },
      { id: "bus-4", speaker: "Driver", kind: "hear", de: "Ja, die dritte Haltestelle.", en: "Yes, the third stop.", tip: "„Haltestelle“ is the stop. Count three from now." },
      { id: "bus-5", speaker: "You", kind: "say", de: "Danke.", en: "Thanks.", tip: "Take the ticket and hold on." },
    ],
    checks: [
      { id: "bus-c1", phraseId: "bus-1", prompt: "One ride to the center.", options: [{ text: "Einmal Innenstadt, bitte.", correct: true }, { text: "Dritte Innenstadt, bitte Kilo.", correct: false }, { text: "Der Bus heißt zwei Euro.", correct: false }], why: "„Einmal“ plus the destination is the ticket request." },
      { id: "bus-c2", phraseId: "bus-4", prompt: "„Die dritte Haltestelle.“", options: [{ text: "Get off at the third stop.", correct: true }, { text: "The ticket costs three euros.", correct: false }, { text: "This bus is the third one today.", correct: false }], why: "„Haltestelle“ is the stop. „Dritte“ is the third." },
      { id: "bus-c3", phraseId: "bus-3", prompt: "You are not sure this is the right bus.", options: [{ text: "Fährt der Bus zur Innenstadt?", correct: true }, { text: "Wohnen Sie in der Innenstadt?", correct: false }, { text: "Wie spät ist die Haltestelle?", correct: false }], why: "„Fährt … zu“ asks where the bus goes." },
    ],
  },
  {
    id: "post",
    level: 2,
    title: "At the post office",
    deTitle: "Auf der Post",
    place: "You have a small parcel for another city.",
    goal: "Send it and ask how long it takes.",
    canDo: "send a parcel and ask how long it takes",
    register: "„Sie“. Put the parcel on the counter and let them lead.",
    phrases: [
      { id: "post-1", speaker: "You", kind: "say", de: "Ich möchte dieses Paket schicken.", en: "I'd like to send this parcel.", tip: "„Dieses“ means this one, the one you are holding." },
      { id: "post-2", speaker: "Staff", kind: "hear", de: "Wohin geht es?", en: "Where is it going?", tip: "City or country. Have the address visible." },
      { id: "post-3", speaker: "You", kind: "say", de: "Nach Hamburg, bitte.", en: "To Hamburg, please.", tip: "„Nach“ plus a city. Not „zu“." },
      { id: "post-4", speaker: "You", kind: "say", de: "Wie lange dauert das?", en: "How long does that take?", tip: "Ask before you pay, if the day matters." },
      { id: "post-5", speaker: "Staff", kind: "hear", de: "Ein bis zwei Tage.", en: "One to two days.", tip: "„Bis“ here means “to”, as in a range. One or two days." },
    ],
    checks: [
      { id: "post-c1", phraseId: "post-1", prompt: "You want to send the parcel in your hand.", options: [{ text: "Ich möchte dieses Paket schicken.", correct: true }, { text: "Dieses Paket wohnt in Hamburg.", correct: false }, { text: "Wie lange ist das Paket?", correct: false }], why: "„Schicken“ is to send. „Dieses“ points to the one you have." },
      { id: "post-c2", phraseId: "post-3", prompt: "It is going to Hamburg.", options: [{ text: "Nach Hamburg, bitte.", correct: true }, { text: "Zu Hamburg Tage, bitte.", correct: false }, { text: "Hamburg dauert ein Kilo.", correct: false }], why: "„Nach“ is the preposition for a destination city." },
      { id: "post-c3", phraseId: "post-5", prompt: "„Ein bis zwei Tage.“", options: [{ text: "It takes one or two days.", correct: true }, { text: "It leaves at 1:00 or 2:00.", correct: false }, { text: "It costs between one and two euros.", correct: false }], why: "„Bis“ between two numbers is a range. Here, days." },
    ],
  },
  {
    id: "exchange",
    level: 2,
    title: "The wrong size",
    deTitle: "Die falsche Größe",
    place: "A clothes shop. The shirt is too small. You have the receipt.",
    goal: "Ask to exchange it for a larger size.",
    canDo: "exchange an item that is the wrong size",
    register: "„Sie“. Receipt in hand. No long story.",
    phrases: [
      { id: "exchange-1", speaker: "You", kind: "say", de: "Ich möchte das umtauschen.", en: "I'd like to exchange this.", tip: "„Umtauschen“ is exchange. „Zurückgeben“ would be a return for money." },
      { id: "exchange-2", speaker: "Staff", kind: "hear", de: "Haben Sie den Bon?", en: "Do you have the receipt?", tip: "„Der Bon“ is the receipt. This is the usual first question." },
      { id: "exchange-3", speaker: "You", kind: "say", de: "Ja, hier. Es ist zu klein.", en: "Yes, here. It's too small.", tip: "„Zu klein“ is too small. „Zu groß“ is too big." },
      { id: "exchange-4", speaker: "Staff", kind: "hear", de: "Welche Größe brauchen Sie?", en: "What size do you need?", tip: "Say the size you want, not only the problem." },
      { id: "exchange-5", speaker: "You", kind: "say", de: "Eine Größe größer, bitte.", en: "One size bigger, please.", tip: "If you don't know the number, this sentence still works." },
    ],
    checks: [
      { id: "exchange-c1", phraseId: "exchange-1", prompt: "You want a different size, not your money back.", options: [{ text: "Ich möchte das umtauschen.", correct: true }, { text: "Ich möchte das schicken.", correct: false }, { text: "Der Bon ist zu klein.", correct: false }], why: "„Umtauschen“ is the exchange. You are not sending it away." },
      { id: "exchange-c2", phraseId: "exchange-3", prompt: "The shirt does not fit. It is small.", options: [{ text: "Es ist zu klein.", correct: true }, { text: "Es ist zu langsam.", correct: false }, { text: "Es dauert zwei Tage.", correct: false }], why: "„Zu klein“ is too small. „Zu“ plus the adjective is the pattern." },
      { id: "exchange-c3", phraseId: "exchange-2", prompt: "„Haben Sie den Bon?“", options: [{ text: "They want the receipt.", correct: true }, { text: "They want a larger shirt from your bag.", correct: false }, { text: "They are asking your name.", correct: false }], why: "„Der Bon“ is the receipt from the shop." },
    ],
  },
  {
    id: "hair",
    level: 2,
    title: "A haircut",
    deTitle: "Beim Friseur",
    place: "You call a salon. You want a cut this week.",
    goal: "Book a haircut and name a day.",
    canDo: "book a haircut on the phone",
    register: "„Sie“ on the phone. Say what you want in the first sentence.",
    phrases: [
      { id: "hair-1", speaker: "You", kind: "say", de: "Guten Tag, ich brauche einen Termin zum Haareschneiden.", en: "Hello, I need an appointment for a haircut.", tip: "„Haareschneiden“ is the haircut. The salon knows the word." },
      { id: "hair-2", speaker: "Staff", kind: "hear", de: "Geht es am Dienstag?", en: "Would Tuesday work?", tip: "„Geht es“ means “is it possible”. Answer the day." },
      { id: "hair-3", speaker: "You", kind: "say", de: "Dienstag am Nachmittag, ja.", en: "Tuesday afternoon, yes.", tip: "„Nachmittag“ is afternoon. „Vormittag“ would be morning." },
      { id: "hair-4", speaker: "Staff", kind: "hear", de: "Um vier Uhr bei Anna.", en: "At four, with Anna.", tip: "Time plus the person. Write both down." },
      { id: "hair-5", speaker: "You", kind: "say", de: "Um vier bei Anna. Perfekt.", en: "At four with Anna. Perfect.", tip: "Repeat both facts so the booking is real." },
    ],
    checks: [
      { id: "hair-c1", phraseId: "hair-1", prompt: "You are calling for a haircut.", options: [{ text: "Ich brauche einen Termin zum Haareschneiden.", correct: true }, { text: "Ich brauche eine Größe größer.", correct: false }, { text: "Der Bon ist am Dienstag.", correct: false }], why: "Say „Termin“ and what it is for." },
      { id: "hair-c2", phraseId: "hair-2", prompt: "„Geht es am Dienstag?“", options: [{ text: "They are offering Tuesday.", correct: true }, { text: "They are closed on Tuesday.", correct: false }, { text: "Tuesday costs four euros.", correct: false }], why: "„Geht es“ is an offer of that day. Yes or a different day." },
      { id: "hair-c3", phraseId: "hair-5", prompt: "Confirm four o'clock with Anna.", options: [{ text: "Um vier bei Anna.", correct: true }, { text: "Um Anna bei vier.", correct: false }, { text: "Nachmittag ist der Bon.", correct: false }], why: "„Um“ the time, „bei“ the person." },
    ],
  },
  {
    id: "lost",
    level: 2,
    title: "A lost bag",
    deTitle: "Die Tasche ist weg",
    place: "You left a bag on the train. You are at the lost-and-found desk.",
    goal: "Describe the bag and where you lost it.",
    canDo: "report a lost bag",
    register: "„Sie“. Color, place, and roughly when.",
    phrases: [
      { id: "lost-1", speaker: "You", kind: "say", de: "Ich habe meine Tasche liegen lassen.", en: "I left my bag behind.", tip: "„Liegen lassen“ is the everyday way to say you left something somewhere." },
      { id: "lost-2", speaker: "Staff", kind: "hear", de: "Wo war das?", en: "Where was that?", tip: "The place. Be as exact as you can." },
      { id: "lost-3", speaker: "You", kind: "say", de: "Im Zug nach Hamburg, heute Morgen.", en: "On the train to Hamburg, this morning.", tip: "Place plus when. Two facts." },
      { id: "lost-4", speaker: "Staff", kind: "hear", de: "Wie sieht sie aus?", en: "What does it look like?", tip: "Color and size. „Sie“ is the bag, die Tasche." },
      { id: "lost-5", speaker: "You", kind: "say", de: "Sie ist schwarz und nicht groß.", en: "It's black and not big.", tip: "„Schwarz“ is black. Add one more detail if you have it." },
    ],
    checks: [
      { id: "lost-c1", phraseId: "lost-1", prompt: "You left the bag. You did not throw it away.", options: [{ text: "Ich habe meine Tasche liegen lassen.", correct: true }, { text: "Ich möchte die Tasche umtauschen.", correct: false }, { text: "Die Tasche dauert zwei Tage.", correct: false }], why: "„Liegen lassen“ means left behind." },
      { id: "lost-c2", phraseId: "lost-4", prompt: "„Wie sieht sie aus?“", options: [{ text: "They want a description of the bag.", correct: true }, { text: "They want the train ticket.", correct: false }, { text: "They are asking if you live in Hamburg.", correct: false }], why: "„Wie sieht … aus“ asks what something looks like." },
      { id: "lost-c3", phraseId: "lost-5", prompt: "The bag is black and smallish.", options: [{ text: "Sie ist schwarz und nicht groß.", correct: true }, { text: "Sie ist gleich drei und rot.", correct: false }, { text: "Sie wohnt im Zug.", correct: false }], why: "Color plus size is enough for a first description." },
    ],
  },
  {
    id: "keys",
    level: 2,
    title: "Locked out",
    deTitle: "Der Schlüssel",
    place: "You are outside your building. The keys are inside. A neighbor answers.",
    goal: "Explain and ask to wait inside, or to use their phone.",
    canDo: "explain that you are locked out",
    register: "„Sie“ if you do not know them well. The problem in one sentence.",
    phrases: [
      { id: "keys-1", speaker: "You", kind: "say", de: "Entschuldigung, ich habe mich ausgesperrt.", en: "Sorry, I've locked myself out.", tip: "„Sich aussperren“ is exactly this situation. People know it." },
      { id: "keys-2", speaker: "Neighbor", kind: "hear", de: "Oh nein. Haben Sie einen zweiten Schlüssel?", en: "Oh no. Do you have a second key?", tip: "A practical question. Yes or no." },
      { id: "keys-3", speaker: "You", kind: "say", de: "Nein. Der ist in der Wohnung.", en: "No. It's in the flat.", tip: "„Der“ is the key, der Schlüssel." },
      { id: "keys-4", speaker: "You", kind: "say", de: "Kann ich kurz Ihr Telefon benutzen?", en: "Can I use your phone for a moment?", tip: "„Kurz“ keeps the favor small. „Benutzen“ is to use." },
      { id: "keys-5", speaker: "Neighbor", kind: "hear", de: "Ja, klar. Kommen Sie rein.", en: "Yes, of course. Come in.", tip: "„Rein“ is in. You are being helped." },
    ],
    checks: [
      { id: "keys-c1", phraseId: "keys-1", prompt: "The keys are inside and you are outside.", options: [{ text: "Ich habe mich ausgesperrt.", correct: true }, { text: "Ich habe die Tür umgetauscht.", correct: false }, { text: "Der Schlüssel dauert zwei Tage.", correct: false }], why: "„Sich aussperren“ is to lock yourself out." },
      { id: "keys-c2", phraseId: "keys-4", prompt: "You need their phone for a minute.", options: [{ text: "Kann ich kurz Ihr Telefon benutzen?", correct: true }, { text: "Kann ich Ihr Telefon schicken?", correct: false }, { text: "Ihr Telefon ist zu klein.", correct: false }], why: "„Benutzen“ is use. „Kurz“ says it will be brief." },
      { id: "keys-c3", phraseId: "keys-5", prompt: "„Kommen Sie rein.“", options: [{ text: "They are inviting you inside.", correct: true }, { text: "They want you to leave the building.", correct: false }, { text: "They are calling the police.", correct: false }], why: "„Rein“ means in. The help has started." },
    ],
  },
  {
    id: "reschedule",
    level: 4,
    title: "Moving an appointment",
    deTitle: "Den Termin verschieben",
    place: "You cannot make Thursday. You call to move it, with a reason.",
    goal: "Postpone the appointment and offer a new window.",
    canDo: "move an appointment and give a reason",
    register: "„Sie“. Reason first, then the new time you can do.",
    phrases: [
      { id: "reschedule-1", speaker: "You", kind: "say", de: "Ich muss den Termin am Donnerstag verschieben.", en: "I have to move Thursday's appointment.", tip: "„Verschieben“ is postpone or move. It is not a cancellation." },
      { id: "reschedule-2", speaker: "You", kind: "say", de: "Ich muss unerwartet arbeiten.", en: "I unexpectedly have to work.", tip: "One reason. „Unerwartet“ means it was not planned." },
      { id: "reschedule-3", speaker: "Staff", kind: "hear", de: "Wann würde es denn gehen?", en: "When would it work, then?", tip: "They want a window, not an apology." },
      { id: "reschedule-4", speaker: "You", kind: "say", de: "Nächste Woche Dienstag oder Mittwoch, nach zwei.", en: "Next week, Tuesday or Wednesday, after two.", tip: "Give two days and a part of the day. That is easier to answer than one exact minute." },
      { id: "reschedule-5", speaker: "Staff", kind: "hear", de: "Mittwoch um halb drei hätten wir Zeit.", en: "We'd have time on Wednesday at half past two.", tip: "„Halb drei“ is 2:30. Confirm it out loud before you hang up.", sound: "Halb drei is 2:30, thirty minutes before three." },
    ],
    checks: [
      { id: "reschedule-c1", phraseId: "reschedule-1", prompt: "You still want the appointment, but not on Thursday.", options: [{ text: "Ich muss den Termin am Donnerstag verschieben.", correct: true }, { text: "Ich muss den Termin am Donnerstag absagen für immer.", correct: false }, { text: "Donnerstag ist zu klein.", correct: false }], why: "„Verschieben“ moves it. It stays on the calendar." },
      { id: "reschedule-c2", phraseId: "reschedule-5", prompt: "„Halb drei“ on Wednesday. What time is that?", options: [{ text: "2:30", correct: true }, { text: "3:30", correct: false }, { text: "3:00", correct: false }], why: "Halb drei is half an hour before three." },
      { id: "reschedule-c3", phraseId: "reschedule-4", prompt: "Offer the days you can do.", options: [{ text: "Dienstag oder Mittwoch, nach zwei.", correct: true }, { text: "Nach zwei ist der Bon schwarz.", correct: false }, { text: "Unerwartet umtauschen, bitte.", correct: false }], why: "Two options plus a time of day gives them room." },
    ],
  },
  {
    id: "recommend",
    level: 4,
    title: "Recommending a place",
    deTitle: "Eine Empfehlung",
    place: "A friend wants somewhere to eat. You know a place and why.",
    goal: "Recommend it and say who it is good for.",
    canDo: "recommend a place and give a reason",
    register: "„Du“. A reason is what makes it a recommendation, not just a name.",
    phrases: [
      { id: "recommend-1", speaker: "Friend", kind: "hear", de: "Kennst du was in der Nähe?", en: "Do you know a place nearby?", tip: "„Was“ here means a place. They want a suggestion." },
      { id: "recommend-2", speaker: "You", kind: "say", de: "Ja, das Café an der Ecke.", en: "Yes, the café on the corner.", tip: "Name it so they can find it. „An der Ecke“ is on the corner." },
      { id: "recommend-3", speaker: "You", kind: "say", de: "Das Essen ist gut und nicht zu teuer.", en: "The food is good and not too expensive.", tip: "Two reasons. „Nicht zu teuer“ is a useful everyday judgment." },
      { id: "recommend-4", speaker: "Friend", kind: "hear", de: "Muss man reservieren?", en: "Do you have to book?", tip: "A practical follow-up. Answer from what you know." },
      { id: "recommend-5", speaker: "You", kind: "say", de: "Unter der Woche nicht. Am Freitag schon.", en: "Not on weekdays. On Friday, yes.", tip: "„Unter der Woche“ is Monday to Friday. „Schon“ here means yes, you do." },
    ],
    checks: [
      { id: "recommend-c1", phraseId: "recommend-3", prompt: "Say why you like it, in one line.", options: [{ text: "Das Essen ist gut und nicht zu teuer.", correct: true }, { text: "Das Essen muss ich verschieben.", correct: false }, { text: "Die Ecke ist ausgesperrt.", correct: false }], why: "A recommendation needs a reason. Price and quality are ordinary ones." },
      { id: "recommend-c2", phraseId: "recommend-4", prompt: "„Muss man reservieren?“", options: [{ text: "They are asking if a booking is necessary.", correct: true }, { text: "They are asking you to pay for them.", correct: false }, { text: "They want the café to move.", correct: false }], why: "„Reservieren“ is to book a table." },
      { id: "recommend-c3", phraseId: "recommend-5", prompt: "Weekdays are fine without a booking. Friday is not.", options: [{ text: "Unter der Woche nicht. Am Freitag schon.", correct: true }, { text: "Unter der Woche schon teuer. Freitag nie.", correct: false }, { text: "Halb Freitag an der Ecke.", correct: false }], why: "„Nicht“ answers the weekday. „Schon“ answers Friday: yes, book then." },
    ],
  },
  {
    id: "disagree",
    level: 4,
    title: "Seeing it differently",
    deTitle: "Das sehe ich anders",
    place: "A colleague wants to send the email today. You think tomorrow morning is better.",
    goal: "Disagree calmly and give the reason.",
    canDo: "disagree without sounding rude",
    register: "„Du“ with this colleague. The soft form is „ich sehe das anders“, not „du liegst falsch“.",
    phrases: [
      { id: "disagree-1", speaker: "Colleague", kind: "hear", de: "Wir schicken die Mail heute noch, oder?", en: "We'll send the email today, right?", tip: "They expect agreement. You can still slow it down." },
      { id: "disagree-2", speaker: "You", kind: "say", de: "Ich sehe das etwas anders.", en: "I see it a bit differently.", tip: "„Etwas“ softens it. This is the normal polite disagreement." },
      { id: "disagree-3", speaker: "You", kind: "say", de: "Morgen früh haben wir den Text in Ruhe gelesen.", en: "Tomorrow morning we'll have read it calmly.", tip: "Give the reason. „In Ruhe“ means without rushing." },
      { id: "disagree-4", speaker: "Colleague", kind: "hear", de: "Meinst du, das reicht zeitlich?", en: "Do you think that's enough time?", tip: "They are asking about the deadline, not attacking you." },
      { id: "disagree-5", speaker: "You", kind: "say", de: "Ja. Der Termin ist erst am Nachmittag.", en: "Yes. The meeting isn't until the afternoon.", tip: "„Erst“ means not until. The afternoon is still early enough." },
    ],
    checks: [
      { id: "disagree-c1", phraseId: "disagree-2", prompt: "You do not agree, and you want to stay friendly.", options: [{ text: "Ich sehe das etwas anders.", correct: true }, { text: "Du liegst falsch, die Mail ist schlecht.", correct: false }, { text: "Wir müssen die Mail umtauschen.", correct: false }], why: "„Etwas anders sehen“ is the calm everyday disagreement." },
      { id: "disagree-c2", phraseId: "disagree-5", prompt: "The meeting is in the afternoon, so morning is enough.", options: [{ text: "Der Termin ist erst am Nachmittag.", correct: true }, { text: "Der Termin ist schon vorbei am Morgen.", correct: false }, { text: "Erst die Mail ist zu klein.", correct: false }], why: "„Erst“ plus a time means not before then." },
      { id: "disagree-c3", phraseId: "disagree-4", prompt: "„Meinst du, das reicht zeitlich?“", options: [{ text: "They are asking if there is enough time.", correct: true }, { text: "They are refusing to read the email.", correct: false }, { text: "They want you to cancel the meeting.", correct: false }], why: "„Reichen“ is to be enough. „Zeitlich“ means in terms of time." },
    ],
  },
  {
    id: "wrongfile",
    level: 4,
    title: "The wrong file",
    deTitle: "Die falsche Datei",
    place: "You emailed the wrong document. You write or call to own it and fix it.",
    goal: "Say what went wrong and what you will do now.",
    canDo: "own a small work mistake and fix it",
    register: "„Sie“ if it is a client, or this version with „Sie“. No long apology.",
    phrases: [
      { id: "wrongfile-1", speaker: "You", kind: "say", de: "Ich habe Ihnen vorhin die falsche Datei geschickt.", en: "I sent you the wrong file earlier.", tip: "State the fact. „Vorhin“ is earlier today." },
      { id: "wrongfile-2", speaker: "You", kind: "say", de: "Das tut mir leid.", en: "I'm sorry about that.", tip: "One sentence of regret is enough. Then the fix." },
      { id: "wrongfile-3", speaker: "Client", kind: "hear", de: "Kein Problem. Schicken Sie mir die richtige?", en: "No problem. Will you send me the right one?", tip: "They want the correction, not a speech." },
      { id: "wrongfile-4", speaker: "You", kind: "say", de: "Ja, ich schicke sie in den nächsten Minuten.", en: "Yes, I'll send it in the next few minutes.", tip: "A time makes the promise real. „Sie“ is the file, die Datei." },
      { id: "wrongfile-5", speaker: "You", kind: "say", de: "Die neue Mail hat den Betreff „korrekte Fassung“.", en: "The new email has the subject “correct version”.", tip: "Tell them how to recognize it, so the wrong file is not used." },
    ],
    checks: [
      { id: "wrongfile-c1", phraseId: "wrongfile-1", prompt: "You sent the wrong document earlier today.", options: [{ text: "Ich habe Ihnen vorhin die falsche Datei geschickt.", correct: true }, { text: "Ich sehe die Datei etwas anders.", correct: false }, { text: "Die Datei ist ausgesperrt.", correct: false }], why: "„Die falsche Datei“ names the mistake. „Vorhin“ places it today." },
      { id: "wrongfile-c2", phraseId: "wrongfile-4", prompt: "You will send the right one very soon.", options: [{ text: "Ich schicke sie in den nächsten Minuten.", correct: true }, { text: "Ich schicke sie nächstes Jahr in Ruhe.", correct: false }, { text: "Die Minuten sind zu teuer.", correct: false }], why: "A short, real time is the useful part of the apology." },
      { id: "wrongfile-c3", phraseId: "wrongfile-3", prompt: "„Schicken Sie mir die richtige?“", options: [{ text: "They want the correct file.", correct: true }, { text: "They want you to delete the project.", correct: false }, { text: "They are asking for a receipt.", correct: false }], why: "„Die richtige“ is the right one, as opposed to „die falsche“." },
    ],
  },
  {
    id: "because",
    level: 4,
    title: "I can't come until eight",
    deTitle: "Erst nach acht",
    place: "Friends are meeting for dinner. You can come, but not at seven.",
    goal: "Join the plan and explain the limit.",
    canDo: "join a plan while explaining why you will be later",
    register: "„Du“. Say yes to the plan, then the limit, then the reason.",
    phrases: [
      { id: "because-1", speaker: "Friend", kind: "hear", de: "Wir treffen uns um sieben. Kommst du?", en: "We're meeting at seven. Are you coming?", tip: "You can say yes to coming and no to the hour." },
      { id: "because-2", speaker: "You", kind: "say", de: "Ich komme gern, aber erst nach acht.", en: "I'd love to come, but not until after eight.", tip: "„Gern“ is the yes. „Erst nach acht“ is the limit." },
      { id: "because-3", speaker: "You", kind: "say", de: "Ich habe vorher noch einen Termin.", en: "I still have an appointment before that.", tip: "„Vorher“ means before the dinner. One reason." },
      { id: "because-4", speaker: "Friend", kind: "hear", de: "Passt. Wir sind eh länger da.", en: "Fine. We'll be there a while anyway.", tip: "„Eh“ is anyway, in speech. The plan still includes you." },
      { id: "because-5", speaker: "You", kind: "say", de: "Super. Ich schreibe, wenn ich losgehe.", en: "Great. I'll text when I head out.", tip: "„Losgehen“ is to set off. They know you are really coming." },
    ],
    checks: [
      { id: "because-c1", phraseId: "because-2", prompt: "You are coming, but not at seven.", options: [{ text: "Ich komme gern, aber erst nach acht.", correct: true }, { text: "Ich komme nicht, der Termin ist falsch.", correct: false }, { text: "Nach acht sehe ich das anders.", correct: false }], why: "„Gern“ accepts. „Erst nach“ moves your arrival, not the friendship." },
      { id: "because-c2", phraseId: "because-4", prompt: "„Wir sind eh länger da.“", options: [{ text: "They will still be there when you arrive.", correct: true }, { text: "They have cancelled because of you.", correct: false }, { text: "They want you there at seven exactly.", correct: false }], why: "„Länger da“ means they are staying. „Eh“ means this was already true." },
      { id: "because-c3", phraseId: "because-3", prompt: "Say why eight is your earliest.", options: [{ text: "Ich habe vorher noch einen Termin.", correct: true }, { text: "Ich habe die Datei vorher geschickt.", correct: false }, { text: "Vorher ist das Essen zu teuer.", correct: false }], why: "„Vorher“ ties the appointment to the time before dinner." },
    ],
  },
];
